### ISSUE TITLE
请问一下透传ua是哪一部分代码？

### ISSUE THREAD

**Issue by xiaomengzaici** [chen3861229/embyExternalUrl#11]
我自己搞了一套，只需要一个emby.js就可以全部完成反代，但是目前115只能获得链接而无法播放，所以想询问一下大佬您的代码

**Comment by sjtuross** [comment]
我觉得你搜索cilentSelfAlistRule应该可以找到答案

**Comment by chen3861229** [comment]
ad8cf4ea00b09fad156cc59f37a8d26e9decb718
只用看更改中ua的关键字，其余不用关注。
单体的历史emby.js的话，最开始一行添加，const ua = r.headersIn["User-Agent"];
并且将所以fetchAlistPathApi的方法传递ua参数，并且最终再方法的ngx.fetch的headers参数加上【"User-Agent": ua】即可
