### ISSUE TITLE
启动时候显示这个错误  启动不了

### ISSUE THREAD

**Issue by Oheyu99** [chen3861229/embyExternalUrl#12]
ginx: [emerg] cannot load certificate "/etc/nginx/conf.d/cert/fullchain.pem": BIO_new_file() failed (SSL: error:80000002:system library::No such file or directory:calling fopen(/etc/nginx/conf.d/cert/fullchain.pem, r) error:10000080:BIO routines::no such file)

**Comment by chen3861229** [comment]
因为plex的客户端对https有部分强制要求，所以默认配置切换为了域名+https的配置，为了避免客户端出现问题，建议为域名申请证书文件并将nginx的证书路径改成自己的。
如果想临时测试功能，也可以将plex.conf中## SSL SETTINGS ##的相关配置注释掉，并打开listen 80;改为自己需要监听的端口使用http也行
