### ISSUE TITLE
115盘直链浏览器播放不了，能不能自动回退到非直链模式

### ISSUE THREAD

**Issue by anyingxiuluo** [chen3861229/embyExternalUrl#16]
大佬，115盘直链浏览器播放不了，能不能自动回退到非直链模式

**Comment by chen3861229** [comment]
disableRedirectRule这个参数可以指定禁用直链的规则，但是匹配范围比较大，可以尝试填一下

你这种情况是直链已经转发到浏览器了，但是115没有响应允许跨域标识导致被浏览器强制拦截了，代码层面是处理成功的，做不了判断，看下浏览器控制台确认下是不是跨域问题，装下浏览器拓展解决比较合适
