### ISSUE TITLE
能获取到IPTV地址但是无法播放

### ISSUE THREAD

**Issue by xiaomengzaici** [chen3861229/embyExternalUrl#17]
我这次全面更换成了大佬的代码，我发现无法使用iptv了
![QQ截图20240401220339](https://github.com/chen3861229/embyExternalUrl/assets/87969148/581f9ec3-ca7e-4b1d-9ebe-e5b86eb1a0a7)

**Comment by chen3861229** [comment]
请问这个地址是局域网资源吗？
【http://[xxx]:80/dbiptv.sn.chinamobile.com/PLTV/88888888/224/32/21226231/1.m3u8】

**Comment by chen3861229** [comment]
我这边用手机网络测试了下，此链接无法访问，没用反代的原始emby可以播放此直播吗？
http://[2409:8087:7000:20::4]:80/dbiptv.sn.chinamobile.com/PLTV/88888888/224/32/21226231/1.m3u8

**Comment by chen3861229** [comment]
我这边找了个直播源测试，已经修复好了，是前几天代码打日志报错了，更新下最新代码就可以了

**Comment by chen3861229** [comment]
啊，不至于吧，是直播失败还是云盘的挂载内容播放失败？我这边测试没啥问题，方便提供下日志吗

**Comment by chen3861229** [comment]
当前nginx有配https证书吗？

**Comment by chen3861229** [comment]
好吧，那不是https的问题，还有种可能是url编码的问题，把mount emby那里的链接和下边编码后的链接单独用支持直播的软件测试下

**Comment by chen3861229** [comment]
感觉不是很对劲啊，日志，目前新代码没对转发后的url编码这么彻底，我这边测试直播日志是这样的

2024/04/02 22:58:58 [warn] 115#115: *36221 js: cached PlaybackInfo path, will skip excess fetchEmbyFilePath
2024/04/02 22:58:58 [warn] 115#115: *36221 js: 0ms, mount emby file path: https://siwazywcdn2.com:5278/zhongwenzimu/5PzEAi0h/index.m3u8
2024/04/02 22:58:58 [warn] 115#115: *36221 js: embyPathMapping: [[0,0,"/AList",""]]
2024/04/02 22:58:58 [warn] 115#115: *36221 js: mapped emby file path: https://siwazywcdn2.com:5278/zhongwenzimu/5PzEAi0h/index.m3u8
2024/04/02 22:58:58 [warn] 115#115: *36221 js: redirect to: https://siwazywcdn2.com:5278/zhongwenzimu/5PzEAi0h/index.m3u8

**Comment by chen3861229** [comment]
怀疑和ipv6地址上的那这个中括号被编码转义了有关，[]

**Comment by chen3861229** [comment]
emby和nginx没开v6没关系，这个v6地址是转发给客户端请求的，客户端能联通v6就行。
是的，原始emby能正常的话地址应该没啥问题，我找的直播源v6是失效的，所以没充分测试。。。只能等明天我找个v6直播地址排查一下了，因为最近改的东西比较多，大概是缓存的那个路径编码影响到了

**Comment by chen3861229** [comment]
已经修复，是前几天提交的多余编码方式导致
e1f462bc9411b3ad2e027d17c195c6d899d6c695

**Comment by chen3861229** [comment]
调用第三方播放器外挂字幕没法在 302 的 URL 上传递，播放器的入参支持情况也不统一，只能用官方形式的客户端了，可以加载外挂字幕，文档里有少量相关的描述，或者使用另外那两个添加外部播放器按钮的脚本，不过前提也是对应的播放器支持传递 http 形式的字幕链接

**Comment by chen3861229** [comment]
1.多谢提供日志很清晰，是我判断的问题，已经修复了
c5354c68476698a3bc481909f9f2cadf4c0de335

**Comment by chen3861229** [comment]
> 新问题：ios端fileball无法通过反代端口访问资源

所有都不行吗？还是只有 IPv6 的直播不行？
fileball 前段时间朋友协助简单测试过了，普通的媒体资源貌似是可以正常直链的
