### ISSUE TITLE
util.js中会报错

### ISSUE THREAD

**Issue by NickLuo21** [chen3861229/embyExternalUrl#18]
![CleanShot 2024-04-02 at 14 09 30@2x](https://github.com/chen3861229/embyExternalUrl/assets/17668622/3fc947fb-6cef-468c-84d4-c116c3eed836)
![CleanShot 2024-04-02 at 14 10 12@2x](https://github.com/chen3861229/embyExternalUrl/assets/17668622/e583d478-976f-40b9-90f2-18c72d37e997)

**Comment by chen3861229** [comment]
辛苦帮忙排错了，确实是我大意了，新提交已经修复
92a372a390b478e78a2c5250a3a5637d315a1c2b
