### ISSUE TITLE
isRemote能否支持一下Windows的路径

### ISSUE THREAD

**Issue by NickLuo21** [chen3861229/embyExternalUrl#19]
emby.js中的isRemote判断加一下Windows路径判断应该就可以了，我本地这样改了测试没有问题
`let isRemote = !embyRes.path.startsWith("/") && !embyRes.path.startsWith("\\");`

**Comment by chen3861229** [comment]
好的，多谢提供测试情况，我晚上回去合并一下

**Comment by chen3861229** [comment]
提交了，可以试一下
dd14df2044b56220d825a175a7b51c01c015c1a0
