### ISSUE TITLE
embyWebAddExternalUrl: 如果文件是STRM，且未播放过，则web页面无图标。

### ISSUE THREAD

**Issue by Swiftfrog** [chen3861229/embyExternalUrl#20]
你好。

我发现一个问题，embyWebAddExternalUrl如果是mp4，mk等文件，则有第三方播放器图标。

但是如果是strm文件，点进去，则没有。

然后你点播放strm的电影，接着退出来，最后有第三方播放器了。

这个问题能否帮一下？

**Comment by chen3861229** [comment]
已做修复
c0ffac66667d455174cd24e3cacca3f45556a55b

**Comment by Swiftfrog** [comment]
搞定了，非常感谢。
