### ISSUE TITLE
请问程序能否自动识别播放请求来自于内网还是外网？

### ISSUE THREAD

**Issue by shenxianmq** [chen3861229/embyExternalUrl#21]
如果来自于内网的话就不需要走直连，如果是外网的话就走302，因为内网走302，用infuse这类第三方播放器播放的时候反而会变慢

**Comment by chen3861229** [comment]
access.log
![image](https://github.com/chen3861229/embyExternalUrl/assets/42368856/b3273d3d-7f47-49af-9b6a-884733b1adea)

error.log
````
2024/04/07 22:26:37 [warn] 54#54: *1000 js: hit isDisableRedirect: ["r.variables.remote_addr",0,["172.","10.","192.","[fd00:"]]
2024/04/07 22:26:37 [warn] 54#54: *1000 js: use original link
2024/04/07 22:26:37 [warn] 54#54: *1000 js: success: fetchEmbyNotificationsAdmin: {"Name":"【emby2Alist】","Description":"use original link success"}
2024/04/07 22:26:37 [warn] 54#54: *1000 js: success: fetchEmbySessionsMessage: {"Header":"【emby2Alist】","Text":"use original link success","TimeoutMs":0}
````

**Comment by shenxianmq** [comment]
谢谢，已经更新

**Comment by shenxianmq** [comment]
我测试了一下，发现不管是内网还是外网，sourceStr都是172.20.0.1

**Comment by chen3861229** [comment]
额，刚才考虑到这种风险了，但是没过多修复，nginx你应该用的是docker的桥接模式吧？172.20是桥接网段吗？

暂时的处理手段是改为host网络，这个问题得明天再看看了

**Comment by chen3861229** [comment]
测试了，必须得把bridge改为host模式，不然流量都是先到docker的网桥然后转发到容器上，就会导致nginx的$remote_addr变量变为docker的内部地址，导致判断失效，这种情况是无法区分客户端内网外的，我去文档上加下说明
![image](https://github.com/chen3861229/embyExternalUrl/assets/42368856/c296edca-e120-4a05-9a58-2891e4966586)

**Comment by shenxianmq** [comment]
当前8095映射的是80端口，如果改成host就得占用80端口了，可以把这个80端口换成不常见的端口吗

**Comment by shenxianmq** [comment]
好的，这么说只要去emby.conf里添加指定端口就可以了,谢谢作者大大

**Comment by shenxianmq** [comment]
我发现用host模式下2024/04/08 14:56:22 [warn] 22#22: *104 js: sourceStr: 172.21.0.2
还是172网段发起的，还是不能解决问题

**Comment by chen3861229** [comment]
https://github.com/chen3861229/embyExternalUrl/issues/21
