### ISSUE TITLE
第三方客户端 Yamby 无法直链播放

### ISSUE THREAD

**Issue by envyafish** [chen3861229/embyExternalUrl#23]
![95dc92b0d760bdee343cb0004af1e84](https://github.com/chen3861229/embyExternalUrl/assets/125949466/984ee872-7217-4554-8f29-103e9f18e0fe)

**Comment by chen3861229** [comment]
新代码已经修复了此问题，需要更新下代码
````
# Redirect the stream to njs
location ~* /videos/(.*)/(stream|original)
````

**Comment by envyafish** [comment]
完美了

**Comment by YanTaocheng** [comment]
> 新代码已经修复了此问题，需要更新下代码
> ````
> # Redirect the stream to njs
> location ~* /videos/(.*)/(stream|original)
> ````
> 65b88b0c82a4914f537fd1e5f76dc86d9b84ca41

刚好烦这个问题呢，大佬牛逼
