### ISSUE TITLE
启动容器后报错

### ISSUE THREAD

**Issue by shenxianmq** [chen3861229/embyExternalUrl#24]
宿主机系统为unraid，创建容器后日志中报错，请问会是什么原因？
/docker-entrypoint.sh: Launching /docker-entrypoint.d/30-tune-worker-processes.sh
/docker-entrypoint.sh: Configuration complete; ready for start up
2024/04/11 09:36:16 [emerg] 1#1: "js_set" directive is not allowed here in /etc/nginx/conf.d/emby.conf:14
nginx: [emerg] "js_set" directive is not allowed here in /etc/nginx/conf.d/emby.conf:14
/docker-entrypoint.sh: /docker-entrypoint.d/ is not empty, will attempt to perform configuration
/docker-entrypoint.sh: Looking for shell scripts in /docker-entrypoint.d/
/docker-entrypoint.sh: Launching /docker-entrypoint.d/10-listen-on-ipv6-by-default.sh
10-listen-on-ipv6-by-default.sh: info: /etc/nginx/conf.d/default.conf is not a file or does not exist
/docker-entrypoint.sh: Launching /docker-entrypoint.d/20-envsubst-on-templates.sh
/docker-entrypoint.sh: Launching /docker-entrypoint.d/30-tune-worker-processes.sh
/docker-entrypoint.sh: Configuration complete; ready for start up

**Comment by chen3861229** [comment]
2020年的nginx的版本太老了，内置的njs不支持js_set指令，需要更新下nginx
https://github.com/bpking1/embyExternalUrl/issues/75

**Comment by chen3861229** [comment]
请问是dock-compose默认拉取下来的版本吗？如果是的话，我这边需要更新下yaml了

**Comment by shenxianmq** [comment]
是的，默认拉取的，直接运行的docker compose命令

**Comment by chen3861229** [comment]
nginx默认镜像修改了，应该能解决
7795958c9894abf3e214a706626075696d3691ad
