### ISSUE TITLE
日志有返回直链，但是emby一直是黑屏状态

### ISSUE THREAD

**Issue by shenxianmq** [chen3861229/embyExternalUrl#25]
如题，当我点进去一个视频，退出来后，再点进去，会出现这样的问题

**Comment by shenxianmq** [comment]
并且有时候拖动进度条也会没反应

**Comment by chen3861229** [comment]
使用环境是什么样的？
我这边embyWeb + 阿里云盘没复现出来，方便的话可以看下浏览器控制台网络日志，看下是不是网盘提供商返回了错误信息

**Comment by chen3861229** [comment]
我这边用115+windows官方客户端尝试复现了下，不过情况不太一样，我是第一次都播放不出来，也是直链返回了且可以访问，日志一切正常，nginx配置了https，且客户端是用http登录的(307重定向到了https)
=>
退出登录，服务器地址使用https链接，绕过http的重定向兼容，播放就是正常的很快，随意拖动进度条，查看日志直链只有一次

不知道我这个情况能不能适用

**Comment by shenxianmq** [comment]
服务器使用https地址是通过反代的嘛，反代走的网桥的172不就变成内网了吗？
另外我怀疑可能是115的问题，我们其他群友也反应我这个问题的

**Comment by chen3861229** [comment]
1.直接在nginx-emby上配置的反代https，我是用得host(主机)模式，因为走了网桥或者其他代理而没设置[X-Real-IP][X-Forwarded-xxx]之类的代理头会导致流量识别不准确，emby控制台看到的播放用户是内网ip，没有参考性了
2.我也感觉是115的问题，毕竟它限制比较严格，目前还不清楚是什么原因导致的
3.Web端倒是没这个问题，就是很多格式不支持播放
