### ISSUE TITLE
长时间暂停之后，无法继续播放。

### ISSUE THREAD

**Issue by Hiccup90** [chen3861229/embyExternalUrl#26]
暂停超过一段时间之后，会把之前缓存的播放完就会自动跳到下一集。

这个应该不算bug。不过可能的话，大佬能不能想想办法？优化一下？

在此感谢。

**Comment by chen3861229** [comment]
请问是302之后的阿里云盘吗？它的直链有效期好像只有15分钟(看alist的issus得知，但也不绝对)

**Comment by Hiccup90** [comment]
对对对。是302之后的阿里云。
一般是win版的emby。
原来如此。懂了。
感谢大佬回复。
