### ISSUE TITLE
4.13版本infuse播放拖动进度条仍然会报错

### ISSUE THREAD

**Issue by shenxianmq** [chen3861229/embyExternalUrl#28]
如题，第一次可以成功播放，拖动进度条会发现请求的是缓存的302地址，但是仍然会播放报错，退出重进后就无法播放了
![telegram-cloud-photo-size-5-6118657642093199617-y](https://github.com/chen3861229/embyExternalUrl/assets/76782947/150c5355-3ae3-4f5d-a22b-3433608b3983)

**Comment by shenxianmq** [comment]
我刚刚测试了一下，电脑端调用第三方播放器播放没有仍然问题，在iso端的emby客户端和infuse上播放会出现相同的问题

**Comment by shenxianmq** [comment]
另外测试发现了个神奇的事情，就是emby拖动黑屏后，过十几二十分钟又突然能播放了

**Comment by chen3861229** [comment]
1.不知道是不是请求115网盘命中了strm内部为局域网ip头的情况，之前这个忘了透传UA了，如果是这个情况可以更新下代码
92fb467f44ca8b8fe406736e6bd42e349c10b57a
2.>>过十几二十分钟又突然能播放了
这个是因为njs做的重定向地址默认配置的15分钟失效，下次就是重新获取了

**Comment by chen3861229** [comment]
````
2024/04/19

1.升级分组禁用直链规则,添加NJS事件日志,重构拆分转码方法

2.经热心网友协助测试,发现拖动进度条黑屏属于emby的ios官方客户端和infuse播放115独有的问题,阿里云盘不存在此问题,
故升级了直链禁用规则,复现测试可以将115直链放到IDM等多线程下载器中,注意设置为获取直链时的UA,即使是115年费会员,
超过2个线程加载,就会导致整个下载进度卡住,时断时续,猜测这两个客户端默认使用了并发分块加载,
如果有相关设置的话(一般没有,是播放器内核自己的行为),自行设置为1,或者放开禁用直链规则

3.115还有一个问题,很久之前做文件迁移时发现的,一个账号不论多少客户端总共的下载进程最大10个,且有日传输量限制,
这个具体多少流量不清楚,复现测试为浏览器开10个任务,官方客户端下载文件夹只算一个任务,就会发现其余客户端无法播放和下载了
````
也可将直链缓存注释掉，如果发现可以正常的话，我之后提供个缓存使用规则参数
````
// check redirect link cache
  const cachedLink = ngx.shared.redirectDict.get(`${ua}:${r.uri}`);
  if (!!cachedLink) {
    r.warn(`hit redirectCache: ${cachedLink}`);
    if (cachedLink.startsWith("@")) {
      // use original link
      return internalRedirect(r, cachedLink, true);
    } else {
      return redirect(r, cachedLink, true);
    }
  }
````

**Comment by shenxianmq** [comment]
但是在3月底的那个版本是可以拉进度条的，而且不会黑屏

**Comment by chen3861229** [comment]
提供了直链缓存的开关选项
0f2a007cd52aabf1b1b173f536f08556a0fac221

能影响到的印象中只改动过PlaybackInfo和加了直链缓存，关闭直链缓存应该就是和3月的代码一样了

**Comment by shenxianmq** [comment]
[emby-nginx.zip](https://github.com/chen3861229/embyExternalUrl/files/15061087/emby-nginx.zip)
我刚刚用了这个版本，发现iso的emby端的确可以随便拉进度条，作者可以和现在的版本对比一下，看看是哪里不同导致现在的emby黑屏问题

**Comment by chen3861229** [comment]
多谢提供历史代码，已经复现出正常情况并做了修复
4c11f2589509e73324645b5c6ddf42f07a91c263

这个参数还是得加回去
````
// 指定客户端自己请求并获取alist直链的规则,代码优先级在redirectStrmLastLinkRule之后
// 特殊情况使用,则此处必须使用域名且公网畅通,用不着请保持默认
// 参数1: 0: startsWith(str), 1: endsWith(str), 2: includes(str), 3: match(/ain/g)
// 参数2: 匹配目标,对象为Alist接口返回的链接raw_url
// 参数3: 指定转发给客户端的alist的host前缀,兼容sign参数
const cilentSelfAlistRule = [
  // "Emby for iOS"和"Infuse"对于115的进度条拖动依赖于此
  // 如果nginx为https,则此alist也必须https,浏览器行为客户端会阻止非https请求
  [0, strHead["115"], alistPublicAddr],
];
````

**Comment by shenxianmq** [comment]
另外我想请教一下作者大大，我们已经配置好参数了，但是git的代码如果修改了，就又要下载下来重新改，我的问题如下：
1.有什么方法可以比较方便的去兼容git上的新更改吗？
2.能否生成一个docker镜像呢？把需要的配置单独拿出来作为一个配置文件，我们只需要填这个文件就行，其他的通过更新镜像
