### ISSUE TITLE
2024/04/13版本emby2Alist 8091套在小雅的2345端口上，不能正确解析xiaoya.host

### ISSUE THREAD

**Issue by boru626** [chen3861229/embyExternalUrl#29]
因为还要用小雅的库，所以只能把emby2Alist直连套在2345的端口上，不能播放，但是pikpak网盘获取直连没问题，看了下视频链接未能解析xiaoya.host

![微信截图_20240415143529](https://github.com/chen3861229/embyExternalUrl/assets/30763533/b37c9d5d-0ab8-4096-9159-c862a2338058)

**Comment by boru626** [comment]
回退到之前版本 刚试了下没问题

![image](https://github.com/chen3861229/embyExternalUrl/assets/30763533/1069e8f7-9803-40fd-a9f2-deba19a8ce50)

**Comment by Swiftfrog** [comment]
你自定义一下xiaoya.host的地址不就好了？

**Comment by chen3861229** [comment]
没太明白是个啥情况，不过根据描述盲猜，貌似是strm内部为远程链接
1.如果nginx所处环境可以连通2345端口，且需要客户端自己访问，如下配置
````
// 路径映射,会在xxxMountPath之后从上到下依次全部替换一遍,不要有重叠
// 参数1: 0: 默认做字符串替换, 1: 前插, 2: 尾插
// 参数2: 0: 默认只处理/开头的路径且不为strm, 1: 只处理strm内部为/开头的相对路径, 2: 只处理strm内部为远程链接的
// 参数3: 来源, 参数4: 目标
const embyPathMapping = [
  [0, 2, "https://xiaoya.host:5678", "https://xiaoya.host:2345"], 
];
````
2.如果nginx所处环境可以连通2345端口，需要njs通过alist api接口获取网盘直链，如下配置
````
// 路径映射,会在xxxMountPath之后从上到下依次全部替换一遍,不要有重叠
// 参数1: 0: 默认做字符串替换, 1: 前插, 2: 尾插
// 参数2: 0: 默认只处理/开头的路径且不为strm, 1: 只处理strm内部为/开头的相对路径, 2: 只处理strm内部为远程链接的
// 参数3: 来源, 参数4: 目标
const embyPathMapping = [
  [0, 2, "https://xiaoya.host:5678", ""], 
];
````
