### ISSUE TITLE
能否支持STRM直链？

### ISSUE THREAD

**Issue by Swiftfrog** [chen3861229/embyExternalUrl#3]
非常感谢，ALI和115都已经成功。

但是用下来直链【http://alist:port/d/xxxx.mp4】更加直观，生成strm文件的工具也更多。

奈何自己不太懂，可否修改一下，直接支持此类直链？

或者说已经支持，劳烦指点一二，再次感谢。

我测试下来：http://alist:port/d/xxxx.mp4，这类strm，只支持直接播放，不支持302，是否是我设置问题？

一下是配置：

// export constant allocation
// 必填项,根据实际情况修改下面的设置
// 这里默认emby/jellyfin的地址是宿主机,要注意iptables给容器放行端口
const embyHost = "http://192.168.xx.xx:8906";
// rclone 的挂载目录, 例如将od, gd挂载到/mnt目录下: /mnt/onedrive /mnt/gd ,那么这里就填写 /mnt
// 通常配置一个远程挂载根路径就够了,默认非此路径开头文件将转给原始emby处理,不用重复填写至disableRedirectRule
const embyMountPath = [""]; 
##我并未挂载alist路径给emby。只有留空，strm的内容为“/Ali/文件路径/xxx.mp4”才可以转发直链播放，否则就失败。
##我提前把alist挂载到系统里，davfs2的形式，不是rclone。

// emby/jellyfin api key, 在emby/jellyfin后台设置
const embyApiKey = "c696ad8xxxxx";
// 访问宿主机上5244端口的alist地址, 要注意iptables给容器放行端口
const alistAddr = "http://Alist:5244";
// alist token, 在alist后台查看
const alistToken = "alist-12345";

// 选填项,用不到保持默认即可
// alist公网地址, 用于需要alist server代理流量的情况, 按需填写
const alistPublicAddr = "http://Alist:5244";

以下是错误日志：
2024/03/21 10:01:56 [warn] 20#20: *851 js: 0ms, mount emby file path: http://alist:5244/%2FALI.R%2FB%2F6Home.Coming.2022.1080p.mp4
2024/03/21 10:01:56 [warn] 20#20: *851 js: embyPathMapping: []
2024/03/21 10:01:56 [warn] 20#20: *851 js: mapped emby file path: http://alist:5244/%2FALI.R%2FB%2F6Home.Coming.2022.1080p.mp4
2024/03/21 10:01:56 [warn] 20#20: *851 js: 1ms, fetchAlistPathApi, UA: Lavf/60.3.100
2024/03/21 10:01:56 [warn] 20#20: *851 js: alistRes: error500: alist_path_api 500 failed get storage: storage not found; rawPath: /http:/alist:5244/%2FALI.R%2FB%2F6Home.Coming.2022.1080p.mp4
2024/03/21 10:01:56 [warn] 20#20: *851 js: will req alist /api/fs/list to search
2024/03/21 10:01:56 [warn] 20#20: *851 js: try to fetch alist path from /115http://alist:5244/%2FALI.R%2FB%2F6Home.Coming.2022.1080p.mp4
2024/03/21 10:01:56 [warn] 20#20: *851 js: try to fetch alist path from /ALI.Rhttp://alist:5244/%2FALI.R%2FB%2F6Home.Coming.2022.1080p.mp4
2024/03/21 10:01:56 [warn] 20#20: *851 js: fail to fetch alist resource: not found
2024/03/21 10:01:56 [warn] 21#21: *856 js: 0ms, mount emby file path: http://alist:5244/%2FALI.R%2FB%2F6Home.Coming.2022.1080p.mp4
2024/03/21 10:01:56 [warn] 21#21: *856 js: embyPathMapping: []
2024/03/21 10:01:56 [warn] 21#21: *856 js: mapped emby file path: http://alist:5244/%2FALI.R%2FB%2F6Home.Coming.2022.1080p.mp4
2024/03/21 10:01:56 [warn] 21#21: *856 js: 1ms, fetchAlistPathApi, UA: libmpv
2024/03/21 10:01:56 [warn] 21#21: *856 js: alistRes: error500: alist_path_api 500 failed get storage: storage not found; rawPath: /http:/alist:5244/%2FALI.R%2FB%2F6Home.Coming.2022.1080p.mp4
2024/03/21 10:01:56 [warn] 21#21: *856 js: will req alist /api/fs/list to search
2024/03/21 10:01:56 [warn] 21#21: *856 js: try to fetch alist path from /115http://alist:5244/%2FALI.R%2FB%2F6Home.Coming.2022.1080p.mp4
2024/03/21 10:01:56 [warn] 21#21: *856 js: try to fetch alist path from /ALI.Rhttp://alist:5244/%2FALI.R%2FB%2F6Home.Coming.2022.1080p.mp4
2024/03/21 10:01:56 [warn] 21#21: *856 js: fail to fetch alist resource: not found

**Comment by Swiftfrog** [comment]
> 是脚本代码问题，【if (embyRes.isRemoteStrm) {】这里的判断失效了，我测试排查下

好的，非常感谢。

我也把我的配置放上来了，麻烦指点一下，谢谢。

**Comment by chen3861229** [comment]
这个不用了，我大概猜到问题了，因为之前加strm支持的时候做过兼容了，之前是可以，只是最近改的东西比较多影响到了

**Comment by Swiftfrog** [comment]
> 这个不用了，我大概猜到问题了，因为之前加strm支持的时候做过兼容了，之前是可以，只是最近改的东西比较多影响到了

谢谢。

还有另一种奇怪的情况，embyMountPath = ["/mnt"] 设置好路径。

如果播放strm文件，会输出以下错误。

2024/03/21 11:09:15 [warn] 20#20: *1 js: modify direct play info
2024/03/21 11:09:15 [warn] 20#20: *1 js: remove transcode config
2024/03/21 11:09:15 [warn] 20#20: *1 js: transfer playbackinfo: {"MediaSources":[{"Protocol":"Http","Id":"739a2cdf539b588975c55a611a5a67ab","Path":"http://alist:5244/%2FALI.R%2FB%2F6Home.Coming.2022.1080p.mp4","Type":"Default","Container":"strm","Size":0,"Name":"10","IsRemote":true,"SupportsTranscoding":false,"SupportsDirectStream":true,"SupportsDirectPlay":true,"IsInfiniteStream":false,"RequiresOpening":false,"RequiresClosing":false,"RequiresLooping":false,"SupportsProbing":false,"MediaStreams":[],"Formats":[],"RequiredHttpHeaders":{},"DirectStreamUrl":"/videos/1617014/stream/10.strm?UserId=40a02f8503ce4de49d58331a282dcea1&reqformat=json&StartTimeTicks=0&IsPlayback=true&AutoOpenLiveStream=true&MaxStreamingBitrate=500000000&api_key=c696ad8d4c5c458a914f1e56d36d61f2&MediaSourceId=739a2cdf539b588975c55a611a5a67ab&Static=true&filePath=http://alist:5244/%252FALI.R%252FB%252F6Home.Coming.2022.1080p.mp4&protocol=Http","ReadAtNativeFramerate":false,"OriginDirectStreamUrl":"/videos/1617014/original.strm?DeviceId=DAD19A2F-040D-4F34-9676-4D3D3EFA1C38&MediaSourceId=739a2cdf539b588975c55a611a5a67ab&PlaySessionId=3a93a1d684854ee798f87ec422ad47cd&api_key=8023b04066eb4c308d9e5bc11099d3c4"}],"PlaySessionId":"3a93a1d684854ee798f87ec422ad47cd"}
2024/03/21 11:09:15 [warn] 23#23: *10 js: 0ms, mount emby file path: http://alist:5244/%2FALI.R%2FB%2F6Home.Coming.2022.1080p.mp4
2024/03/21 11:09:15 [warn] 23#23: *10 js: embyRes hit isDisableRedirect
2024/03/21 11:09:15 [warn] 23#23: *10 js: use original link
2024/03/21 11:09:16 [warn] 20#20: *12 js: 0ms, mount emby file path: http://alist:5244/%2FALI.R%2FB%2F6Home.Coming.2022.1080p.mp4
2024/03/21 11:09:16 [warn] 20#20: *12 js: embyRes hit isDisableRedirect
2024/03/21 11:09:16 [warn] 20#20: *12 js: use original link

**Comment by chen3861229** [comment]
等下，你的配置好像十分特殊，需要看下这个参数配置disableRedirectRule

**Comment by Swiftfrog** [comment]
我概述一下我的思路：emby直接播放strm文件（http://alist:port/d/xxx.mp4），封面和info存放本地。

故想要做到strm文件可以转直链接。

目前的情况是这样的，strm文件：/alist/xx/xxx.mp4，能转自链接。http://alist:port/d/xxx.mp4报错。

disableRedirectRule 未设置。

**Comment by Swiftfrog** [comment]
// export constant allocation
// 必填项,根据实际情况修改下面的设置
// 这里默认emby/jellyfin的地址是宿主机,要注意iptables给容器放行端口
const embyHost = "http://192.168.xx.xx:9608";
// rclone 的挂载目录, 例如将od, gd挂载到/mnt目录下: /mnt/onedrive /mnt/gd ,那么这里就填写 /mnt
// 通常配置一个远程挂载根路径就够了,默认非此路径开头文件将转给原始emby处理,不用重复填写至disableRedirectRule
const embyMountPath = ["/home/albert/mnt"];
// emby/jellyfin api key, 在emby/jellyfin后台设置
const embyApiKey = "c696a914f1e56d36d61f2";
// 访问宿主机上5244端口的alist地址, 要注意iptables给容器放行端口
const alistAddr = "http://192.168.xx.xx:5244";
// alist token, 在alist后台查看
const alistToken = "alist-12345";

// 选填项,用不到保持默认即可
// alist公网地址, 用于需要alist server代理流量的情况, 按需填写
const alistPublicAddr = "http://alist:5244";
// 指定客户端自己请求并获取alist直链的规则,特殊情况使用,则此处必须使用域名且公网畅通,用不着请保持默认
// arg0: 0: startsWith(str), 1: endsWith(str), 2: includes(str), 3: match(/ain/g)
// arg1: 匹配的规则,对象为Alist接口返回的直链
// arg2: 指定转发给客户端的alist的host前缀
const cilentSelfAlistRule = [
  // [2, "xxx", alistPublicAddr],
];
// 多个可以给emby记录的strm文件内链接做映射,会在embyMountPath之后全部替换一遍,不要有重叠
// strm文件提醒,填写规则参考emby官方文档,强烈建议strm文件内部只填路径,重定向后的远程链接将被部分浏览器跨域限制
const embyPathMapping = [
  //  "/home/albert/mnt"
  // ["/mnt/aliyun-01", "/mnt/aliyun-02"],
  // ["http:", "https:"], 
  // [":5244", "/alist"], 
  // ["D:", "F:"],
  // [/blue/g, "red"],
];
// 禁用直链的规则,将转给原始emby处理,字幕和图片没有走直链,不用添加
// arg0: 0: startsWith(str), 1: endsWith(str), 2: includes(str), 3: match(/ain/g)
// arg1: 匹配的规则,对象为Item.Path
// arg2: 是否处理alist响应链接
const disableRedirectRule = [
  // [0, "/mnt/sda1"],
  // [1, ".mp3"],
  // [2, "Google"],
  // [2, "/NAS/", true],
  // [3, /private/ig],
];
// !!!实验功能,转码分流,默认false,将按之前逻辑禁止转码处理并移除转码选项参数,与emby配置无关
// 使用条件很苛刻,主库和所有从库给用户开启[播放-如有必要，在媒体播放期间允许视频转码]+[倒数7行-允许媒体转换]
// 转码服务组中的媒体id需要和主媒体库中id一致,自行寻找实现主从同步,完全同步后,embyApiKey也是一致的
const transcodeBalanceConfig = {
  enable: false,
  // method: "least_conn",
  server: [
    {
      host: "http://172.17.0.1:8096",
      apiKey: "f839390f50a648fd92108bc11ca6730a",
      weight: 1
    },
    {
      host: "http://172.17.0.2:8096",
      apiKey: "f839390f50a648fd92108bc11ca6730a",
      weight: 2
    }
  ]
};

**Comment by Swiftfrog** [comment]
> // export constant allocation // 必填项,根据实际情况修改下面的设置 // 这里默认emby/jellyfin的地址是宿主机,要注意iptables给容器放行端口 const embyHost = "http://192.168.xx.xx:9608"; // rclone 的挂载目录, 例如将od, gd挂载到/mnt目录下: /mnt/onedrive /mnt/gd ,那么这里就填写 /mnt // 通常配置一个远程挂载根路径就够了,默认非此路径开头文件将转给原始emby处理,不用重复填写至disableRedirectRule const embyMountPath = ["/home/albert/mnt"]; // emby/jellyfin api key, 在emby/jellyfin后台设置 const embyApiKey = "c696a914f1e56d36d61f2"; // 访问宿主机上5244端口的alist地址, 要注意iptables给容器放行端口 const alistAddr = "http://192.168.xx.xx:5244"; // alist token, 在alist后台查看 const alistToken = "alist-12345";
> 
> // 选填项,用不到保持默认即可 // alist公网地址, 用于需要alist server代理流量的情况, 按需填写 const alistPublicAddr = "http://alist:5244"; // 指定客户端自己请求并获取alist直链的规则,特殊情况使用,则此处必须使用域名且公网畅通,用不着请保持默认 // arg0: 0: startsWith(str), 1: endsWith(str), 2: includes(str), 3: match(/ain/g) // arg1: 匹配的规则,对象为Alist接口返回的直链 // arg2: 指定转发给客户端的alist的host前缀 const cilentSelfAlistRule = [ // [2, "xxx", alistPublicAddr], ]; // 多个可以给emby记录的strm文件内链接做映射,会在embyMountPath之后全部替换一遍,不要有重叠 // strm文件提醒,填写规则参考emby官方文档,强烈建议strm文件内部只填路径,重定向后的远程链接将被部分浏览器跨域限制 const embyPathMapping = [ // "/home/albert/mnt" // ["/mnt/aliyun-01", "/mnt/aliyun-02"], // ["http:", "https:"], // [":5244", "/alist"], // ["D:", "F:"], // [/blue/g, "red"], ]; // 禁用直链的规则,将转给原始emby处理,字幕和图片没有走直链,不用添加 // arg0: 0: startsWith(str), 1: endsWith(str), 2: includes(str), 3: match(/ain/g) // arg1: 匹配的规则,对象为Item.Path // arg2: 是否处理alist响应链接 const disableRedirectRule = [ // [0, "/mnt/sda1"], // [1, ".mp3"], // [2, "Google"], // [2, "/NAS/", true], // [3, /private/ig], ]; // !!!实验功能,转码分流,默认false,将按之前逻辑禁止转码处理并移除转码选项参数,与emby配置无关 // 使用条件很苛刻,主库和所有从库给用户开启[播放-如有必要，在媒体播放期间允许视频转码]+[倒数7行-允许媒体转换] // 转码服务组中的媒体id需要和主媒体库中id一致,自行寻找实现主从同步,完全同步后,embyApiKey也是一致的 const transcodeBalanceConfig = { enable: false, // method: "least_conn", server: [ { host: "http://172.17.0.1:8096", apiKey: "f839390f50a648fd92108bc11ca6730a", weight: 1 }, { host: "http://172.17.0.2:8096", apiKey: "f839390f50a648fd92108bc11ca6730a", weight: 2 } ] };

这样的话，strm: http://alist:port/alist/xxx.mp4，播放就是original link，接着报错。


如果embyMountPath=“”为空，就是alistRes: error500: alist_path_api 500 failed get storage

**Comment by chen3861229** [comment]
嗯，定位到问题了，稍等我修复下

**Comment by Swiftfrog** [comment]
非常感谢，可能我的思路比较奇怪。

**Comment by chen3861229** [comment]
不奇怪，我代码问题，已做修复

**Comment by Swiftfrog** [comment]
你好，今天早上抽空测试了一下，问题依旧。

配置如下（加粗就是配置了，否则就是默认。）：
// export constant allocation
// 必填项,根据实际情况修改下面的设置
// 这里默认emby/jellyfin的地址是宿主机,要注意iptables给容器放行端口
**const embyHost = "http://192.168.xx.xx:8096";**
// rclone 的挂载目录, 例如将od, gd挂载到/mnt目录下: /mnt/onedrive /mnt/gd ,那么这里就填写 /mnt
// 通常配置一个远程挂载根路径就够了,默认非此路径开头文件将转给原始emby处理,不用重复填写至disableRedirectRule
**const embyMountPath = ["/home/albert/mnt"];**
// emby/jellyfin api key, 在emby/jellyfin后台设置
const embyApiKey = "c696xxxxxxx";
// 访问宿主机上5244端口的alist地址, 要注意iptables给容器放行端口
**const alistAddr = "http://192.168.xx.xx:5244";**
// alist token, 在alist后台查看
const alistToken = "alist-8xxxxxx";

// 选填项,用不到保持默认即可
// alist公网地址, 用于需要alist server代理流量的情况, 按需填写
**const alistPublicAddr = "http://xxx.xxx.xxx:5244";**
// 指定客户端自己请求并获取alist直链的规则,特殊情况使用,则此处必须使用域名且公网畅通,用不着请保持默认
// arg0: 0: startsWith(str), 1: endsWith(str), 2: includes(str), 3: match(/ain/g)
// arg1: 匹配的规则,对象为Alist接口返回的直链
// arg2: 指定转发给客户端的alist的host前缀
const cilentSelfAlistRule = [
  // [2, "xxx", alistPublicAddr],
];
// 多个可以给emby记录的strm文件内链接做映射,会在embyMountPath之后全部替换一遍,不要有重叠
// strm文件提醒,填写规则参考emby官方文档,强烈建议strm文件内部只填路径,重定向后的远程链接将被部分浏览器跨域限制
const embyPathMapping = [
  // ["/mnt/aliyun-01", "/mnt/aliyun-02"],
  // ["http:", "https:"], 
  // [":5244", "/alist"], 
  // ["D:", "F:"],
  // [/blue/g, "red"],
];
// 禁用直链的规则,将转给原始emby处理,字幕和图片没有走直链,不用添加
// arg0: 0: startsWith(str), 1: endsWith(str), 2: includes(str), 3: match(/ain/g)
// arg1: 匹配的规则,对象为Item.Path
// arg2: 是否处理alist响应链接
const disableRedirectRule = [
  // [0, "/mnt/sda1"],
  // [1, ".mp3"],
  // [2, "Google"],
  // [2, "/NAS/", true],
  // [3, /private/ig],
];
// !!!实验功能,转码分流,默认false,将按之前逻辑禁止转码处理并移除转码选项参数,与emby配置无关
// 使用条件很苛刻,主库和所有从库给用户开启[播放-如有必要，在媒体播放期间允许视频转码]+[倒数7行-允许媒体转换]
// 转码服务组中的媒体id需要和主媒体库中id一致,自行寻找实现主从同步,完全同步后,embyApiKey也是一致的
const transcodeBalanceConfig = {
  enable: false,
--------------------

当const embyMountPath = ["/home/albert/mnt"];是绝对路径时，播放strm:https://xxx.xxx.xx.xx:port/d/xxx.mp4,日志如下：
2024/03/22 01:43:45 [warn] 20#20: *105 js: 0ms, mount emby file path: http://alist:5244/d/%2FALI.R%2FB%2F6Home.Coming.2022.1080p.mp4
2024/03/22 01:43:45 [warn] 20#20: *105 js: embyRes hit isDisableRedirect
2024/03/22 01:43:45 [warn] 20#20: *105 js: use original link
2024/03/22 01:43:45 [warn] 20#20: *107 js: 0ms, mount emby file path: http://alist:5244/d/%2FALI.R%2FB%2F6Home.Coming.2022.1080p.mp4
2024/03/22 01:43:45 [warn] 20#20: *107 js: embyRes hit isDisableRedirect
2024/03/22 01:43:45 [warn] 20#20: *107 js: use original link

似乎是绝对路径有挂载，然后用原链接本地播放，但是失败。
-----------------------------
当const embyMountPath = [""]，为空时，播放strm:https://xxx.xxx.xx.xx:port/d/xxx.mp4, 日志如下：

2024/03/22 01:52:52 [warn] 21#21: *4 js: 0ms, mount emby file path: http://alist:5244/d/%2FALI.R%2FB%2F6Home.Coming.2022.1080p.mp4
2024/03/22 01:52:52 [warn] 21#21: *4 js: embyPathMapping: []
2024/03/22 01:52:52 [warn] 21#21: *4 js: mapped emby file path: http://alist:5244/d/%2FALI.R%2FB%2F6Home.Coming.2022.1080p.mp4
2024/03/22 01:52:52 [warn] 21#21: *4 js: !!!warnning remote strm file protocol: Http
2024/03/22 01:52:52 [warn] 21#21: *4 js: redirect to: http://alist:5244/d/%2FALI.R%2FB%2F6Home.Coming.2022.1080p.mp4
2024/03/22 01:52:52 [warn] 22#22: *5 js: 0ms, mount emby file path: http://alist:5244/d/%2FALI.R%2FB%2F6Home.Coming.2022.1080p.mp4
2024/03/22 01:52:52 [warn] 22#22: *5 js: embyPathMapping: []
2024/03/22 01:52:52 [warn] 22#22: *5 js: mapped emby file path: http://alist:5244/d/%2FALI.R%2FB%2F6Home.Coming.2022.1080p.mp4
2024/03/22 01:52:52 [warn] 22#22: *5 js: !!!warnning remote strm file protocol: Http
2024/03/22 01:52:52 [warn] 22#22: *5 js: redirect to: http://alist:5244/d/%2FALI.R%2FB%2F6Home.Coming.2022.1080p.mp4

没有转到直链，失败。

播放**stream:/ali/xx/xxx.mp4,** 成功，日志如下：
2024/03/22 01:56:32 [warn] 20#20: *18 js: 0ms, mount emby file path: /ALI.R/B/6Home.Coming.2022.1080p.mp4
2024/03/22 01:56:32 [warn] 20#20: *18 js: embyPathMapping: []
2024/03/22 01:56:32 [warn] 20#20: *18 js: mapped emby file path: /ALI.R/B/6Home.Coming.2022.1080p.mp4
2024/03/22 01:56:32 [warn] 20#20: *18 js: 1ms, fetchAlistPathApi, UA: libmpv
2024/03/22 01:56:32 [warn] 20#20: *18 js: redirect to: https://cn-beijing-data.aliyundrive.net/CdFRbi2E%2F77318683%2F639be3c351448e25e2464b3eba40cddc566593a2%2F639be3c320843c556d6b4ea6b27ba4c02174b7e2?callback=eyJjYWxsYmFja1VybCI6Imh0dHA6Ly9iajI5LmFwaS1ocC5hbGl5dW5wZHMuY29tL3YyL2ZpbGUvZG93bmxvYWRfY2FsbGJhY2siLCJjYWxsYmFja0JvZHkiOiJodHRwSGVhZGVyLnJhbmdlPSR7aHR0cEhlYWRlci5yYW5nZX1cdTAwMjZidWNrZXQ9JHtidWNrZXR9XHUwMDI2b2JqZWN0PSR7b2JqZWN0fVx1MDAyNmRvbWFpbl9pZD0ke3g6ZG9tYWluX2lkfVx1MDAyNnVzZXJfaWQ9JHt4OnVzZXJfaWR9XHUwMDI2ZHJpdmVfaWQ9JHt4OmRyaXZlX2lkfVx1MDAyNmZpbGVfaWQ9JHt4OmZpbGVfaWR9XHUwMDI2cGRzX3BhcmFtcz0ke3g6cGRzX3BhcmFtc30iLCJjYWxsYmFja0JvZHlUeXBlIjoiYXBwbGljYXRpb24veC13d3ctZm9ybS11cmxlbmNvZGVkIiwiY2FsbGJhY2tTdGFnZSI6ImJlZm9yZS1leGVjdXRlIiwiY2FsbGJhY2tGYWlsdXJlQWN0aW9uIjoiaWdub3JlIn0%3D&callback-var=eyJ4OmRvbWFpbl9pZCI6ImJqMjkiLCJ4OnVzZXJfaWQiOiJiMmU4ZGE4ZjJiMWY0Y2NhODNjZTVhNWM5NTE3ZmM4NSIsIng6ZHJpdmVfaWQiOiI5MDA4ODk1ODIiLCJ4OmZpbGVfaWQiOiI2NWRjODM0ZjAyMDhmN2Q2OThmODQxOGRiZDU2M2ZkOTE1MjM2OWFjIiwieDpwZHNfcGFyYW1zIjoie1wiYXBcIjpcIjc2OTE3Y2NjY2Q0NDQxYzM5NDU3YTA0ZjYwODRmYjJmXCJ9In0%3D&di=bj29&dr=900889582&f=65dc834f0208f7d698f8418dbd563fd9152369ac&pds-params=%7B%22ap%22%3A%2276917ccccd4441c39457a04f6084fb2f%22%7D&response-content-disposition=attachment%3B%20filename%2A%3DUTF

麻烦有时间抽空看看，多谢了。

**Comment by Swiftfrog** [comment]
搞定了，谢谢。

之前有个签名的问题，现在解决了，再次感谢。
