### ISSUE TITLE
转码问题

### ISSUE THREAD

**Issue by Swiftfrog** [chen3861229/embyExternalUrl#30]
你好。

更新到最新版后，转码播放开启，日志如下：
2024/04/18 16:59:35 [warn] 21#21: *3 js: 2ms, fetchEmbyFilePath async function cost
2024/04/18 16:59:35 [warn] 21#21: *3 js: itemName: 01, originalFilePath: /media/test/01.mp4
2024/04/18 16:59:36 [warn] 20#20: *19 js: syncPlayState transcodeDict key: 2ee68a4f670240aba15280d44c8c672c
2024/04/18 16:59:36 [warn] 20#20: *19 js: syncPlayState playSession not exist, skip, /emby/Sessions/Playing
2024/04/18 16:59:36 [warn] 20#20: *19 js: syncPlayState transcodeDict key: 2ee68a4f670240aba15280d44c8c672c
2024/04/18 16:59:36 [warn] 20#20: *19 js: syncPlayState playSession not exist, skip, /emby/Sessions/Playing/Progress
2024/04/18 16:59:46 [warn] 20#20: *19 js: syncPlayState transcodeDict key: 2ee68a4f670240aba15280d44c8c672c
2024/04/18 16:59:46 [warn] 20#20: *19 js: syncPlayState playSession not exist, skip, /emby/Sessions/Playing/Progress
2024/04/18 16:59:52 [warn] 20#20: *19 js: syncPlayState transcodeDict key: 2ee68a4f670240aba15280d44c8c672c
2024/04/18 16:59:52 [warn] 20#20: *19 js: syncPlayState playSession not exist, skip, /emby/Sessions/Playing/Stopped

不停地跳key和Stopped.

麻烦看一下。

设置如下：

const transcodeBalanceConfig = {
  enable: true

其他选项都注释掉了。

**Comment by Swiftfrog** [comment]
补充说明，不是302的转码，是本地文件的转码。

**Comment by chen3861229** [comment]
1.这个transcodeBalanceConfig 中有配置客户端公网可访问server组吗？虽然内部代码做了判断，找不到就会转给当前访问的原始服务处理
>不停地跳key和Stopped
2.这个是正常的，同步当前进度和操作到目标服务使用打印出来的

**Comment by Swiftfrog** [comment]
谢谢解释，好的，理解了。

我没有配置公网可访问的。我是strm和本地文件混合，没有配置远程挂载。

解码日志是正常的，明白了。
