### ISSUE TITLE
使用jellyfin pc客户端连接emby服务端 无法播放。

### ISSUE THREAD

**Issue by Hiccup90** [chen3861229/embyExternalUrl#31]
看了下文档，好像是23年的更新有提到过，兼容jellyfin和TerminusPlayer 不知道是不是指pc客户端

不过我两个都试了下，都无法播放。

这是用emby客户端可以播放的   
<img width="405" alt="emby" src="https://github.com/chen3861229/embyExternalUrl/assets/24733459/57764093-80f8-4efb-9da0-802c32e44764">
下面是用jf客户端的日志。无法播放  
<img width="320" alt="jf" src="https://github.com/chen3861229/embyExternalUrl/assets/24733459/6e3039e2-31ba-4dd8-ae3f-759485414de9">

不知道是不是跟这个有关。

**Comment by chen3861229** [comment]
1.不支持这样操作的，兼容jellyfin指的是该脚本可以为其工作，并不能跨客户端类型访问
2.这个操作去年构思实践过，虽然emby/jellyfin很多接口相同，但是还是有很多区别，只过了验证服务版本号这关，账号登录这块一个是get一个是post，然后就觉得这样兼容客户端互相访问工作量太大了，就放弃了

**Comment by Hiccup90** [comment]
哈哈哈。好的。知道原因就行了。感谢作者回复。
