### ISSUE TITLE
关于emby2alist配置遇到的问题

### ISSUE THREAD

**Issue by Akimio521** [chen3861229/embyExternalUrl#32]
最近想要配置jellyfin的strm文件直链功能，但是似乎并没有完整的配置教程，我并不了解njs，下面是我的几个问题，希望可以解答一下
1. nginx需要使用host网络，因为这样才能获取到客户端的真实ip：请问其他容器需要使用host网络吗，目前我容器的是使用docker 网桥，通过容器名相连接，只有nginx-proxy- manager在宿主机上映射的端口，目前是宿主机的666端口指向npm的443端口，npm反代jellyfin的地址就填了http://jellyfin:8096，jellyfin本身并没有把端口映射到宿主机，如果需要用到emby2alist这个项目我的访问应该是npm->emby2alist->jellyfin，这样我所有的容器都需要使用host网络吗，还是说把jellyfin的8096映射到宿主机后，只需要emby2alist是host，然后emby2alist反代宿主机的网络，最后再用npm反代emby2alist
2. 然后就是不太懂为什么需要识别内网网段的地址，不太理解有什么用
3. 就是关于alist，目前我有xiaoya和自己两个alist，应该怎么配置，xiaoya的似乎不允许被添加到其他的alist
4. 关于路由配置的，这里没太明白怎么配置，我的需求就是strm文件可以直链播放，本地的视频文件可以硬件解码，并且可以同一个端口实现
5. strm文件的内容应该填写容器可以访问到的地址还是局域网可以访问到的地址还是公网可以访问到的地址
6. strm视频是使用内封字母比较好还是外挂字幕，我看readme之前说内封字母会让服务器获取完整的视频文件，那么这样是不是就失去了直链播放的意义，还使得服务端失去硬解的能力，但外挂字幕说是直接无法推送到客户端

总的来说，我的需求有下面几点
- 主要是想strm文件能直链，本地视频可以硬解，最好能一个端口实现（或者一个端口可以直链，并且本地视频可以正常推送，另一个端口无论strm还是本地视频都能硬解转码推送给客户端）
- 然后就是有两个alist，一个是我自己挂在onedrive的，另一个是xiaoya
- 宿主机上暴露的端口经可能少（主要通过npm配置了ssl证书访问）

我的网络环境目前是ipv6的地址ddns到主路由上，通过socat放行主路由的端口，转发到npm映射到宿主机的端口上（至于为什么不直接在nas的宿主机上做ddns，主要是不知道怎么放行防火墙规则，动态v6地址一直在变，换一次防火墙的规则又要重新设置一次）然后nas上有frp，也是将流量转发给npm，这样就实现了v4v6环境下都能访问，并且局域网内访问时速度也不影响（只是数据先要到主理由绕一圈）

**Comment by chen3861229** [comment]
1.这个其实不是必要条件，但是因为 nginx 之前可能还有其他反代程序而没有传递客户端真实 IP 标头，所以用 host 比较简单，能保证本 nginx=> jellyfin 传递的是客户端的真实远程 IP ,在 nginx 后如果直接就是原始媒体服务，emby 就不需要 host 网络了,但是如果 nginx 前后还有其他的反代程序，则它们都需要传递客户端真实 IP, 所需标头可以参考 proxy.conf 或 alist 文档中反代传递的标头，根据你的流量链路 npm->emby2alist->jellyfin 只需要在 npm 这里传递标头就行了，这样 nginx 和 jellyfin 都可以用桥接网络不用改，
这个配置同时也是给问题 2 做内网外识别用的，如果用不到或者不在意 jellyfin 控制台中和 nginx 日志中的显示的客户端 IP 都是内网而不是真实远程 IP 的，也不用管这个配置了
2.这个如果没有特殊需要可以不用管的，选填项，目前两个地方用到了
2.1 有用户反馈内网环境走直链 infuse 反而会更卡
````
const routeRule = [
   // docker注意必须为host模式,不然此变量全部为内网ip,判断无效,nginx内置变量不带$,客户端地址($remote_addr)
  // ["r.variables.remote_addr", 0, strHead.lanIp],
];
````
2.2 如果 strm 内部的远程链接为局域网的，转发给远程客户端访问不了，所以做了内网的条件判断在 nginx 内网这层去获取 strm 内网链接 302 后的公网直链返回给远程客户端
````
const redirectStrmLastLinkRule = [
  [0, strHead.lanIp.map(s => "http://" + s)]
];
````
3.之前尝试过但是资源有效性不太理想，所以都是自己整理资源了，目前这个就不清楚了，我看小雅官方文档是要 docker 自己部署的，里边有提到无法套娃挂载的问题，当然好像也有人用工具转 strm 来播放，这个就需要自己摸索了
4.直链播放是默认的路由规则，不用配置，有转码需求的如下设置，默认情况都是基于 ngixn 监听的同一端口的，原始媒体服务那个端口仅作为特殊情况下无法使用时客户端手动连接过去用原服务，就和本项目无关了
````
const routeRule = [
  ["transcode", "filePath", 0, "/mnt/sda3"], // 允许转码的文件路径开头
];
const transcodeConfig = {
  enable: true, // 允许转码功能的总开关
  type: "distributed-media-server", // 负载类型，只有这个实现了路由规则
 redirectTransOptEnable: false, // 302的直链文件是否保留码率选择
};
````
5.效率最高的还是填远程客户端可以访问的公网地址，这样代码里几乎没做费时的处理，但是如果需要 2.2 的处理，就必须保证 nginx 容器和 strm 内部的链接是可访问的，普通情况下等同于局域网下，只要不是极端情况，例如 nginx 配置了 none 类型网络，通过 link 和其他容器网络连接，这样就不是局域网了，而且问题估计也比较多，我没这样测试过
6.这个是按客户端的播放形式分的，如果像我一样用官方修改版客户端还调用了外部的第三方播放器，这样就是没法传递外挂字幕的地址了，所以播放内封字幕的更好，如果没有调用外部的第三方播放器，官方客户端和第三方客户端都是支持外挂字幕的加载的，
内封字幕在第三方播放器都是直接播放没有任何影响，内封字幕问题只在官方客户端上存在的，因为它要兼容的设备比较多，只是扫一个字幕流编码的提取而已，性能占用可以忽略不记，只占视频文件的 4 成左右，流量也还能接受，这个提取内封字幕的功能我印象中转码设置里可以关闭的，但我这边还是保持默认的开，没有测试过关闭的影响，和服务端硬解能力是无关的，总的来说还是内封字幕比较省心
7.不建议对 strm 文件进行转码哦，jellyfin 对它的支持也不知道是不是有bug，我这边会导致 playbackinfo 这个接口长达 30 秒，也就是进详情页也会调用这个接口查询，再加上还要走一遍服务转码的文件分块读取(下载)过程，如果转码的响应时间超过了 10 秒客户端就会主动断开请求，断开后转码进度就清空重置了，然后客户端会重试转码，循环失败次数过多就直接报没有兼容的流了，需要保证网络带宽和转码硬件的能力都跟上才能有个好的体验，使用条件太苛刻了

**Comment by Akimio521** [comment]
感谢解答，我去尝试配置一下

**Comment by arthurxj** [comment]
> 感谢解答，我去尝试配置一下

小雅套娃这样用。添加"存储"时选v3。
获取alist_auth_token（把令牌填到“令牌”，“链接”选用本地的docker 域名或IP地址，用户名、密码留空）
docker exec -i xiaoya sqlite3 data/data.db <<EOF
select value from x_setting_items where key = "token";
EOF
https://xiaoyaliu.notion.site/xiaoya-docker-69404af849504fa5bcf9f2dd5ecaa75f

顺便我想请教一下，我感觉有了目前讨论的这个项目，使用strm好像没更多便利，是不是我还没有发掘出strm的实用性。

**Comment by Akimio521** [comment]
> > 感谢解答，我去尝试配置一下
> 
> 小雅套娃这样用。添加"存储"时选v3。 获取alist_auth_token（把令牌填到“令牌”，“链接”选用本地的docker 域名或IP地址，用户名、密码留空） docker exec -i xiaoya sqlite3 data/data.db <<EOF select value from x_setting_items where key = "token"; EOF https://xiaoyaliu.notion.site/xiaoya-docker-69404af849504fa5bcf9f2dd5ecaa75f
> 
> 顺便我想请教一下，我感觉有了目前讨论的这个项目，使用strm好像没更多便利，是不是我还没有发掘出strm的实用性。

主要用于扩充一下自己的影视库吧，主力还是本地视频，另一方面就是看高码率视频，可以strm直接访问到源文件，流量不经过NAS，也就不用担心NAS的带宽问题了

**Comment by chen3861229** [comment]
strm 主要优点是不扫库，库内容太多了，做迁移或者恢复，如果文件夹或者媒体的最后更新时间变化了，我 115 扫了快一个多月了，缺点是第一次播放的时候会稍微慢一点，同时 emby 去补充入库媒体编码信息，然后就是可能稍微灵活一点吧，毕竟内部只有一个文件网址链接，当然软连接好像也能实现相同效果，这个需要自己对比选择了
去年加 strm 的支持只是想到个骚操作，emby 服务端是有安卓版的，想到可以用旧手机或者旧盒子搭，然后当时 cd2 还没出安卓版，所以尝试了下，不过发现用处还是不大

**Comment by Akimio521** [comment]
> strm 主要优点是不扫库，库内容太多了，做迁移或者恢复，如果文件夹或者媒体的最后更新时间变化了，我 115 扫了快一个多月了，缺点是第一次播放的时候会稍微慢一点，同时 emby 去补充入库媒体编码信息，然后就是可能稍微灵活一点吧，毕竟内部只有一个文件网址链接，当然软连接好像也能实现相同效果，这个需要自己对比选择了
> 
> 去年加 strm 的支持只是想到个骚操作，emby 服务端是有安卓版的，想到可以用旧手机或者旧盒子搭，然后当时 cd2 还没出安卓版，所以尝试了下，不过发现我这种需求还是不大

不算不扫库吧，准确来说应该是已经扫过一遍了，我一般是用我的脚本生成xiaoya的strm，然后用挂销软件再挂销一遍，这样能确保命名规范符合自己的媒体，看着也省心悦目一点

**Comment by Akimio521** [comment]
strm 还有一个优点就是如果你的设备不方便做硬链接，又想保重，又不想额外浪费空间把文件复制一份，就可以用 strm
如果是用 cd2 把视频从网盘挂载到本地路径，strm 就像是 pr 里面的代理文件，用 strm 进行刮削分类既可以不改变网盘中的文件结构，也不会出现封号的风险

**Comment by chen3861229** [comment]
嗯，是后续不扫库了，只要 strm 的最后修改时间不变，原始媒体文件的修改时间和路径可以任意改变，strm 优点是和磁盘文件系统分离开了，不受限制，例如我有强迫症，原始字幕组的规范文件名我不想改动，然而 emby 中我却需要中文的简洁命名，目前用的硬链接不能跨硬盘，软连接倒是可以跨盘，但是我 NAS 硬盘炸过，目前全部存网盘但是占用两份空间，当时也是考虑到全部切换到 strm 可以让我网盘省出 60T 空间来，不过有些懒没找到时间切换，阿里还能用，先凑合到下月再看情况

**Comment by arthurxj** [comment]
> strm 主要优点是不扫库，库内容太多了，做迁移或者恢复，如果文件夹或者媒体的最后更新时间变化了，我 115 扫了快一个多月了，缺点是第一次播放的时候会稍微慢一点，同时 emby 去补充入库媒体编码信息，然后就是可能稍微灵活一点吧，毕竟内部只有一个文件网址链接，当然软连接好像也能实现相同效果，这个需要自己对比选择了 去年加 strm 的支持只是想到个骚操作，emby 服务端是有安卓版的，想到可以用旧手机或者旧盒子搭，然后当时 cd2 还没出安卓版，所以尝试了下，不过发现我这种需求还是不大

我试过用Emby安卓服务端与strm结合，结论是可用，但是WiFi加转码结果不是很理想，毕竟现在影片体积都很大。还是这种直链效果最佳，算是目前的终极解决方案。
另外，Emby的识别率比较差，作为个人整理海量影片资源是不可取的行为，只有plex值得一试。
strm我能想到的一个实用途径，可能是把小雅的资源转化为自己影视库的一部分，但是好像行不通。
strm的另一个实用途径，或许可以用于整理影视库，避开网盘厂家对文件频繁大量扫描的封锁。但是需要有nfo和图片回传的功能（反正整理媒体库还是一个自寻烦恼的过程）。

目前使用这个直链项目基本解决了个人影视库的搭建需要，只是投屏还没有一个好的解决办法（与本项目无关），如果是苹果客户端，可以用镜像投屏，基本是90%的一次性成功率，plex直接投屏不太灵。安卓客户端没有找到好的办法。

**Comment by Akimio521** [comment]
不建议把info，img 图片等数据放在网盘，只要 strm命名符合规范，大多数挂销软件都能识别，info，img 等文件放本地就好，毕竟数据量也不大
