### ISSUE TITLE
整合embyAddExternalUrl支持emby全客户端

### ISSUE THREAD

**Issue by sjtuross** [chen3861229/embyExternalUrl#33]
现在那个embyWebAddExternalUrl只能通过网页访问emby，然后调用外部播放器

我尝试整合embyAddExternalUrl到302的nginx中不起作用，估计不适配现在的emby或njs的反代代码了

就是想利用那排链接，直接在app里面调用外部播放器，不知大佬是否有兴趣看一下？

**Comment by chen3861229** [comment]
平时我的测试容器中注释掉这个了，不过刚测试了下，是可以共存的，因为示例配置可能是原作者考虑到有人单独只用其中一个，所以是独立的 nginx 配置，需要自己复制下 emby.conf 中的内容组合一下了,和配置顺序关系不大，不过为了兼容之后的内容，还是建议放在 location / 的上边，以下放了两个 emby 302 的 conf 配置定位，只需要 ## addExternalUrl SETTINGS ## 中的
````
  ## Disables access to swagger/openapi interface
    location ~* /(swagger|openapi) {
        return 404;
    }

   ## addExternalUrl SETTINGS ##
    location ~* /Users/(.*)/Items/(\d+)$ {
        proxy_buffering off;
        js_body_filter  addExternalUrl.addExternalUrl buffer_type=string;
        proxy_pass $emby;
        proxy_pass_request_body off;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Accept-Encoding "identity";
        proxy_set_header X-Original-URI $request_uri;
        js_header_filter addExternalUrl.HeaderFilter;
    }

    location ~* /redirect2external {
        js_content addExternalUrl.redirectUrl;
    }
    ## addExternalUrl SETTINGS ##
    
    location / {
        # Proxy main emby/jellyfin traffic
        proxy_pass $emby;
    }
````

**Comment by sjtuross** [comment]
感谢指导！可以用了。有2个小问题：

1. 剧集季的页面上不显示，得进入到某一集才显示
2. 没有mpv链接，这个我主要是在win上用，DV片源颜色映射正常

**Comment by chen3861229** [comment]
1.因为受限于原本这个外置媒体数据库的展示就只在单集的详情里，所以只有加在这里有效
2.MPV是之前的合作者加的，之后我粘贴下吧

**Comment by sjtuross** [comment]
补充一下，因为web端可以在季页面显示那些外部播放按钮，因此询问一下。

**Comment by chen3861229** [comment]
同步代码添加了 MPV
77d96a2dea8d7f6c3276cc32eae0b8ef67de0e21

**Comment by sjtuross** [comment]
感谢更新代码！

试了下mpv，用web那个按钮可以，但是点植入的链接不行，我启用了mpv-debug这个handler得到了下面的错误信息

![image](https://github.com/chen3861229/embyExternalUrl/assets/940110/3232b0ca-5662-412d-99b4-0aede3d32088)

**Comment by chen3861229** [comment]
是我错误去掉了特殊的编码，修改已经提交
35d9ce5816756953ca7f41399bc85b05ea7354de
