### ISSUE TITLE
最新版好像不显示日志了

### ISSUE THREAD

**Issue by anyingxiuluo** [chen3861229/embyExternalUrl#34]
大佬，用docker logs -f -n 10 nginx-emby 2>&1  | grep js:命令，最新版不显示日志了

**Comment by anyingxiuluo** [comment]
还有embyPathMapping参数2似乎不生效

**Comment by anyingxiuluo** [comment]
1.改了容器名称还是不显示日志，我直接在/nginx/log/error.log里面看的日志。

2.我播放 内部为/开头的相对路径的 stem时显示日志`mount emby file path: /CloudNAS/115/test/AEGE/AEGE-005/AEGE-005.mp4
embyPathMapping: [[0,0,"/sp",""],[0,1,"/CloudNAS",""]]
strMapping replace: /sp => 
mapped emby file path: /CloudNAS/115/test/AEGE/AEGE-005/AEGE-005.mp4
2ms, fetchAlistPathApi async function cost
fetchAlistPathApi, UA: libmpv
alistRes: error500: alist_path_api 500 failed get storage: storage not found; rawPath: /CloudNAS/115/test/AEGE/AEGE-005/AEGE-005.mp4
will req alist /api/fs/list to rerty
`按道理应该匹配[0,1,"/CloudNAS",""]规则而不是[0,0,"/sp",""]

**Comment by chen3861229** [comment]
1.嗯，其实直接看这个日志文件更全更清晰
2从路径来看这个媒体是挂载后的本地路径开头了，是 strm 文件吗？
3.我测试是有点问题了，稍后我提交下修复

**Comment by chen3861229** [comment]
方便提供下 playbackinfo 这个接口的报文吗？缓存的路径是通过这个判断的 MediaStreams
![image](https://github.com/chen3861229/embyExternalUrl/assets/42368856/3089f0ec-a1f3-47aa-a481-5546ec05dc08)

**Comment by anyingxiuluo** [comment]
[
    {
        "Codec": "h264",
        "CodecTag": "avc1",
        "Language": "und",
        "ColorTransfer": "bt709",
        "ColorPrimaries": "bt709",
        "ColorSpace": "bt709",
        "TimeBase": "1/60000",
        "VideoRange": "SDR",
        "DisplayTitle": "1080p H264",
        "NalLengthSize": "4",
        "IsInterlaced": false,
        "BitRate": 5970832,
        "BitDepth": 8,
        "RefFrames": 1,
        "IsDefault": true,
        "IsForced": false,
        "IsHearingImpaired": false,
        "Height": 1080,
        "Width": 1920,
        "AverageFrameRate": 29.97003,
        "RealFrameRate": 29.97003,
        "Profile": "High",
        "Type": "Video",
        "AspectRatio": "16:9",
        "Index": 0,
        "IsExternal": false,
        "IsTextSubtitleStream": false,
        "SupportsExternalStream": false,
        "Protocol": "File",
        "PixelFormat": "yuv420p",
        "Level": 40,
        "IsAnamorphic": false,
        "ExtendedVideoType": "None",
        "ExtendedVideoSubType": "None",
        "ExtendedVideoSubTypeDescription": "None",
        "AttachmentSize": 0
    },
    {
        "Codec": "aac",
        "CodecTag": "mp4a",
        "Language": "und",
        "TimeBase": "1/48000",
        "DisplayTitle": "AAC stereo (默认)",
        "IsInterlaced": false,
        "ChannelLayout": "stereo",
        "BitRate": 317374,
        "Channels": 2,
        "SampleRate": 48000,
        "IsDefault": true,
        "IsForced": false,
        "IsHearingImpaired": false,
        "Profile": "LC",
        "Type": "Audio",
        "Index": 1,
        "IsExternal": false,
        "IsTextSubtitleStream": false,
        "SupportsExternalStream": false,
        "Protocol": "File",
        "ExtendedVideoType": "None",
        "ExtendedVideoSubType": "None",
        "ExtendedVideoSubTypeDescription": "None",
        "AttachmentSize": 0
    }
]

**Comment by anyingxiuluo** [comment]
另外我发现用infuse播放时能正常判断，用fileball播放时不能正确判断strm

**Comment by chen3861229** [comment]
奇怪，strm 内部文本是 / 开头的路径应该是不会补充入库 MediaStreams 信息来着，只有 http 开头的在第一次播放后才会有这个信息，我这边修复下吧，去掉缓存路径的代码，也差不了十几毫秒

**Comment by anyingxiuluo** [comment]
> 应该已经修复了 [f2e925c](https://github.com/chen3861229/embyExternalUrl/commit/f2e925cbb8130195ddd65ec45c72127ada1df395)

问题已经解决了，感谢大佬
