### ISSUE TITLE
阿里播放失败

### ISSUE THREAD

**Issue by 1373654716** [chen3861229/embyExternalUrl#35]
大佬，其他云盘可以正常直链播放，比如天翼云盘emby可以正常播放，并且是走的直链，但是阿里云盘播放不了是什么原因呢，同一个alist

**Comment by 1373654716** [comment]
2024/05/08 10:06:24 [warn] 19#19: *11120 js: will req alist /api/fs/list to rerty
2024/05/08 10:06:24 [warn] 19#19: *11120 js: try to fetch alist path from /5248/mnt/CloudNAS/5248/5248mv/飞驰人生2.mkv
2024/05/08 10:06:24 [warn] 19#19: *11120 js: try to fetch alist path from /8476/mnt/CloudNAS/5248/5248mv/飞驰人生2.mkv
2024/05/08 10:06:24 [warn] 19#19: *11120 js: try to fetch alist path from /ty/mnt/CloudNAS/5248/5248mv/飞驰人生2.mkv
2024/05/08 10:06:24 [warn] 19#19: *11120 js: fail to fetch alist resource: not found
2024/05/08 10:06:24 [warn] 19#19: *11120 js: === /emby/videos/144764/飞驰人生2.mkv, the NJS VM is destroyed ===
2024/05/08 10:06:27 [warn] 19#19: *11126 js: redirect2Pan, UA: MXPlayer/1.74.6 (Linux; Android 14; zh-CN; 23013RK75C Build/UKQ1.230804.001 release-keys)
2024/05/08 10:06:27 [warn] 19#19: *11126 js: cached PlaybackInfo path, will skip excess fetchEmbyFilePath
2024/05/08 10:06:27 [warn] 19#19: *11126 js: mount emby file path: /mnt/CloudNAS/5248/5248mv/飞驰人生2.mkv
2024/05/08 10:06:27 [warn] 19#19: *11126 js: embyPathMapping: [[0,0,"/mnt/CloudNAS",""]]
2024/05/08 10:06:27 [warn] 19#19: *11126 js: mapped emby file path: /mnt/CloudNAS/5248/5248mv/飞驰人生2.mkv
2024/05/08 10:06:27 [warn] 19#19: *11126 js: 1ms, fetchAlistPathApi async function cost
2024/05/08 10:06:27 [warn] 19#19: *11126 js: fetchAlistPathApi, UA: MXPlayer/1.74.6 (Linux; Android 14; zh-CN; 23013RK75C Build/UKQ1.230804.001 release-keys)
2024/05/08 10:06:27 [warn] 19#19: *11126 js: alistRes: error500: alist_path_api 500 failed get storage: storage not found; rawPath: /peng/mnt/CloudNAS/5248/5248mv/飞驰人生2.mkv
2024/05/08 10:06:27 [warn] 19#19: *11126 js: will req alist /api/fs/list to rerty
2024/05/08 10:06:27 [warn] 19#19: *11126 js: try to fetch alist path from /5248/mnt/CloudNAS/5248/5248mv/飞驰人生2.mkv
2024/05/08 10:06:27 [warn] 19#19: *11126 js: try to fetch alist path from /8476/mnt/CloudNAS/5248/5248mv/飞驰人生2.mkv
2024/05/08 10:06:27 [warn] 19#19: *11126 js: try to fetch alist path from /ty/mnt/CloudNAS/5248/5248mv/飞驰人生2.mkv
2024/05/08 10:06:27 [warn] 19#19: *11126 js: fail to fetch alist resource: not found
2024/05/08 10:06:27 [warn] 19#19: *11126 js: === /emby/videos/144764/飞驰人生2.mkv, the NJS VM is destroyed ===

**Comment by chen3861229** [comment]
这里的路径映射判断出问题了，这个文件是本地挂载的还是 strm 的？
````
2024/05/08 10:06:27 [warn] 19#19: *11126 js: cached PlaybackInfo path, will skip excess fetchEmbyFilePath
2024/05/08 10:06:27 [warn] 19#19: *11126 js: mount emby file path: /mnt/CloudNAS/5248/5248mv/飞驰人生2.mkv
2024/05/08 10:06:27 [warn] 19#19: *11126 js: embyPathMapping: [[0,0,"/mnt/CloudNAS",""]]
2024/05/08 10:06:27 [warn] 19#19: *11126 js: mapped emby file path: /mnt/CloudNAS/5248/5248mv/飞驰人生2.mkv
````

**Comment by 1373654716** [comment]
大佬

> 这里的路径映射判断出问题了，这个文件是本地挂载的还是 strm 的？
> 
> ```
> 2024/05/08 10:06:27 [warn] 19#19: *11126 js: cached PlaybackInfo path, will skip excess fetchEmbyFilePath
> 2024/05/08 10:06:27 [warn] 19#19: *11126 js: mount emby file path: /mnt/CloudNAS/5248/5248mv/飞驰人生2.mkv
> 2024/05/08 10:06:27 [warn] 19#19: *11126 js: embyPathMapping: [[0,0,"/mnt/CloudNAS",""]]
> 2024/05/08 10:06:27 [warn] 19#19: *11126 js: mapped emby file path: /mnt/CloudNAS/5248/5248mv/飞驰人生2.mkv
> ```

大佬你好，不是 strm，是rclone挂载到本地的。我看了下，“/mnt/CloudNAS/5248/5248mv/飞驰人生2.mkv”这个本地路径是正确的啊

**Comment by 1373654716** [comment]
2024/05/08 15:38:50 [warn] 19#19: *788 js: 1ms, fetchAlistPathApi async function cost
2024/05/08 15:38:50 [warn] 19#19: *788 js: fetchAlistPathApi, UA: MXPlayer/1.74.6 (Linux; Android 14; zh-CN; 23013RK75C Build/UKQ1.230804.001 release-keys)
2024/05/08 15:38:50 [warn] 19#19: *788 js: alistRes: error500: alist_path_api 500 failed get storage: storage not found; rawPath: /mnt/CloudNAS/5248/5248mv/飞驰人生2.mkv
2024/05/08 15:38:50 [warn] 19#19: *788 js: will req alist /api/fs/list to rerty
2024/05/08 15:38:50 [warn] 19#19: *788 js: try to fetch alist path from /5248/mnt/CloudNAS/5248/5248mv/飞驰人生2.mkv
2024/05/08 15:38:50 [warn] 19#19: *788 js: fail to fetch alist resource: not found
2024/05/08 15:38:50 [warn] 19#19: *788 js: === /emby/videos/144771/飞驰人生2.mkv, the NJS VM is destroyed ===

--------
这部电影alist正确的路径应该是/5248/5248mv/飞驰人生2.mkv，不知道为什么日志显示的是 try to fetch alist path from /5248/mnt/CloudNAS/5248/5248mv/飞驰人生2.mkv，前面/5248/mnt/CloudNAS/了一个这个

**Comment by chen3861229** [comment]
>try to fetch alist path from

这个是之前没匹配到路径的补偿措施，正常不会走到这里，先不用管这个，新提交可能修复了你最初的问题，有时间可以试下
f2e925cbb8130195ddd65ec45c72127ada1df395

**Comment by 1373654716** [comment]
> > 尝试从中获取 alist 路径
> 
> 这个是之前没匹配到路径的补偿措施，正常不会走到这里，先不用管这个，新提交可能修复了你最初的问题，有时间可以试下 [f2e925c](https://github.com/chen3861229/embyExternalUrl/commit/f2e925cbb8130195ddd65ec45c72127ada1df395)

好的好的，感谢大佬的解答！
