### ISSUE TITLE
官方emby客户端播放阿里云资源时进度条异常

### ISSUE THREAD

**Issue by zfhxi** [chen3861229/embyExternalUrl#36]
rclone+alist挂载的阿里云，使用ios/android版emby官方客户端时均不记录进度条，拖动进度条时，进度条UI并不刷新，退出播放时，当前剧集被直接标记为“已播放”。播放115盘上的资源时，不发生这种情况。

视频录屏演示播放阿里云资源：[here](https://www.alipan.com/s/VjPbZxMRcJc)

也就是说，似乎有两点问题：
* 进度条UI不会随着拖动而刷新
* 退出播放时，无论播放多少，直接被标记为“已播放”，下次打开时又重新从片头播放。

补充：
所使用代码为commit：https://github.com/chen3861229/embyExternalUrl/commit/f991ab1445f9e336d184b10dd5785b120eb16044

**Comment by chen3861229** [comment]
多谢清晰的描述，尝试修复了下，不确定对不对，有时间可以更新代码试下
ca19c9ccbbb447425245f5db7c6287b334dd2094

**Comment by chen3861229** [comment]
那有可能是客户端版本的问题了，我这边装了下安卓的最新官方客户端，没复现出来，尝试升级下最新版客户端吧，
或者让阿里的链接和 115 的处理相同，可以尝试这样配置，但是播放查询 alist 会稍微慢几秒了
````
// 字符串头,用于特殊匹配判断
const strHead = {
  lanIp: ["172.", "10.", "192.", "[fd00:"], // 局域网ip头
  "115": "115.com",
  ali: "aliyundrive.net",
};
const cilentSelfAlistRule = [
  [2, strHead["115"], alistPublicAddr],
  [2, strHead.ali, alistPublicAddr],
];
````

**Comment by chen3861229** [comment]
好的，多谢留档，看来不扫库竟然还有bug
