### ISSUE TITLE
开启路由缓存配置后，会导致短时间内去下载不同集数但实际是同一集的文件

### ISSUE THREAD

**Issue by Katou-Kouseki** [chen3861229/embyExternalUrl#37]
如题，这个有办法单独避免吗，路由缓存还是挺好用的

**Comment by chen3861229** [comment]
请问是Web 端下载还是客户端内下载，这两个 api 不同，可以尝试这样配置一下
````
// 路由缓存配置
const routeCacheConfig = {
  // 总开关,是否开启路由缓存,此为一级缓存,添加阶段为 redirect 和 proxy 之前
  // 短时间内同客户端访问相同资源不会再做判断和请求 alist,有限的防抖措施,出现问题可以关闭此选项
  enable: true,
  // 二级缓存开关,仅针对直链,添加阶段为进入单集详情页,cilentSelfAlistRule 中的和首页直接播放的不生效
  enableL2: false,
  // 缓存键表达式,默认为请求参数 MediaSourceId,好处是命中范围大,但会导致 routeRule 中针对设备的规则失效,多个变量可自行组合修改,冒号分隔
  keyExpression: "r.uri:r.args.MediaSourceId", // "r.args.MediaSourceId:r.args.X-Emby-Device-Id"
};
````

**Comment by Katou-Kouseki** [comment]
> ~请问是Web 端下载还是客户端内下载，这两个 api 不同，可以尝试这样配置一下~
> 
> ```
> // 路由缓存配置
> const routeCacheConfig = {
>   // 总开关,是否开启路由缓存,此为一级缓存,添加阶段为 redirect 和 proxy 之前
>   // 短时间内同客户端访问相同资源不会再做判断和请求 alist,有限的防抖措施,出现问题可以关闭此选项
>   enable: true,
>   // 二级缓存开关,仅针对直链,添加阶段为进入单集详情页,cilentSelfAlistRule 中的和首页直接播放的不生效
>   enableL2: false,
>   // 缓存键表达式,默认为请求参数 MediaSourceId,好处是命中范围大,但会导致 routeRule 中针对设备的规则失效,多个变量可自行组合修改,冒号分隔
>   keyExpression: "r.uri:r.args.MediaSourceId", // "r.args.MediaSourceId:r.args.X-Emby-Device-Id"
> };
> ```
> 
> 多谢反馈了，应该已经修复了，尝试更新下代码 [5e5a9cd](https://github.com/chen3861229/embyExternalUrl/commit/5e5a9cdedeaaa414ee0d6f5ef90f5ddfe77692fb)

非常感谢！更新后可以了
