### ISSUE TITLE
plex官方客户端无法播放

### ISSUE THREAD

**Issue by mzouxx** [chen3861229/embyExternalUrl#38]
大佬好，我用alist挂载到本地的，目前plex网页端可以正常直链播放，plex安卓官方客户端里无法播放成功，显示播放出错，但是如果在plex客户端里勾选第三方播放器，用第三方播放器播放又可以直链播放成功。plex客户端里质量什么的都已经选了最高了，请教一下是什么原因。
以下为日志：
2024/05/15 14:40:26 [warn] 19#19: *2563 js: === /hubs/continueWatching, the NJS VM is destroyed ===
2024/05/15 14:45:35 [warn] 19#19: *2654 js: === /hubs/sections/1, the NJS VM is destroyed ===
2024/05/15 14:45:54 [warn] 19#19: *2678 js: === /hubs/sections/1, the NJS VM is destroyed ===
2024/05/15 14:45:59 [warn] 19#19: *2659 js: === /library/metadata/33, the NJS VM is destroyed ===
2024/05/15 14:46:05 [warn] 19#19: *2655 js: === /library/metadata/33, the NJS VM is destroyed ===
2024/05/15 14:46:08 [warn] 19#19: *2655 js: === /library/metadata/33, the NJS VM is destroyed ===
2024/05/15 14:46:08 [warn] 19#19: *2659 js: === /library/metadata/33, the NJS VM is destroyed ===
2024/05/15 14:46:10 [warn] 19#19: *2655 js: === /video/:/transcode/universal/decision, the NJS VM is destroyed ===
2024/05/15 14:46:13 [warn] 19#19: *2655 js: === /library/metadata/33, the NJS VM is destroyed ===
2024/05/15 14:46:16 [warn] 19#19: *2655 js: === /video/:/transcode/universal/decision, the NJS VM is destroyed ===
2024/05/15 14:46:18 [warn] 19#19: *2655 js: === /hubs/sections/1, the NJS VM is destroyed ===
2024/05/15 14:46:20 [warn] 19#19: *2659 js: === /library/metadata/33, the NJS VM is destroyed ===
2024/05/15 14:48:28 [warn] 19#19: *2714 js: === /hubs/sections/1, the NJS VM is destroyed ===
2024/05/15 14:48:39 [warn] 19#19: *2721 js: === /hubs/continueWatching, the NJS VM is destroyed ===
2024/05/15 14:48:39 [warn] 19#19: *2723 js: === /hubs/promoted, the NJS VM is destroyed ===
2024/05/15 14:48:46 [warn] 19#19: *2743 js: === /hubs/sections/1, the NJS VM is destroyed ===

**Comment by chen3861229** [comment]
日志中没有有效信息，有以下几种可能
1.媒体格式不支持，不过 web 端可以播放，如果是同一个视频，理论上不应该，web 端的媒体支持情况更少
2.可能是 https 禁止发送 http 不安全内容的问题，也就是 plex 配置了 https ,而 alist 还是 http，不过这个只会在 115 资源上存在这个问题

如果还是不行，只能打开 constans 中允许转码，播放成功率会高一些，不过会走中转流量的转码
