### ISSUE TITLE
大佬按步骤做的 没成功 alist是先前已经部署好的 就把那部分删掉了 这是啥原因

### ISSUE THREAD

**Issue by Yan-nian** [chen3861229/embyExternalUrl#43]
2024/06/01 16:10:21 [emerg] 1#1: unknown directive "js_shared_dict_zone" in /etc/nginx/conf.d/plex.conf:9
2024/06/01 16:10:22 [emerg] 1#1: unknown directive "js_shared_dict_zone" in /etc/nginx/conf.d/plex.conf:9
2024/06/01 16:10:22 [emerg] 1#1: unknown directive "js_shared_dict_zone" in /etc/nginx/conf.d/plex.conf:9
2024/06/01 16:10:23 [emerg] 1#1: unknown directive "js_shared_dict_zone" in /etc/nginx/conf.d/plex.conf:9
2024/06/01 16:10:24 [emerg] 1#1: unknown directive "js_shared_dict_zone" in /etc/nginx/conf.d/plex.conf:9
2024/06/01 16:10:26 [emerg] 1#1: unknown directive "js_shared_dict_zone" in /etc/nginx/conf.d/plex.conf:9
2024/06/01 16:10:29 [emerg] 1#1: unknown directive "js_shared_dict_zone" in /etc/nginx/conf.d/plex.conf:9
2024/06/01 16:10:36 [emerg] 1#1: unknown directive "js_shared_dict_zone" in /etc/nginx/conf.d/plex.conf:9
2024/06/01 16:10:49 [emerg] 1#1: unknown directive "js_shared_dict_zone" in /etc/nginx/conf.d/plex.conf:9
2024/06/01 16:11:15 [emerg] 1#1: unknown directive "js_shared_dict_zone" in /etc/nginx/conf.d/plex.conf:9
2024/06/01 16:12:06 [emerg] 1#1: unknown directive "js_shared_dict_zone" in /etc/nginx/conf.d/plex.conf:9
2024/06/01 16:13:06 [emerg] 1#1: unknown directive "js_shared_dict_zone" in /etc/nginx/conf.d/plex.conf:9
2024/06/01 16:14:06 [emerg] 1#1: unknown directive "js_shared_dict_zone" in /etc/nginx/conf.d/plex.conf:9
2024/06/01 16:15:07 [emerg] 1#1: unknown directive "js_shared_dict_zone" in /etc/nginx/conf.d/plex.conf:9

**Comment by chen3861229** [comment]
nginx 内置的 njs 版本低了
需要 > 0.8.0，直接 nginx:latest 即可
This directive appeared in version 0.8.0.
https://nginx.org/en/docs/http/ngx_http_js_module.html#js_shared_dict_zone

**Comment by Yan-nian** [comment]
2024/06/02 07:58:13 [notice] 1#1: using the "epoll" event method
2024/06/02 07:58:13 [notice] 1#1: nginx/1.26.1
2024/06/02 07:58:13 [notice] 1#1: built by gcc 13.2.1 20231014 (Alpine 13.2.1_git20231014) 
2024/06/02 07:58:13 [notice] 1#1: OS: Linux 5.13.x
2024/06/02 07:58:13 [notice] 1#1: getrlimit(RLIMIT_NOFILE): 1024:4096
2024/06/02 07:58:13 [notice] 1#1: start worker processes
2024/06/02 07:58:13 [notice] 1#1: start worker process 19
2024/06/02 07:58:13 [notice] 1#1: start worker process 20
2024/06/02 07:58:13 [notice] 1#1: start worker process 21
2024/06/02 07:58:13 [notice] 1#1: start worker process 22
我换了个镜像 然后显示这个 试了下远程播放 没成功
