### ISSUE TITLE
经过直链反代以后 直播电视在外网 无法播放，在内网正常播放，不经过直链反代可以正常播放，麻烦大佬排查一下

### ISSUE THREAD

**Issue by wanyuxi88** [chen3861229/embyExternalUrl#44]
![Uploading IMG_2577.PNG…]()

**Comment by wanyuxi88** [comment]
![IMG_2577](https://github.com/chen3861229/embyExternalUrl/assets/83001660/15b0b0d7-be11-4c49-a170-f75380a5b034)

**Comment by wanyuxi88** [comment]
![IMG_2582](https://github.com/chen3861229/embyExternalUrl/assets/83001660/8b3513ab-843b-444f-887a-40e6e76da055)

**Comment by wanyuxi88** [comment]
plex.0517788.xyz是plex外网指定访问url
 192.168.10.3是lucky反代地址
现在是外网>lucky>medialinker>plex
不经过medialinker就不影响直播源观看
直播源是江苏电信组播源https://udpxy.0517788.xyz/udp/239.49.8.129:6000

**Comment by wanyuxi88** [comment]
域名不是真实的。是化名

**Comment by chen3861229** [comment]
日志很清晰，之前正则写得太宽泛了，已经修复
3f766021a5e0ba04a4f755e8fd301dbfb20acbdf

**Comment by wanyuxi88** [comment]
经过测试 已成功修复
