### ISSUE TITLE
vidhub播放无法记录播放进度

### ISSUE THREAD

**Issue by kingtalk** [chen3861229/embyExternalUrl#45]
vidhub偶发无法记录播放进度的问题，看了error.log，分为两种情况。
/emby/videos/14580/stream.mp4:代码，这种情况可以记录播放进度
/emby/videos/14580/stream.strm:代码，这种情况不能记录播放进度
我的strm里面是域名链接，不是本地替换链接。

本地替换链接好像无论如何都无法记录播放进度。

**Comment by chen3861229** [comment]
测试了下，这个主要依赖于 emby 对 strm 媒体第一次播放后补充入库的媒体编码信息，表现形式为单集详情页下方的媒体信息中有没有视频的编码信息，将导致 itemInfo 接口中的 RunTimeTicks 可播放毫秒值没有这个字段，所以以下情况是无法记录播放进度的

1.strm 内部文本为 / 开头的，这个属于脚本强行兼容支持的播放，emby 服务端不会进行补充信息
2.strm 内部文本为 http 开头的远程链接，只在第一次播放的时候估计也是没有编码信息的，第一次播放后 emby 客户端都会报告媒体信息给 server 端进行补充媒体编码信息，可退出后查看详情页下方有没有多出来媒体编码信息，然后再进行播放就是没问题的了

3.补充，emby 插件库里有个貌似可以定时处理 strm 媒体信息的，设置-高级-插件-Catalog-元数据-StrmExtract，我这边只是看到了，没有尝试过这个插件，需要自行摸索了，但是这样其实 strm 又扫库了，虽然可能是定时可控可手动取消的，这点也需要自行权衡下

**Comment by chen3861229** [comment]
测试了下，这个主要依赖于 emby 对 strm 媒体第一次播放后补充入库的媒体编码信息，表现形式为单集详情页下方的媒体信息中有没有视频的编码信息，将导致 itemInfo 接口中的 RunTimeTicks 可播放毫秒值没有这个字段，所以以下情况是无法记录播放进度的

1.strm 内部文本为 / 开头的，这个属于脚本强行兼容支持的播放，emby 服务端不会进行补充信息
2.strm 内部文本为 http 开头的远程链接，只在第一次播放的时候估计也是没有编码信息的，第一次播放后 emby 客户端都会报告媒体信息给 server 端进行补充媒体编码信息，可退出后查看详情页下方有没有多出来媒体编码信息，然后再进行播放就是没问题的了

3.补充，emby 插件库里有个貌似可以定时处理 strm 媒体信息的，设置-高级-插件-Catalog-元数据-StrmExtract，我这边只是看到了，没有尝试过这个插件，需要自行摸索了，但是这样其实 strm 又扫库了，虽然可能是定时可控可手动取消的，这点也需要自行权衡下

**Comment by chaomarks** [comment]
> vidhub偶发无法记录播放进度的问题，看了error.log，分为两种情况。 /emby/videos/14580/stream.mp4:代码，这种情况可以记录播放进度 /emby/videos/14580/stream.strm:代码，这种情况不能记录播放进度 我的strm里面是域名链接，不是本地替换链接。
> 
> 本地替换链接好像无论如何都无法记录播放进度。

你用vidhub播放，直链strm文件内容是http链接还是本地模式/

**Comment by kingtalk** [comment]
> > vidhub偶发无法记录播放进度的问题，看了error.log，分为两种情况。 /emby/videos/14580/stream.mp4:代码，这种情况可以记录播放进度 /emby/videos/14580/stream.strm:代码，这种情况不能记录播放进度 我的strm里面是域名链接，不是本地替换链接。
> > 本地替换链接好像无论如何都无法记录播放进度。
> 
> 你用vidhub播放，直链strm文件内容是http链接还是本地模式/

两个都试过，最开始http有进度，本都路径无进度，后来改为http后依然无进度，目前通过strm扫描解决。没有折腾本地模式，东西太多了。
