### ISSUE TITLE
不确定经过直链以后 下载到本地预告片播放很慢，感觉是全部下载到手机上再播放

### ISSUE THREAD

**Issue by wanyuxi88** [chen3861229/embyExternalUrl#46]
/ # tail -f /var/log/nginx/error.log
2024/06/09 01:53:40 [warn] 29#29: *34240 js: === plexApiHandler: /hubs/promoted, the NJS VM is destroyed ===
2024/06/09 01:53:40 [warn] 29#29: *34243 an upstream response is buffered to a temporary file /var/lib/nginx/tmp/proxy/2/84/0000001842 while reading upstream, client: 192.168.10.3, server: default, request: "GET /hubs/promoted?contentDirectoryID=4&count=25&excludeContinueWatching=1&includeExternalMedia=1&includeMeta=1&includeRecentChannels=1&pinnedContentDirectoryID=1%2C2%2C15%2C3%2C4%2C16&X-Plex-Language=zh-CN&X-Plex-Device-Name=iPhone HTTP/1.1", subrequest: "/hubs/promoted", upstream: "http://192.168.1.2:32400/hubs/promoted?contentDirectoryID=4&count=25&excludeContinueWatching=1&includeExternalMedia=1&includeMeta=1&includeRecentChannels=1&pinnedContentDirectoryID=1%2C2%2C15%2C3%2C4%2C16&X-Plex-Language=zh-CN&X-Plex-Device-Name=iPhone", host: "xxx"
2024/06/09 01:53:40 [warn] 29#29: *34243 js: === plexApiHandler: /hubs/promoted, the NJS VM is destroyed ===
2024/06/09 01:53:40 [warn] 28#28: *34227 js: === plexApiHandler: /hubs/continueWatching, the NJS VM is destroyed ===
2024/06/09 01:53:41 [warn] 29#29: *34248 an upstream response is buffered to a temporary file /var/lib/nginx/tmp/proxy/3/84/0000001843 while reading upstream, client: 192.168.10.3, server: default, request: "GET /hubs/continueWatching?contentDirectoryID=1%2C2%2C15%2C3%2C4%2C16&includeExternalMedia=1&includeMeta=1&includeRecentChannels=1&X-Plex-Language=zh-CN&X-Plex-Device-Name=iPhone HTTP/1.1", subrequest: "/hubs/continueWatching", upstream: "http://192.168.1.2:32400/hubs/continueWatching?contentDirectoryID=1%2C2%2C15%2C3%2C4%2C16&includeExternalMedia=1&includeMeta=1&includeRecentChannels=1&X-Plex-Language=zh-CN&X-Plex-Device-Name=iPhone", host: "xxx"
2024/06/09 01:53:41 [warn] 29#29: *34248 js: === plexApiHandler: /hubs/continueWatching, the NJS VM is destroyed ===
2024/06/09 01:53:49 [warn] 29#29: *34248 js: === plexApiHandler: /library/metadata/17137, the NJS VM is destroyed ===
2024/06/09 01:53:49 [warn] 28#28: *34273 js: === plexApiHandler: /library/metadata/17137, the NJS VM is destroyed ===
2024/06/09 01:53:59 [warn] 25#25: *34303 js: === plexApiHandler: /library/metadata/10798, the NJS VM is destroyed ===
2024/06/09 01:53:59 [warn] 27#27: *34305 js: === plexApiHandler: /library/metadata/10798, the NJS VM is destroyed ===
2024/06/09 01:56:23 [warn] 28#28: *34322 js: plexApiHandler subrequest failed
2024/06/09 01:56:23 [warn] 28#28: *34322 js: use original link
2024/06/09 01:56:23 [warn] 28#28: *34322 js: routeL1Dict add: [/playQueues] : [@root]
2024/06/09 01:56:23 [warn] 28#28: *34322 js: === plexApiHandler: /playQueues, the NJS VM is destroyed ===
2024/06/09 01:56:23 [warn] 28#28: *34322 js: partInfoDict add: [/library/parts/18573/0/file.mp4] : [/volume2/video2/link/电影/来自汪星的你 (2024)/来自汪星的你 (2024) - 1080p-trailer.mp4]
2024/06/09 01:56:23 [warn] 28#28: *34322 js: === plexApiHandler: /library/metadata/17211, the NJS VM is destroyed ===
2024/06/09 01:56:23 [warn] 28#28: *34322 js: === plexApiHandler: /library/metadata/17211, the NJS VM is destroyed ===
2024/06/09 01:56:23 [warn] 28#28: *34322 js: === plexApiHandler: /video/:/transcode/universal/decision, the NJS VM is destroyed ===
2024/06/09 01:56:23 [warn] 28#28: *34322 js: redirect2Pan, UA: libmpv
2024/06/09 01:56:23 [warn] 28#28: *34322 js: getPlexItemInfo r.uri: /library/parts/18573/0/file.mp4
2024/06/09 01:56:23 [warn] 28#28: *34322 js: 0ms, getPlexItemInfo async function cost
2024/06/09 01:56:23 [warn] 28#28: *34322 js: get filePath from cache partInfoDict
2024/06/09 01:56:23 [warn] 28#28: *34322 js: notLocal: false
2024/06/09 01:56:23 [warn] 28#28: *34322 js: mount plex file path: /volume2/video2/link/电影/来自汪星的你 (2024)/来自汪星的你 (2024) - 1080p-trailer.mp4
2024/06/09 01:56:23 [warn] 28#28: *34322 js: hit proxy, not mountPath first: ["/volume2/CloudNAS/CloudDrive2"]
2024/06/09 01:56:23 [warn] 28#28: *34322 js: getRouteMode: proxy
2024/06/09 01:56:23 [warn] 28#28: *34322 js: use original link
2024/06/09 01:56:23 [warn] 28#28: *34322 js: routeL1Dict add: [/library/parts/18573/0/file.mp4] : [@root]
2024/06/09 01:56:23 [warn] 28#28: *34322 an upstream response is buffered to a temporary file /var/lib/nginx/tmp/proxy/4/84/0000001844 while reading upstream, client: 192.168.10.3, server: default, request: "GET /library/parts/18573/0/file.mp4?X-Plex-Client-Identifier=A8B89D01-CD64-41C9-B82B-15DF92DFE857&X-Plex-Client-Platform=iOS&X-Plex-Device=iPhone&X-Plex-Device-Screen-Density=3&X-Plex-Device-Screen-Resolution=1170x2532&X-Plex-Device-Vendor=Apple&X-Plex-Drm=fairplay%3Avideo&X-Plex-Http-Pipeline=infinite&X-Plex-Model=13%2C2&X-Plex-Platform=iOS&X-Plex-Platform-Version=14.8.1&X-Plex-Product=Plex%20for%20iOS&X-Plex-Provides=client%2Ccontroller%2Csync-target%2Cplayer%2Cpubsub-player%2Cprovider-playback&X-Plex-Session-Id=5CAA1B1C-EC80-481F-AEC5-5D902A8FCAA7&X-Plex-Supported-Commands=abort%2CchangeQuality&X-Plex-Sync-Version=2&X-Plex-Token=bAi6utBNogA4rHt6GpXv&X-Plex-Username=wanyuxi&X-Plex-Version=8.35&X-Plex-Language=zh-CN&X-Plex-Device-Name=iPhone HTTP/1.1", upstream: "http://192.168.1.2:32400/library/parts/18573/0/file.mp4?X-Plex-Client-Identifier=A8B89D01-CD64-41C9-B82B-15DF92DFE857&X-Plex-Client-Platform=iOS&X-Plex-Device=iPhone&X-Plex-Device-Screen-Density=3&X-Plex-Device-Screen-Resolution=1170x2532&X-Plex-Device-Vendor=Apple&X-Plex-Drm=fairplay%3Avideo&X-Plex-Http-Pipeline=infinite&X-Plex-Model=13%2C2&X-Plex-Platform=iOS&X-Plex-Platform-Version=14.8.1&X-Plex-Product=Plex%20for%20iOS&X-Plex-Provides=client%2Ccontroller%2Csync-target%2Cplayer%2Cpubsub-player%2Cprovider-playback&X-Plex-Session-Id=5CAA1B1C-EC80-481F-AEC5-5D902A8FCAA7&X-Plex-Supported-Commands=abort%2CchangeQuality&X-Plex-Sync-Version=2&X-Plex-Token=bAi6utBNogA4rHt6GpXv&X-Plex-Username=wanyuxi&X-Plex-Version=8.35&X-Plex-Language=zh-CN&X-Plex-Device-Name=iPhone", host: "xxx"
2024/06/09 01:56:31 [warn] 28#28: *34322 js: === redirect2Pan: /library/parts/18573/0/file.mp4, the NJS VM is destroyed ===
2024/06/09 01:56:53 [warn] 28#28: *34322 js: === plexApiHandler: /library/metadata/10798, the NJS VM is destroyed ===
2024/06/09 01:56:53 [warn] 28#28: *34322 an upstream response is buffered to a temporary file /var/lib/nginx/tmp/proxy/5/84/0000001845 while reading upstream, client: 192.168.10.3, server: default, request: "GET /hubs/continueWatching/items?contentDirectoryID=1%2C2%2C15%2C3%2C4%2C16&includeExternalMedia=1&includeMeta=1&X-Plex-Container-Size=25&X-Plex-Container-Start=0&X-Plex-Language=zh-CN&X-Plex-Device-Name=iPhone HTTP/1.1", subrequest: "/hubs/continueWatching/items", upstream: "http://192.168.1.2:32400/hubs/continueWatching/items?contentDirectoryID=1%2C2%2C15%2C3%2C4%2C16&includeExternalMedia=1&includeMeta=1&X-Plex-Container-Size=25&X-Plex-Container-Start=0&X-Plex-Language=zh-CN&X-Plex-Device-Name=iPhone", host: "xxx"
2024/06/09 01:56:53 [warn] 28#28: *34322 js: === plexApiHandler: /hubs/continueWatching/items, the NJS VM is destroyed ===

**Comment by chen3861229** [comment]
日志中这个文件不在挂载目录下，所以走了源服务，没有走直链
```
2024/06/09 01:56:23 [warn] 28#28: *34322 js: mount plex file path: /volume2/video2/link/电影/来自汪星的你 (2024)/来自汪星的你 (2024) - 1080p-trailer.mp4
2024/06/09 01:56:23 [warn] 28#28: *34322 js: hit proxy, not mountPath first: ["/volume2/CloudNAS/CloudDrive2"]
```
假如这个文件也在同挂载目录下，可以映射下目录，
plex2Alist\nginx\conf.d\config\constant-pro.js
```js
// 路径映射,会在 xxxMountPath 之后从上到下依次全部替换一遍,不要有重叠
// 参数1: 0: 默认做字符串替换, 1: 前插, 2: 尾插
// 参数2: 0: 默认只处理/开头的路径且不为 strm, 1: 只处理 strm 内部为/开头的相对路径, 2: 只处理 strm 内部为远程链接的
// 参数3: 来源, 参数4: 目标
const plexPathMapping = [
  [0, 0, "/volume2/video2/link", "/"], 
];
```
即 alist 中为
```
/电影/来自汪星的你 (2024)/来自汪星的你 (2024) - 1080p-trailer.mp4
```

**Comment by wanyuxi88** [comment]
这个预告片应该是plex机制就是下载完再播放，

**Comment by chen3861229** [comment]
应该是这样吧，如果是客户端播放形式就是这样的，只能考虑上边的优化为网盘直链加速下载，或者尝试压缩下媒体大小了
