### ISSUE TITLE
经过软链接之后的文件，无法保存播放进度。麻烦作者指导一下。

### ISSUE THREAD

**Issue by Hiccup90** [chen3861229/embyExternalUrl#47]
猜测应该是emby2alist无法获取软链接的真实路径导致的。

但是示例看不太懂。所以麻烦作者指导下

由于各种遗留问题，所以我的映射可能有点乱，我尽量描述的详细一点

宿主机云盘挂载本地路径：/mnt/addons/ali/xxxxxxx                     软链接后的宿主机路径：/mnt/media/Alist3/ali/xxxxxxxx
docker版EMBY没有映射云盘挂载的路径                                      软链接后路径：/disk3/Alist3/ali/xxxxxxxx
emby2alist 云盘路径：/alist/ali/xxxxx                                              软链接路径：/disk3/Alist3/ali/xxxxxxxx
配置文件尝试使用 [0, "/disk3/Alist3/", "/alist" ], 但是还是没法保存播放记录。

**Comment by chen3861229** [comment]
这个和软连接还有路径映射没关系，因为在 emby 看来都是本地文件系统，播放进度是取决于 emby 服务端入库了媒体的编码和时长信息的，排查下媒体详情页最下方有没有编码信息的卡片，或者参考下
https://github.com/chen3861229/embyExternalUrl/issues/36

**Comment by chen3861229** [comment]
单独测试这个媒体重新刷新下媒体元数据，如果还是出不来，可能 davfs2 对于 302 之类的资源支持不是太好，可能得换 rclone/CD2 之类的挂载了吧

**Comment by Hiccup90** [comment]
嗯，测试过，播放界面的媒体信息能看到视频以及音频的编码信息，也有正常的时长。不过在简介页面就没有。

我明天换rclone测试下。

因为软链接有插件能实时监控，strm的话只能设置成定时扫描，不优雅。。

**Comment by Hiccup90** [comment]
> 单独测试这个媒体重新刷新下媒体元数据，如果还是出不来，可能 davfs2 对于 302 之类的资源支持不是太好，可能得换 rclone/CD2 之类的挂载了吧

尝试更换了rlone挂载，但是阿里的还是无法保存播放进度。不知道是不是挂载参数的问题。

**Comment by Hiccup90** [comment]
看了下#36里面的emby论坛的链接。尝试更新了emby版本。无果
尝试emby直接映射本地挂载文件夹。也不行。

做个记录吧。

emby错误报告如下 

*** Error Report ***
Version: 4.8.8.0
Command line: /system/EmbyServer.dll -programdata /config -ffdetect /bin/ffdetect -ffmpeg /bin/ffmpeg -ffprobe /bin/ffprobe -restartexitcode 3
Operating system: Linux version 6.1.79-Unraid (root@Develop-612) (gcc (GCC) 12.2.0, GNU ld version 2.40-slack151) #1 SMP PREEMPT_DYNAMIC Fri Mar 29 13:34:03 PDT 2024
Framework: .NET 6.0.25
OS/Process: x64/x64
Runtime: system/System.Private.CoreLib.dll
Processor count: 64
Data path: /config
Application path: /system
Emby.Server.MediaEncoding.Unified.Ffmpeg.FfRunException: Emby.Server.MediaEncoding.Unified.Ffmpeg.FfRunException: ffprobe failed - streams and format are both null: -i file:"/alist/ali/test/城寨英雄/城寨英雄_18.mkv" -threads 0 -v info -print_format json -show_streams -show_chapters -show_format -show_data
ffprobe version 5.1-emby_2023_06_25 Copyright (c) 2007-2022 the FFmpeg developers and softworkz for Emby LLC
built with gcc 10.3.0 (crosstool-NG 1.25.0)
file:/alist/ali/test/城寨英雄/城寨英雄_18.mkv: Input/output error

**Comment by chen3861229** [comment]
不知道是不是这个媒体文件的编码比较特殊，导致 ffprobe 获取不到媒体编码元信息，只能换个测试文件，或者换 CD2 挂载试试了

**Comment by Hiccup90** [comment]
> 不知道是不是这个媒体文件的编码比较特殊，导致 ffprobe 获取不到媒体编码元信息，只能换个测试文件，或者换 CD2 挂载试试了

后来想了想，是我自己比较傻。因为软链接的创建是某个docker，然后emby又是另一个docker。所以两家伙映射的路径不一致。导致emby无法识别软链接的源文件。。估计是这么个原因。。还是继续用strm好了。


顺便，最新的更新 阿里转115的记录，好像看不太懂。

**Comment by chen3861229** [comment]
> 阿里转115

这个不用太在意，是因为之前提前有做准备，所以没啥影响，如果没做 alias 配置，只能用 alist / cd2 的跨云盘迁移文件了

**Comment by Hiccup90** [comment]
> > 阿里转115
> 
> 这个不用太在意，是因为之前提前有做准备，所以没啥影响，如果没做 alias 配置，只能用 alist / cd2 的跨云盘迁移文件了
> 
> 简单做了一个补充说明 [3ed7858](https://github.com/chen3861229/embyExternalUrl/commit/3ed7858822bc6bc09cfad08a61ba216a80eb9f17)

嗯。有点印象。我记得以前的兜底是，会去全盘搜索同名文件，进行匹配？

**Comment by Hiccup90** [comment]
再次记录一下，今天又闲的蛋疼，又重新折腾了一下软链接。算是成功了。

改成rclone挂载，emby映射软连接的源目录，并增加/dev/fuse的映射，这样就能正常刮削。

然后也能正常播放了。不过这时候，哪怕停止播放，还是会从115疯狂下载资源。不知道下载的什么，怕被115限制或者熔断，赶紧删除了。

**Comment by chen3861229** [comment]
> 并增加/dev/fuse的映射

1.这个其实是必须的，所有挂载工具的 docker 版基本都依赖 fuse 工具包

> 怕被115限制或者熔断

2.这个建议用 alist 再套一层开限流比较简单，停止播放还在下载应该是 emby 在做提取内封字幕的操作或媒体信息的操作，这个稍微等会儿就会停止了，没啥太大问题，我这边并发最大是 5 个人同时用，暂时也是没啥太大问题

https://github.com/bpking1/embyExternalUrl/blob/main/emby2Alist/README.md#2024-04-05

>3.alist 一定要开启 115 网盘驱动的限制速率,它的限制比较严格,一扫库必定熔断,默认为 2【限制所有 api 请求速率(1r/[limit_rate]s)】, 意味着 2 秒内只处理 1 个请求,个人设置为 1 也是没问题的,此为限流最小值,缺点是整库扫持续时间会达到一周,但是不会触发熔断,比较安全, 不要设置为 0 ,代表没限制,阿里网盘的熔断机制相对宽松很多,除非一次性文件太多,但是截止当前,alist 并没有当前网盘的限流参数

**Comment by Hiccup90** [comment]
2、对，应该是emby的操作，因为我是外网观看，观看的时候。没有上传，全部都在下载。停止观看了。还在下载。我也已经套了alist，不过限流默认是2。还没改。感觉有点怂。目前看起来，还是strm比较保险？

**Comment by chen3861229** [comment]
额，这些方案其实各有优缺点，就看个人的接受程度了，strm 也是有 bug 的，比如初始播放响应慢一点，不符合 emby 官方文档格式的话播放进度和播放历史会有无记录的情况

**Comment by Hiccup90** [comment]
哈哈哈哈。好的。感谢作者的耐心回复。

哦。还有个小tips，你之前也提过。但是我之前没有特别去注意，所以走了很多弯路。。

就是测试完一种方案之后，测试其他方案，一定要对测试的文件，刷新元数据，要不然重新入库也没用的。
