### ISSUE TITLE
关于embyLaunchPotplayer和alistWebLaunchExternalPlayer的若干问题

### ISSUE THREAD

**Issue by sjtuross** [chen3861229/embyExternalUrl#48]
embyLaunchPotplayer这个我看已经更新到1.1.8了，但是油猴那个链接还是1.1.0，有没有最新版的链接呢？

启用embyLaunchPotplayer之后，在Jellyfin里面的外部播放器图标是出现了，但是实际调用播放器放不了，试过pot和vlc，10.8和10.9一样。

alistWebLaunchExternalPlayer启用后，新的外部播放器图标是出现了，但是实际调用播放器放不了，貌似是URL编码问题，换用alist自带的没问题。

感谢大佬的付出！

**Comment by chen3861229** [comment]
1.这个暂时需要手动粘贴下新代码，我尝试联系下 bpking1 大佬，不然再开一个脚本链接没必要
2.这个和 emby 的注意事项是一样的，是不是测试的播放器没有注册 URL 处理，看下浏览器控制台是否有错误提示，
Failed to launch 'potplayer://xxx' because the scheme does not have a registered handler.
3.编码问题刚修复，稍后更新下就行了

**Comment by sjtuross** [comment]
关于第2个问题，不是注册URL的问题，播放器都调用成功了，以下是pot和vlc的错误截图

![image](https://github.com/chen3861229/embyExternalUrl/assets/940110/53aa8cf8-ee2c-4cb4-9ebd-5c5fd257fe93)

**Comment by chen3861229** [comment]
已经复现修复了
59a78e53e8d538a5efcf1e40b8a13f0b1b943405

**Comment by sjtuross** [comment]
感谢，解决了。测试过程中发现potplayer不支持播放strm，不过这是播放器的问题，vlc没问题。
