### ISSUE TITLE
不依赖alist的redirect2Pan

### ISSUE THREAD

**Issue by sjtuross** [chen3861229/embyExternalUrl#49]
这不是个问题，只是个想法，主要是依赖alist，一方面增加了转发处理时间，另一方面增加了部署依赖度和复杂度。

据我所知 https://github.com/T3rry7f/Fake115Upload/blob/master/fake115upload.user.js 有获取115直链的js实现方式，这里 https://github.com/thsrite/emby_alipan_redirect 有阿里盘的实现方式，这样这2个用的比较多的网盘就覆盖了，可以作为alist的替代选择。

**Comment by arthurxxy** [comment]
这个想法很不错，希望作者可以优先考虑

**Comment by wxrbbs** [comment]
这个思路可以考虑，目前比较好的转型方式，可以让作者参考优化升级！！！

**Comment by qejkl12138** [comment]
作者可以尝试一下，看看新思路

**Comment by codomo8848** [comment]
这个很6啊

**Comment by chen3861229** [comment]
感谢建议了，其实之前有想过把重定向目标这个概念封装抽取出来，但是考虑了下，工作量比较大😅，我这边能可控的话倒还好，直接实现阿里云和 115 的接口这个工作量和维护量与 alist 还有 CD2 其实重合了，而且 115 还需要斗智斗勇，它俩都实现了 115 的任务队列和限流，不然会被熔断风控，可能还有一些其他的点，个人精力实在有限，毕竟脚本重心还是直链转发上，还是倾向于已有成熟 API 提供的，而且它们社区力量大，其实还有个重点是最近有部分人感觉脚本变得越来越复杂了，直链的核心功能其实没啥变化，再增加配置项之类的部署难度会更高了，例如阿里云的 refresh_token 和 115 的 cookie 获取之类的

**Comment by sjtuross** [comment]
好的，就是交流一下想法，再次感谢大佬的付出❤️
