### ISSUE TITLE
对接emby通知管理员设置开启后无反应，是还需添加其他配置吗？

### ISSUE THREAD

**Issue by Katou-Kouseki** [chen3861229/embyExternalUrl#5]

**Comment by chen3861229** [comment]
是的，emby还需要配置通知的Webhook且勾选外部通知，不然emby没有地方显示日志
![image](https://github.com/chen3861229/embyExternalUrl/assets/42368856/39f61a82-0ab7-4489-be47-59f99a4a229f)
![image](https://github.com/chen3861229/embyExternalUrl/assets/42368856/28d30220-65e4-4156-ab42-17fb2cf72435)
![image](https://github.com/chen3861229/embyExternalUrl/assets/42368856/3e674185-1059-4699-8e46-ca5befafc181)
