### ISSUE TITLE
115直链 emby网页版跨域问题

### ISSUE THREAD

**Issue by anyingxiuluo** [chen3861229/embyExternalUrl#50]
大佬，用你最新版的方法解决115直链 emby网页版跨域问题，还是出现无法兼容的流下面是相关截图，跟我emby是https，alist是http有关吗？
![微信截图_20240622174425](https://github.com/chen3861229/embyExternalUrl/assets/125189022/d9d6a398-1700-4b0e-a350-248b29dfa80d)
![微信截图_20240622174242](https://github.com/chen3861229/embyExternalUrl/assets/125189022/5b9b83f9-4437-4faf-8283-83c24d2965b8)

**Comment by chen3861229** [comment]
> 跟我emby是https，alist是http有关吗？

是的，浏览器默认禁止 https 安全网站加载非安全网站 http 的资源，三种方案选一

1.最好就是给 alist 也套上 https ，alist 官方文档中有教程，不需要反代 alist

2.浏览器网站设置中允许这个行为，点击地址栏上的锁图标，选择此网站的权限，不安全的内容 勾选为 允许，当然这种每个浏览器都得设置一遍，比较麻烦

3.如果没遇到进度条拖动有 bug 的客户端，可以注释掉 cilentSelfAlistRule 中的 115 那条默认规则
emby2Alist\nginx\conf.d\config\constant-mount.js

```js
// 指定客户端自己请求并获取 alist 直链的规则,代码优先级在 redirectStrmLastLinkRule 之后
// 特殊情况使用,则此处必须使用域名且公网畅通,用不着请保持默认
// 参数1: 0: startsWith(str), 1: endsWith(str), 2: includes(str), 3: match(/ain/g)
// 参数2: 匹配目标,对象为 Alist 接口返回的链接 raw_url
// 参数3: 指定转发给客户端的 alist 的 host 前缀,兼容 sign 参数
const cilentSelfAlistRule = [
  // "Emby for iOS"和"Infuse"对于 115 的进度条拖动依赖于此
  // 如果 nginx 为 https,则此 alist 也必须 https,浏览器行为客户端会阻止非 https 请求
  // [2, strHead["115"], alistPublicAddr],
  // [2, strHead.ali, alistPublicAddr],
];
```

**Comment by anyingxiuluo** [comment]
感谢大佬，问题已经解决了，我用的方案三，目前没遇到infuse播放进度条拖动问题

**Comment by liclown2020** [comment]
> > 跟我emby是https，alist是http有关吗？
> 
> 是的，浏览器默认禁止 https 安全网站加载非安全网站 http 的资源，三种方案选一
> 
> 1.最好就是给 alist 也套上 https ，alist 官方文档中有教程，不需要反代 alist
> 
> 2.浏览器网站设置中允许这个行为，点击地址栏上的锁图标，选择此网站的权限，不安全的内容 勾选为 允许，当然这种每个浏览器都得设置一遍，比较麻烦
> 
> 3.如果没遇到进度条拖动有 bug 的客户端，可以注释掉 cilentSelfAlistRule 中的 115 那条默认规则 emby2Alist\nginx\conf.d\config\constant-mount.js
> 
> ```js
> // 指定客户端自己请求并获取 alist 直链的规则,代码优先级在 redirectStrmLastLinkRule 之后
> // 特殊情况使用,则此处必须使用域名且公网畅通,用不着请保持默认
> // 参数1: 0: startsWith(str), 1: endsWith(str), 2: includes(str), 3: match(/ain/g)
> // 参数2: 匹配目标,对象为 Alist 接口返回的链接 raw_url
> // 参数3: 指定转发给客户端的 alist 的 host 前缀,兼容 sign 参数
> const cilentSelfAlistRule = [
>   // "Emby for iOS"和"Infuse"对于 115 的进度条拖动依赖于此
>   // 如果 nginx 为 https,则此 alist 也必须 https,浏览器行为客户端会阻止非 https 请求
>   // [2, strHead["115"], alistPublicAddr],
>   // [2, strHead.ali, alistPublicAddr],
> ];
> ```

大佬，我也有相同的问题，我的npm给alist和emby都做了反代的。方案二和三都试了，都还是不行。方案一我看不懂官方文档的用法就没尝试。。。
