### ISSUE TITLE
Emby和alist的windows服务端115怎么处理302直链

### ISSUE THREAD

**Issue by qq328508474** [chen3861229/embyExternalUrl#52]
我用Windows server系统搭建的Emby和alist，用Rlone映射成本地文件夹，开了虚拟机openwrt的docker安装emby2Alist进行直链转发，阿里云盘和天翼云盘没问题，最近阿里云盘限速，准备试试115。本地emby端口播放没问题，用emby2Alist转直链后，客户端播放器不能播放，看了emby2Alist错误日志，似乎是url编码的问题，请教如何解决，谢谢。
以下是emby2Alist error.log报错的部分内容：

2024/06/29 03:26:48 [warn] 22#22: *89 js: mount emby file path: D:\CloudDrive\AlistCloud\115网盘\高清4\三体周年纪念版(4K)\三体周年纪念版S01E23.mp4
2024/06/29 03:26:48 [warn] 22#22: *89 js: getRouteMode: redirect
2024/06/29 03:26:48 [warn] 22#22: *89 js: embyPathMapping: [[0,0,"D:\\CloudDrive\\AlistCloud",""]]
2024/06/29 03:26:48 [warn] 22#22: *89 js: strMapping replace: D:\CloudDrive\AlistCloud => 
2024/06/29 03:26:48 [warn] 22#22: *89 js: mapped emby file path: \115网盘\高清4\三体周年纪念版(4K)\三体周年纪念版S01E23.mp4
2024/06/29 03:26:48 [warn] 22#22: *89 js: hit cilentSelfAlistRule: [2,"115.com","http://xxx:5244"]
2024/06/29 03:26:48 [warn] 22#22: *89 js: 139ms, fetchAlistPathApi async function cost
2024/06/29 03:26:48 [warn] 22#22: *89 js: fetchAlistPathApi, UA: libmpv
2024/06/29 03:26:48 [warn] 22#22: *89 js: redirect to: http://xxx:5244/d%5C115%E7%BD%91%E7%9B%98%5C%E9%AB%98%E6%B8%854%5C%E4%B8%89%E4%BD%93%E5%91%A8%E5%B9%B4%E7%BA%AA%E5%BF%B5%E7%89%88(4K)%5C%E4%B8%89%E4%BD%93%E5%91%A8%E5%B9%B4%E7%BA%AA%E5%BF%B5%E7%89%88S01E23.mp4
2024/06/29 03:26:48 [warn] 22#22: *89 js: routeL1Dict add: [/emby/videos/325839/stream.mp4:4cf151f6db69792d31b752d1f5b5a65b] : [http://xxx:5244/d%5C115%E7%BD%91%E7%9B%98%5C%E9%AB%98%E6%B8%854%5C%E4%B8%89%E4%BD%93%E5%91%A8%E5%B9%B4%E7%BA%AA%E5%BF%B5%E7%89%88(4K)%5C%E4%B8%89%E4%BD%93%E5%91%A8%E5%B9%B4%E7%BA%AA%E5%BF%B5%E7%89%88S01E23.mp4]
2024/06/29 03:26:48 [warn] 22#22: *89 js: === redirect2Pan: /emby/videos/325839/stream.mp4, the NJS VM is destroyed ===
2024/06/29 03:26:50 [warn] 22#22: *92 js: redirect2Pan, UA: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.115 Safari/537.36
2024/06/29 03:26:50 [warn] 22#22: *92 js: hit cache routeL1Dict: http://xxx:5244/d%5C115%E7%BD%91%E7%9B%98%5C%E9%AB%98%E6%B8%854%5C%E4%B8%89%E4%BD%93%E5%91%A8%E5%B9%B4%E7%BA%AA%E5%BF%B5%E7%89%88(4K)%5C%E4%B8%89%E4%BD%93%E5%91%A8%E5%B9%B4%E7%BA%AA%E5%BF%B5%E7%89%88S01E23.mp4
2024/06/29 03:26:50 [warn] 22#22: *92 js: redirect to: http://xxx:5244/d%5C115%E7%BD%91%E7%9B%98%5C%E9%AB%98%E6%B8%854%5C%E4%B8%89%E4%BD%93%E5%91%A8%E5%B9%B4%E7%BA%AA%E5%BF%B5%E7%89%88(4K)%5C%E4%B8%89%E4%BD%93%E5%91%A8%E5%B9%B4%E7%BA%AA%E5%BF%B5%E7%89%88S01E23.mp4
2024/06/29 03:26:50 [warn] 22#22: *92 js: === redirect2Pan: /emby/videos/325839/stream.mp4, the NJS VM is destroyed ===

**Comment by chen3861229** [comment]
1.用路径映射参数修正 win 平台的反斜杠

emby2Alist\nginx\conf.d\config\constant-pro.js

```js
// 路径映射,会在 xxxMountPath 之后从上到下依次全部替换一遍,不要有重叠,注意 /mnt 会先被移除掉了
// 参数1: 0: 默认做字符串替换, 1: 前插, 2: 尾插
// 参数2: 0: 默认只处理/开头的路径且不为 strm, 1: 只处理 strm 内部为/开头的相对路径, 2: 只处理 strm 内部为远程链接的
// 参数3: 来源, 参数4: 目标
const embyPathMapping = [
  [0, 0, "\", "/"],
];
```

**Comment by qq328508474** [comment]
> 1.用路径映射参数修正 win 平台的反斜杠
> 
> emby2Alist\nginx\conf.d\config\constant-pro.js
> 
> ```js
> // 路径映射,会在 xxxMountPath 之后从上到下依次全部替换一遍,不要有重叠,注意 /mnt 会先被移除掉了
> // 参数1: 0: 默认做字符串替换, 1: 前插, 2: 尾插
> // 参数2: 0: 默认只处理/开头的路径且不为 strm, 1: 只处理 strm 内部为/开头的相对路径, 2: 只处理 strm 内部为远程链接的
> // 参数3: 来源, 参数4: 目标
> const embyPathMapping = [
>   [0, 0, "\", "/"],
> ];
> ```
谢谢回复。
更改constant.js后，网站不能访问。
我是直拷贝的nginx\conf.d\config\constant-pro.js到\conf.d\\constant.js使用，报错内容就是修改的地方

2024/06/29 16:23:54 [emerg] 1#1: SyntaxError: Unterminated string ""],
" in /etc/nginx/conf.d/constant.js:103

这是什么问题呢？

**Comment by qq328508474** [comment]
> 1.用路径映射参数修正 win 平台的反斜杠
> 
> emby2Alist\nginx\conf.d\config\constant-pro.js
> 
> ```js
> // 路径映射,会在 xxxMountPath 之后从上到下依次全部替换一遍,不要有重叠,注意 /mnt 会先被移除掉了
> // 参数1: 0: 默认做字符串替换, 1: 前插, 2: 尾插
> // 参数2: 0: 默认只处理/开头的路径且不为 strm, 1: 只处理 strm 内部为/开头的相对路径, 2: 只处理 strm 内部为远程链接的
> // 参数3: 来源, 参数4: 目标
> const embyPathMapping = [
>   [0, 0, "\", "/"],
> ];
> ```

谢谢回复，我按照你说的修改\nginx\conf.d\config\constant-pro.js，没起作用啊，依然报上面的错误。
然后我想着修改下\nginx\conf.d\constant.js试试，结果网站不能启动。
这是什么问题

**Comment by chen3861229** [comment]
1.日志中那些是步骤提示信息，不是报错信息，不要被 error.log 这个名称误导了

>\nginx\conf.d\constant.js

2.不要改这个，因为拆分后的位于 \nginx\conf.d\config\constant-pro.js，变量重复了

3.alist 是不是默认开启了签名所有？alist 设置 => 全局 => 签名所有，如果是默认的开启状态，需要配置下 alist 的 sign 参数配置，
emby2Alist\nginx\conf.d\config\constant-mount.js 中 sign 的两个的

**Comment by qq328508474** [comment]
> 1.日志中那些是步骤提示信息，不是报错信息，不要被 error.log 这个名称误导了 https://github.com/bpking1/embyExternalUrl/blob/main/FAQ.md#13%E4%B8%BA%E4%BB%80%E4%B9%88%E6%97%A5%E5%BF%97%E5%90%8D%E7%A7%B0%E5%8F%AB-errorlog%E4%B8%8D%E4%BC%9A%E6%9C%89%E6%AD%A7%E4%B9%89%E5%90%97
> 
> > \nginx\conf.d\constant.js
> 
> 2.不要改这个，因为拆分后的位于 \nginx\conf.d\config\constant-pro.js，变量重复了
> 
> 3.alist 是不是默认开启了签名所有？alist 设置 => 全局 => 签名所有，如果是默认的开启状态，需要配置下 alist 的 sign 参数配置， emby2Alist\nginx\conf.d\config\constant-mount.js 中 sign 的两个的

alist已经关闭了签名所有。阿里云盘和天翼云盘是可以302跳转的。目前115那个反斜杠的问题，不知到哪里错误，我不太懂技术，不知道怎么查看错误呢。客户端播放不了115的内容。
再次感谢回复。
实在不行的话，我就用openwrt搭建所有服务，115就没问题了吧。
就是还得从新扫库，电影太多，得等很长时间

**Comment by chen3861229** [comment]
这倒不至于，是我的问题，转义问题忽视了，稍等我测试下

**Comment by qq328508474** [comment]
> 这倒不至于，是我的问题，转义问题忽视了，~稍等我测试下~
> 
> 需要更新下代码，并还原上边提到的 embyPathMapping 参数了，目前默认就是兼容的了

好的，我一会更新，谢谢。
新的emby2Alist还需要修改\nginx\conf.d\config\constant-pro.js这里的
const embyPathMapping = [
  [0, 0, "\", "/"],
这段吗？

**Comment by chen3861229** [comment]
大意了，没有实际测试。。。变量写错了，又修复了一版

**Comment by qq328508474** [comment]
> 大意了，没有实际测试。。。变量写错了，又修复了一版
> 
> > const embyMountPath = ["D:\CloudDrive\AlistCloud"];
> 
> 这个不需要改，都保持原样就行了，具体看这段日志，之前是正常的，不要改
> 
> > 这里怎么显示不了两个斜杠。。。。，就是D:后面有两个斜杠，这里只显示一个。以前我就是用这2个斜杠的路径
> 
> 也不要理会这个，从之前的日志来说是正常的，emby 内部入库的只有一个反斜杠，D:\CloudDrive\AlistCloud
> 
> ```
> 2024/06/29 03:26:48 [warn] 22#22: *89 js: mount emby file path: D:\CloudDrive\AlistCloud\115网盘\高清4\三体周年纪念版(4K)\三体周年纪念版S01E23.mp4
> 2024/06/29 03:26:48 [warn] 22#22: *89 js: getRouteMode: redirect
> 2024/06/29 03:26:48 [warn] 22#22: *89 js: embyPathMapping: [[0,0,"D:\CloudDrive\AlistCloud",""]]
> 2024/06/29 03:26:48 [warn] 22#22: *89 js: strMapping replace: D:\CloudDrive\AlistCloud =>
> 2024/06/29 03:26:48 [warn] 22#22: *89 js: mapped emby file path: \115网盘\高清4\三体周年纪念版(4K)\三体周年纪念版S01E23.mp4
> ```
> 
> 内部代码已经修复，预期应该输出
> 
> ```
> 2024/06/29 03:26:48 [warn] 22#22: *89 js: mapped emby file path: /115网盘/高清4/三体周年纪念版(4K)/三体周年纪念版S01E23.mp4
> ```

大佬，我又重新下载的最新版，和上次更新一样都无法302跳转。今天更新的这2次都是客户端302跳转无法播放，天翼和阿里也无法播放302

**Comment by qq328508474** [comment]
最新的日志好像少了很多信息，客户端播放后（无法播放）部分日志：

2024/06/29 22:53:33 [warn] 20#20: *47 js: mount emby file path: D:\CloudDrive\AlistCloud\115网盘\高清4\三体周年纪念版(4K)\三体周年纪念版S01E23.mp4
2024/06/29 22:53:33 [warn] 20#20: *47 js: getRouteMode: redirect
2024/06/29 22:53:33 [warn] 20#20: *47 js: embyPathMapping: [[0,0,"D:\\CloudDrive\\AlistCloud",""]]
2024/06/29 22:53:33 [warn] 20#20: *47 js: strMapping replaceAll: D:\CloudDrive\AlistCloud => 
2024/06/29 22:53:33 [warn] 20#20: *47 js: windows filePath to URL path  => /
2024/06/29 22:53:33 [warn] 20#20: *47 js: === redirect2Pan: /emby/videos/325839/stream.mp4, the NJS VM is destroyed ===
2024/06/29 22:53:35 [warn] 20#20: *49 js: redirect2Pan, UA: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.101 Safari/537.36
2024/06/29 22:53:35 [warn] 20#20: *49 js: itemInfoUri: http://192.168.5.113:8686/Items?Ids=4cf151f6db69792d31b752d1f5b5a65b&Fields=Path,MediaSources&Limit=1&api_key=6cbd9fa0ce524e63abce43261746b7fd
2024/06/29 22:53:35 [warn] 20#20: *49 js: 51ms, fetchEmbyFilePath async function cost
2024/06/29 22:53:35 [warn] 20#20: *49 js: notLocal: false
2024/06/29 22:53:35 [warn] 20#20: *49 js: mount emby file path: D:\CloudDrive\AlistCloud\115网盘\高清4\三体周年纪念版(4K)\三体周年纪念版S01E23.mp4
2024/06/29 22:53:35 [warn] 20#20: *49 js: getRouteMode: redirect
2024/06/29 22:53:35 [warn] 20#20: *49 js: embyPathMapping: [[0,0,"D:\\CloudDrive\\AlistCloud",""]]
2024/06/29 22:53:35 [warn] 20#20: *49 js: strMapping replaceAll: D:\CloudDrive\AlistCloud => 
2024/06/29 22:53:35 [warn] 20#20: *49 js: windows filePath to URL path  => /
2024/06/29 22:53:35 [warn] 20#20: *49 js: === redirect2Pan: /emby/videos/325839/stream.mp4, the NJS VM is destroyed ===

**Comment by chen3861229** [comment]
不好意思，我这边没 win 的测试环境，所以可能被 md 平台的日志也给转义给误导了，
需要自己尝试下改成下面的，
emby2Alist\nginx\conf.d\emby.js
110 到 114 行
```js
// windows filePath to URL path
  if (embyItemPath.startsWith("\\")) {
    r.warn(`windows filePath to URL path \\ => /`);
    embyItemPath = embyItemPath.replaceAll("\\", "/");
  }
```

**Comment by qq328508474** [comment]
> 不好意思，我这边没 win 的测试环境，所以可能被 markdown 平台的日志也给转义给误导了， 也可直接更新 emby.js 代码 ~需要自己尝试下改成下面的，~ emby2Alist\nginx\conf.d\emby.js 110 到 114 行
> 
> ```js
> // windows filePath to URL path
>   if (embyItemPath.startsWith("\\")) {
>     r.warn(`windows filePath to URL path \\ => /`);
>     embyItemPath = embyItemPath.replaceAll("\\", "/");
>   }
> ```

好了，修改了emby2Alist\nginx\conf.d\emby.js，目前情况正常。天翼和115都能302跳转了。阿里由于限速已转移到115
非常感谢
