### ISSUE TITLE
关于windows端部署cd2、alist、emby2alist重定向不生效的问题

### ISSUE THREAD

**Issue by Ailina0728** [chen3861229/embyExternalUrl#53]
先说下我的运行环境，和其他人不太一样，并非全部都是docker运行，这样做的目的是想着部署方便

我在windows系统下安装了cd2，alist，emby，并在wsl2中运行了docker版的emby2alist，集成镜像来自thsrite/MediaLinker。

运行在wsl2中的docker容器使用镜像网络可以在局域网访问，并且可以访问windows系统下的磁盘，磁盘默认自动挂载在“/mnt”，比如“/mnt/c”，方便后期设置脚本提到的软链接规则需要读取文件目录

cd2挂载了115根目录到本地磁盘 “D:” ，alist挂载115的目录我暂时设置为 “/”  ，emby的媒体目录也是 “D:”

在costant.js中将媒体挂载路径设置为 mediaMountPath = ["D:"];  ，alist端没有开签名，脚本默认也是false，
安装我的理解，如果一份文件在115根目录名为1.mp4，那么在各个服务端的实际路径分别是D:\1.mp4 ；/1.mp4 ； D:\1.mp4
经过脚本的转换首先将“D:” 替换掉了，然后经过windows路径转译变为/1.mp4，正好符合alist的路径，实际测试并不生效，后面又尝试alist端根目录设为/115然后字符串替换，等等各种尝试还是不生效，要么是没经过alist重定向要么就是打不开。

不太懂代码，我知道是我对路径映射的理解有问题，但是现在摸不到头脑，提供一段日志希望能帮我排查一下路径映射在windows端到底该怎么填写

2024/07/09 06:20:22 [info] 35#35: *23 js: embyRes: {"message":"success","path":"D:\\三民窒Sandwich(2023).mp4","itemName":"三民窒Sandwich","notLocal":false}
2024/07/09 06:20:22 [warn] 35#35: *23 js: notLocal: false
2024/07/09 06:20:22 [warn] 35#35: *23 js: mount emby file path: D:\三民窒Sandwich(2023).mp4
2024/07/09 06:20:22 [info] 35#35: *23 js: getRouteMode proxyRules: []
2024/07/09 06:20:22 [warn] 35#35: *23 js: getRouteMode: redirect
2024/07/09 06:20:22 [warn] 35#35: *23 js: mediaPathMapping: [[0,0,"D:",""]]
2024/07/09 06:20:22 [warn] 35#35: *23 js: strMapping replaceAll: D: => 
2024/07/09 06:20:22 [warn] 35#35: *23 js: windows filePath to URL path \ => /
2024/07/09 06:20:22 [warn] 35#35: *23 js: mapped emby file path: /三民窒Sandwich(2023).mp4
2024/07/09 06:20:22 [warn] 35#35: *23 js: 1ms, fetchAlistPathApi async function cost
2024/07/09 06:20:22 [warn] 35#35: *23 js: fetchAlistPathApi, UA: libmpv
2024/07/09 06:20:22 [warn] 35#35: *23 js: alistRes: error500: alist_path_api 500 object not found
2024/07/09 06:20:22 [warn] 35#35: *23 js: will req alist /api/fs/list to rerty
2024/07/09 06:20:22 [warn] 35#35: *23 js: try to fetch alist path from /115/三民窒Sandwich(2023).mp4
192.168.10.239 - - [09/Jul/2024:06:20:22 +0000] "GET /Items/114629/Images/Primary?maxHeight=600&maxWidth=600&quality=90 HTTP/1.1" 500 53 "-" "Fileball/238 CFNetwork/1399 Darwin/22.1.0" "-"
2024/07/09 06:20:23 [warn] 35#35: *23 js: try to fetch alist path from /14t/三民窒Sandwich(2023).mp4
2024/07/09 06:20:23 [warn] 35#35: *23 js: try to fetch alist path from /PT/三民窒Sandwich(2023).mp4
2024/07/09 06:20:23 [warn] 35#35: *23 js: try to fetch alist path from /Shares/三民窒Sandwich(2023).mp4
2024/07/09 06:20:24 [warn] 35#35: *23 js: try to fetch alist path from /unraid/三民窒Sandwich(2023).mp4
2024/07/09 06:20:24 [warn] 35#35: *23 js: try to fetch alist path from /云下载/三民窒Sandwich(2023).mp4
2024/07/09 06:20:25 [warn] 35#35: *23 js: hit cilentSelfAlistRule: [2,"115.com","http://youralist.com:5244"]
2024/07/09 06:20:25 [warn] 35#35: *23 js: redirect to: http://youralist.com:5244/d/%E4%BA%91%E4%B8%8B%E8%BD%BD/%E4%B8%89%E6%B0%91%E7%AA%92Sandwich(2023)%E9%AB%98%E6%B8%85%E4%B8%AD%E5%AD%9798%E5%A0%82%E7%89%B9%E4%BE%9B%E7%89%88.mp4
2024/07/09 06:20:25 [info] 35#35: *23 js: redirectAfter cacheKey: /videos/114629/stream.mp4:6766ec6e91fe1a4b40fcff449149647d
2024/07/09 06:20:25 [warn] 35#35: *23 js: routeL1Dict add: [/videos/114629/stream.mp4:6766ec6e91fe1a4b40fcff449149647d] : [http://youralist.com:5244/d/%E4%BA%91%E4%B8%8B%E8%BD%BD/%E4%B8%89%E6%B0%91%E7%AA%92Sandwich(2023)%E9%AB%98%E6%B8%85%E4%B8%AD%E5%AD%9798%E5%A0%82%E7%89%B9%E4%BE%9B%E7%89%88.mp4]
192.168.10.239 - - [09/Jul/2024:06:20:25 +0000] "GET /videos/114629/stream.mp4?AutoOpenLiveStream=false&IsPlayback=false&MaxStreamingBitrate=42000000&MediaSourceId=6766ec6e91fe1a4b40fcff449149647d&UserId=2917944ed0ff483c9916eedd86c2beae&api_key=ceb2b79238834a3d952d399675a9e79e&PlaySessionId=0c0f2ed090bf460fb0ccd7ccdcf110d1&Static=true HTTP/1.1" 302 138 "-" "libmpv" "-"
2024/07/09 06:20:25 [warn] 35#35: *23 js: === redirect2Pan: /videos/114629/stream.mp4, the NJS VM is destroyed ===

**Comment by chen3861229** [comment]
1.和部署环境没有太大关系，前段时间针对 win 服务端的反斜杠路径做了兼容了了，从提供的日志来看也是正确的 mediaMountPath 设置，然后存在的问题是无关系统的路径映射有些问题

2.尽量在 mapped emby file path 这个日志阶段映射为正确的路径，不要让脚本走到失败补偿的 will req alist /api/fs/list to rerty 以下代码轮询驱动去查询了

3.假设你的路径 D: 对应为 alist 根目录下的 /115 ，因为从媒体的入库路径来看，cd2 挂载的路径选多了一级，本应该选 alist 的 / 路径进行挂载，目前是到了 /115 挂载为了 D: 所以缺失了这个路径对应关系，可以用路径映射来进行手动补充，同时需要去掉脚本的挂载路径参数
```js
// 挂载工具 rclone/CD2 多出来的挂载目录, 例如将 od,gd 挂载到 /mnt 目录下: /mnt/onedrive /mnt/gd ,那么这里就填写 /mnt
// 通常配置一个远程挂载根路径就够了,默认非此路径开头文件将转给原始 emby 处理,不用重复填写至 disableRedirectRule
// 如果没有挂载,全部使用 strm 文件,此项填[""],必须要是数组
const mediaMountPath = [""];

// 路径映射,会在 mediaMountPath 之后从上到下依次全部替换一遍,不要有重叠,注意 /mnt 会先被移除掉了
// 参数1: 0: 默认做字符串替换, 1: 前插, 2: 尾插
// 参数2: 0: 默认只处理/开头的路径且不为 strm, 1: 只处理 strm 内部为/开头的相对路径, 2: 只处理 strm 内部为远程链接的
// 参数3: 来源, 参数4: 目标
const mediaPathMapping = [
  [0, 0, "D:", "/115"],
];
```
以上仅为当前描述的情况，也就是不刷新历史入库文件路径的情况下

3.1 假如你将 cd2 的挂载路径改为了 alist 的 / 挂载为 D: , 那这两项配置参数不用变动，需要 emby 中扫描下媒体文件
```js
// 挂载工具 rclone/CD2 多出来的挂载目录, 例如将 od,gd 挂载到 /mnt 目录下: /mnt/onedrive /mnt/gd ,那么这里就填写 /mnt
// 通常配置一个远程挂载根路径就够了,默认非此路径开头文件将转给原始 emby 处理,不用重复填写至 disableRedirectRule
// 如果没有挂载,全部使用 strm 文件,此项填[""],必须要是数组
const mediaMountPath = ["D:"];
```

4.然后最根本的问题是命中了 hit cilentSelfAlistRule: [2,"115.com","http://youralist.com:5244"]，以下是默认的配置，
看注释，如果客户端 115 的进度条拖动没问题，可以注释掉 [2, strHead["115"], alistPublicAddr], 
如果使用到了 "Emby for iOS"和"Infuse" 这些有 bug 的客户端，则 alistPublicAddr 必须填写实际的公网可访问的域名
```js
// alist 公网地址,用于需要 alist server 代理流量的情况,按需填写
const alistPublicAddr = "http://youralist.com:5244";

// 指定客户端自己请求并获取 alist 直链的规则,代码优先级在 redirectStrmLastLinkRule 之后
// 特殊情况使用,则此处必须使用域名且公网畅通,用不着请保持默认
// 参数1: 0: startsWith(str), 1: endsWith(str), 2: includes(str), 3: match(/ain/g)
// 参数2: 匹配目标,对象为 Alist 接口返回的链接 raw_url
// 参数3: 指定转发给客户端的 alist 的 host 前缀,兼容 sign 参数
const cilentSelfAlistRule = [
  // "Emby for iOS"和"Infuse"对于 115 的进度条拖动依赖于此
  // 如果 nginx 为 https,则此 alist 也必须 https,浏览器行为客户端会阻止非 https 请求
  [2, strHead["115"], alistPublicAddr],
  // [2, strHead.ali, alistPublicAddr],
];
```

**Comment by Ailina0728** [comment]
感谢您的回复，您给出的方案四解决了问题，十分感激。之前三个方案我在没提问题前也都都尝试过，一模一样也没生效，就非常焦虑。
另外还想趁此机会再问一下，软连接的那个
`const symlinkRule = [
  // [0, "/mnt/sda1"],
];`
我是想将本地的一块物理磁盘存放软连接文件，刮削下来的信息之类的，emby读取这个路径然后访问文件再重定向等等流程。比如“E:\媒体库”，现在使用的配置为const mediaMountPath = ["D:"];  然后alist挂载根目录为/，那么这个/mnt/xxx应该是填写哪个路径

**Comment by gongdaoran** [comment]
大佬好，我的运行环境和楼主差不多，cd2，alist，emby都部署在windows系统下，使用Hyper-v搭建istoreos系统，在上面安装了docker版的emby2alist，集成镜像来自thsrite/MediaLinker。
我使用cd2将115挂载在windows本地磁盘"H:"下，将115里的一些文件做了软链接放在在本地磁盘"F:"下，假设软链接文件为F:\test\1.mp4，软链接所指向的路径为H:\115\test\test.mp4，symlinkRule配置为const symlinkRule = [0, "F:\\test"]，程序无法读取软链接所指向的文件路径，结果也实现不了重定向
日志如下:
 js: hit symlinkRule: [0,"F:\\test"]
 js: Error: No such file or directory, skip: F:\test\1.mp4
后来我试了在istoreos系统里部署cd2，alist，emby，并创建软链接程序就可以读取软链接所指向的文件路径，实现了重定向
日志如下:
js: symlinkRule realpath overwrite pre: /mnt/mydisk/tools/auto_symlink/link/1.mp4
js: mount emby file path: /mnt/mydisk/clouddrive/115/test/test.mp4
所以我就想问大佬是我操作有问题，还是说emby2alist没法读取windows系统上软链接文件所指向的文件路径，必须是在emby2alist所部署的系统上创建的软链接才可以读取？

**Comment by chen3861229** [comment]
1.docker 版 nginx 的话 F: 这个目录有挂载到容器中吗？可以手动在容器终端里执行命令看下这个 F:\test\1.mp4 是否存在，和是否有读取的权限

2.windows emby server 环境下我这边确实没实际测试过，不过主要是和文件系统有关，你的情况是和 cd2 还有 nginx 所在的环境强相关，和 alist 还有 emby 应该暂无关系，它俩是通过网络连接的，只需要确保 nginx 所在环境能正确读取到文件系统上的软链接文件就行了

**Comment by Luckystar2025** [comment]
大佬，我将windows系统磁盘"F:"映射到了istoreos的/mnt/F目录下，在创建emby2alist的Docker时使用-v /mnt/F:/F  ，我进入容器/F/text目录使用stat 1.mp4 ，结果如下：
  File: '1.mp4' -> '/??/H:/115/text/ceshi.mp4'
  Size: 0               Blocks: 0          IO Block: 16384  symbolic link
Device: 48h/72d Inode: 2814749767185311  Links: 1
Access: (0000/l---------)  Uid: (    0/    root)   Gid: (    0/    root)
Access: 2024-07-12 03:08:55.021511600 +0000
Modify: 2024-07-12 03:08:55.021511600 +0000
Change: 2024-07-12 03:44:20.584071500 +0000
请问大佬这操作是否正确？

**Comment by chen3861229** [comment]
> File: '1.mp4' -> '/??/H:/115/text/ceshi.mp4'

1.是正确的，这里已经输出了软链接的原始路径信息了

2.但是 WSL 的这种混合 linux 和 win 的路径风格稍微有些难以理解，以下是个人猜测，需要自己试一下了，
假设 emby 中的入库后的路径为 /F/text/1.mp4
```js
// 指定需要获取符号链接真实路径的规则,优先级在 mediaMountPath 和 routeRule 之间
// 注意前提条件是此程序或容器必须挂载或具有对应目录的读取权限,否则将跳过处理,不生效
// 此参数仅在软连接后的文件名和原始文件名不一致或路径差异较大时使用,其余情况建议用 mediaPathMapping
// 参数1: 0: startsWith(str), 1: endsWith(str), 2: includes(str), 3: match(/ain/g)
// 参数2: 匹配目标,对象为媒体服务入库的文件路径(Item.Path)
const symlinkRule = [
  [0, "/F"],
];
```
以上参数具体取决于 emby 服务中媒体的入库文件的路径风格，假如 emby 中是 F:\text\1.mp4 , 则填 F:

2.1 此条规则会让脚本去获取到 /??/H:/115/text/ceshi.mp4 路径，然后再走 mediaMountPath 和 mediaPathMapping
```js
// 挂载工具 rclone/CD2 多出来的挂载目录, 例如将 od,gd 挂载到 /mnt 目录下: /mnt/onedrive /mnt/gd ,那么这里就填写 /mnt
// 通常配置一个远程挂载根路径就够了,默认非此路径开头文件将转给原始 emby 处理,不用重复填写至 disableRedirectRule
// 如果没有挂载,全部使用 strm 文件,此项填[""],必须要是数组
const mediaMountPath = [""];

// 路径映射,会在 mediaMountPath 之后从上到下依次全部替换一遍,不要有重叠,注意 /mnt 会先被移除掉了
// 参数1: 0: 默认做字符串替换replace一次, 1: 前插, 2: 尾插, 3: replaceAll替换全部
// 参数2: 0: 默认只处理/开头的路径且不为 strm, 1: 只处理 strm 内部为/开头的相对路径, 2: 只处理 strm 内部为远程链接的
// 参数3: 来源, 参数4: 目标
const mediaPathMapping = [
  // [0, 0, "/??/H:", ""],
];
```
以上基于这次单次的情况，因为之前是没有 /115 这个命令层级的，所以具体填写需要根据实际情况改动

**Comment by Luckystar2025** [comment]
大佬辛苦了，按照大佬说的我又试了下：
1.将emby server部署到Windows端，symlinkRule 设置为[0, "F:"]和[0, "F:\\text"]两种情况，MediaLinker识别不到软链接文件指向路径的信息，以symlinkRule 设置为[0, "F:\\text"]为例，日志如下：

2024/07/12 16:49:07 [info] 25#25: *4 js: embyRes: {"message":"success","path":"F:\\text\\1.mp4","itemName":"1","notLocal":false}
2024/07/12 16:49:07 [warn] 25#25: *4 js: notLocal: false
2024/07/12 16:49:07 [warn] 25#25: *4 js: hit symlinkRule: [0,"F:\\text"]
2024/07/12 16:49:07 [warn] 25#25: *4 js: Error: No such file or directory, skip: F:\text\1.mp4
2024/07/12 16:49:07 [warn] 25#25: *4 js: mount emby file path: F:\text\1.mp4
2024/07/12 16:49:07 [info] 25#25: *4 js: getRouteMode proxyRules: []
2024/07/12 16:49:07 [warn] 25#25: *4 js: hit proxy, maybe is localFile
2024/07/12 16:49:07 [warn] 25#25: *4 js: getRouteMode: proxy
2024/07/12 16:49:07 [warn] 25#25: *4 js: use original link

2.将emby server部署到Docker端，将windows端磁盘F共享到istoreos下/mnt/F，在创建MediaLinker的Docker时使用
-v /mnt/F:/mnt/F，symlinkRule 设置为[0, "/mnt"]，[0, "/mnt/F"]，[0, "/mnt/F/text"]三种情况，MediaLinker识别不到软链接文件指向路径的信息

2.1 symlinkRule 设置为[0, "/mnt"]，日志如下：

2024/07/12 17:06:58 [info] 25#25: *4 js: embyRes: {"message":"success","path":"/mnt/F/text/1.mp4","itemName":"1","notLocal":false}
2024/07/12 17:06:58 [warn] 25#25: *4 js: notLocal: false
2024/07/12 17:06:58 [warn] 25#25: *4 js: hit symlinkRule: [0,"/mnt"]
2024/07/12 17:06:58 [warn] 25#25: *4 js: Error: No such file or directory, skip: /mnt/F/text/1.mp4
2024/07/12 17:06:58 [warn] 25#25: *4 js: mount emby file path: /mnt/F/text/1.mp4
2024/07/12 17:06:58 [info] 25#25: *4 js: getRouteMode proxyRules: []
2024/07/12 17:06:58 [warn] 25#25: *4 js: hit proxy, maybe is localFile
2024/07/12 17:06:58 [warn] 25#25: *4 js: getRouteMode: proxy
2024/07/12 17:06:58 [warn] 25#25: *4 js: use original link

2.2 symlinkRule 设置为[0, "/mnt/F"]，日志如下：

2024/07/12 17:09:42 [info] 25#25: *5 js: embyRes: {"message":"success","path":"/mnt/F/text/1.mp4","itemName":"1","notLocal":false}
2024/07/12 17:09:42 [warn] 25#25: *5 js: notLocal: false
2024/07/12 17:09:42 [warn] 25#25: *5 js: hit symlinkRule: [0,"/mnt/F"]
2024/07/12 17:09:42 [warn] 25#25: *5 js: Error: No such file or directory, skip: /mnt/F/text/1.mp4
2024/07/12 17:09:42 [warn] 25#25: *5 js: mount emby file path: /mnt/F/text/1.mp4
2024/07/12 17:09:42 [info] 25#25: *5 js: getRouteMode proxyRules: []
2024/07/12 17:09:42 [warn] 25#25: *5 js: hit proxy, maybe is localFile
2024/07/12 17:09:42 [warn] 25#25: *5 js: getRouteMode: proxy
2024/07/12 17:09:42 [warn] 25#25: *5 js: use original link

2.3 symlinkRule 设置为[0, "/mnt/F/text"]，日志如下：
2024/07/12 17:11:44 [info] 25#25: *3 js: embyRes: {"message":"success","path":"/mnt/F/text/1.mp4","itemName":"1","notLocal":false}
2024/07/12 17:11:44 [warn] 25#25: *3 js: notLocal: false
2024/07/12 17:11:44 [warn] 25#25: *3 js: hit symlinkRule: [0,"/mnt/F/text"]
2024/07/12 17:11:44 [warn] 25#25: *3 js: Error: No such file or directory, skip: /mnt/F/text/1.mp4
2024/07/12 17:11:44 [warn] 25#25: *3 js: mount emby file path: /mnt/F/text/1.mp4
2024/07/12 17:11:44 [info] 25#25: *3 js: getRouteMode proxyRules: []
2024/07/12 17:11:44 [warn] 25#25: *3 js: hit proxy, maybe is localFile
2024/07/12 17:11:44 [warn] 25#25: *3 js: getRouteMode: proxy
2024/07/12 17:11:44 [warn] 25#25: *3 js: use original link

很奇怪，MediaLinker识别不到软链接信息，不过进入MediaLinker容器中，使用stat命令查看1.mp4软链接文件是可以读出指向路径的，只不过路径很奇怪， mediaMountPath 和 mediaPathMapping我按照大佬的填写了，不过根本走不到替换字符串这一步
  File: '1.mp4' -> '/??/H:/115/text/ceshi.mp4'
  Size: 0               Blocks: 0          IO Block: 16384  symbolic link
Device: 48h/72d Inode: 204         Links: 1
Access: (0000/l---------)  Uid: (    0/    root)   Gid: (    0/    root)
Access: 2024-07-12 16:13:14.782842300 +0000
Modify: 2024-07-12 16:13:14.782842300 +0000
Change: 2024-07-12 16:13:21.431458400 +0000

**Comment by chen3861229** [comment]
1.不好意思，之前看漏掉了，这个操作有误

>我将windows系统磁盘"F:"映射到了istoreos的/mnt/F目录下，在创建emby2alist的Docker时使用-v /mnt/F:/F ，我进入容器/F/text目录使用stat 1.mp4 ，结果如下：
File: '1.mp4' -> '/??/H:/115/text/ceshi.mp4'

软链接的目录挂载到 docker 目录中需要遵循 emby 中的媒体入库路径的层级，不能少了或多了层级，
~~因为 symlinkRule 未实现路径字符串的替换功能 (暂时不打算实现这个，再多一个目录映射参数过于复杂了且无必要，docker 挂载时遵循相同的目录层级即可)，~~
稍后准备调整代码处理优先级，把这个放置在路径映射后，
综上暂时应该改为 -v /mnt/F:/mnt/F ，这样 docker 容器中才存在 /mnt/F/text1.mp4 ，且 emby 中也存在

> 2024/07/12 17:06:58 [info] 25#25: *4 js: embyRes: {"message":"success","path":"/mnt/F/text/1.mp4","itemName":"1","notLocal":false}

没有更改之前 -v /mnt/F:/F ，docker 容器中不存在 /mnt/F 这个目录，只存在 /F/text1.mp4 这种，缺失了 /mnt 层级，所以 2.1 - 2.3
中都是未找到文件，这里建议用 2.2 或 2.3 中的 symlinkRule 精确路径层级写法，不要用 /mnt 这种太宽泛的写法

2.你的 1 中的情况大概率也是不存在与 emby 中入库文件层级对应的目录造成的，已知 win 版 emby 的路径日志中如下

> 2024/07/12 16:49:07 [info] 25#25: *4 js: embyRes: {"message":"success","path":"F:\text\1.mp4","itemName":"1","notLocal":false}

而 nginx 所在位于 WSL 的 docker 中，linux 路径风格限制不一样，需要我这边修复下代码

**Comment by Luckystar2025** [comment]
麻烦大佬了！针对您提到的第一点，我昨天考虑到docker路径要与Emby路径一致，所以在创建docker时已经更换使用
-v /mnt/F:/mnt/F，结果如上所述。第二点确实如您所说，我猜测这个没办法吧，windows端Emby入库的文件路径都是以磁盘F:开头的，istoreos和docker里文件都是以/开头的，所以我才想着将emby server部署到Docker端，可是2.1 2.2 2.3都读取不到软链接信息

**Comment by chen3861229** [comment]
> emby server部署到Docker端

1.这个有好处也有缺点，好处是备份/还原之类的操作简单了，可以很方便的以相同的入库路径迁移至其他机器上而不用重新刷新媒体库，缺点的话是 WSL 的，底层是通过 Hyper-V 虚拟化实现的，不确定转码性能的损失和显卡驱动设备的兼容性，这个太复杂了，所以我没测试过

2.再次思考了下，感觉和 WSL 的底层路径翻译有关，这个涉及到我的知识盲区了，win 环境 docker 下可能被 WSL 转义了一层导致跨系统的软链接在 nginx 的 fs API 上支持有 bug，这个还不知道如何修复，可能还是得

> 后来我试了在istoreos系统里部署cd2，alist，emby，并创建软链接程序就可以读取软链接所指向的文件路径，实现了重定向

不过只有涉及到文件系统的统一 docker 中就行了，cd2 + emby + nginx , alist 应该可以 win ，它只走了网络协议

**Comment by Luckystar2025** [comment]
是的，应该是跨系统的软链接问题，所以要不全走docker要不windows下不使用软链接而使用strm或emby直接挂在云盘，感谢大佬的解答！！

**Comment by Ailina0728** [comment]
经过一段时间折腾，数据倒腾到了Ubuntu下面，现在所有容器都是基于docker部署，没有了跨系统路径的问题。
直连115文件可以重定向，但是软链接这块还是没看懂，希望提点一下，这个路径怎么对应的，如果symlink目录下有媒体分类的不同目录，比如 /华语电影，/新电影，/老电影...等等的该怎么办
![issuse](https://github.com/user-attachments/assets/47600772-be77-4544-a0b9-0b7ca0c5bb0b)

**Comment by Ailina0728** [comment]
因为刮削工具刮削下来都是单独创建一个文件夹并且重命名，/home/linux/symlink/电影/外语电影/666（2024）/666.mkv这种。看faq说是要保持目录层级，然后又把/home/linux剔除掉了，意思是不是软链接参数要填“/symlink/电影/外语电影”，然后有多少分类就另起一行参数填分类目录
