### ISSUE TITLE
在alist中使用了代理服务器来下载应该怎么配置呢

### ISSUE THREAD

**Issue by ZhaoJunnNie** [chen3861229/embyExternalUrl#58]
### 基础参数的配置
`const mediaMountPath = ["/mnt/alist"];`
// alist 公网地址,用于需要 alist server 代理流量的情况,按需填写
`const alistPublicAddr = "https://****.space";`
使用设备是安卓上的emby `redirect2Pan, UA: Emby/3.4.11 (Linux;Android 14) AndroidXMedia3/1.1.1`
一次运行的日志是：
2024/07/17 11:30:57 [warn] 35#35: *29 js: redirect2Pan, UA: Emby/3.4.11 (Linux;Android 14) AndroidXMedia3/1.1.1
2024/07/17 11:30:57 [warn] 35#35: *29 js: itemInfoUri: http://172.17.0.1:8096/Items?Ids=fa29ebc30576c3e8139d5e02cf533216&Fields=Path,MediaSources&Limit=1&api_key=f14304357ba141c49784b32d4405ac4c
2024/07/17 11:30:57 [warn] 35#35: *29 js: 2ms, fetchEmbyFilePath async function cost
2024/07/17 11:30:57 [warn] 35#35: *29 js: notLocal: false
2024/07/17 11:30:57 [warn] 35#35: *29 js: mount emby file path: /mnt/alist/PikPak/电影/首尔之春 (2023)/首尔之春 (2023).mkv
2024/07/17 11:30:57 [warn] 35#35: *29 js: getRouteMode: redirect
2024/07/17 11:30:57 [warn] 35#35: *29 js: mediaPathMapping: [[0,0,"/mnt/alist",""],[1,1,"https://alist.tou12138.space/d"]]
2024/07/17 11:30:57 [warn] 35#35: *29 js: strMapping replace: /mnt/alist => 
2024/07/17 11:30:57 [warn] 35#35: *29 js: mapped emby file path: /PikPak/电影/首尔之春 (2023)/首尔之春 (2023).mkv
2024/07/17 11:30:57 [warn] 35#35: *29 js: === redirect2Pan: /emby/videos/26/stream.mkv, the NJS VM is destroyed ===
2024/07/17 11:30:59 [warn] 34#34: *16 js: redirect2Pan, UA: Emby/3.4.11 (Linux;Android 14) AndroidXMedia3/1.1.1
### 1. 默认配置无修改
播放失败，没有兼容的流
### 2. 修改routeRule
`["redirect","alistRes", 2, "/PikPak/"]`,无法播放，依然是没有兼容的流
`["proxy","alistRes", 2, "/PikPak/"]`,能够播放，走的是服务器的带宽
### 3.修改mediaPathMapping
增加`[1, 1, `${alistPublicAddr}/d`]`，无法播放，依然是没有兼容的流(直接打开${alistPublicAddr}/d/PikPak/电影/首尔之春 (2023)/首尔之春 (2023).mkv是打不开的，因为alist代理服务器的设置的原因)
### 现在不知道该怎么修改才能调用到代理服务器来下载了

**Comment by chen3861229** [comment]
日志好像有点问题，正常情况下这两行之间还有很多日志信息的，最关键的 redirect to 这个缺失了，通过这行日志可以看到重定向客户端到哪个链接上了

```js
2024/07/17 11:30:57 [warn] 35#35: *29 js: mapped emby file path: /PikPak/电影/首尔之春 (2023)/首尔之春 (2023).mkv
2024/07/17 11:30:57 [warn] 35#35: *29 js: === redirect2Pan: /emby/videos/26/stream.mkv, the NJS VM is destroyed ===
```

默认没有其它配置的情况下会请求 alist 获取 raw_url 链接，这个接口返回的链接具体取决于 alist 的驱动如何配置的，如果配置了代理地址，该接口返回的就是代理地址，所以该脚本中不用在做其它配置了

emby2Alist\nginx\conf.d\config\constant-mount.js
```js
// rclone/CD2 挂载的 alist 文件配置,根据实际情况修改下面的设置
// 访问宿主机上 5244 端口的 alist 地址, 要注意 iptables 给容器放行端口
const alistAddr = "http://172.17.0.1:5244";

// alist token, 在 alist 后台查看
const alistToken = "alsit-123456";

// alist 是否启用了 sign
const alistSignEnable = false;

// alist 中设置的直链过期时间,以小时为单位
const alistSignExpireTime = 12;
```

**Comment by ZhaoJunnNie** [comment]
> 1.日志好像有点问题，正常情况下这两行之间还有很多日志信息的，最关键的 redirect to 这个缺失了，通过这行日志可以看到重定向客户端到哪个链接上了
是这样没错！我又使用了emby2Alist的docker布置了一下，默认配置就能正常播放，之前使用的是，集成版 docker 一键部署应该有点问题

**Comment by ZhaoJunnNie** [comment]
> 1.日志好像有点问题，正常情况下这两行之间还有很多日志信息的，最关键的 redirect to 这个缺失了，通过这行日志可以看到重定向客户端到哪个链接上了
> 
> ```js
> 2024/07/17 11:30:57 [warn] 35#35: *29 js: mapped emby file path: /PikPak/电影/首尔之春 (2023)/首尔之春 (2023).mkv
> 2024/07/17 11:30:57 [warn] 35#35: *29 js: === redirect2Pan: /emby/videos/26/stream.mkv, the NJS VM is destroyed ===
> ```
> 
> 2.默认没有其它配置的情况下会请求 alist 获取 raw_url 链接，这个接口返回的链接具体取决于 alist 的驱动如何配置的，如果配置了代理地址，该接口返回的就是代理地址，所以该脚本中不用在做其它配置了
> 
> emby2Alist\nginx\conf.d\config\constant-mount.js
> 
> ```js
> // rclone/CD2 挂载的 alist 文件配置,根据实际情况修改下面的设置
> // 访问宿主机上 5244 端口的 alist 地址, 要注意 iptables 给容器放行端口
> const alistAddr = "http://172.17.0.1:5244";
> 
> // alist token, 在 alist 后台查看
> const alistToken = "alsit-123456";
> 
> // alist 是否启用了 sign
> const alistSignEnable = false;
> 
> // alist 中设置的直链过期时间,以小时为单位
> const alistSignExpireTime = 12;
> ```
> 
> 3.正常情况下 routeRule 不用配置，默认取值是走直链，调试的时候可以更改
> 
> 4.理论上 mediaPathMapping [1, 1, ${alistPublicAddr}/d] 这个也不用更改，前提是 1 中能查到 alist 接口返回的 raw_url

是这样没错！我又使用了emby2Alist的docker布置了一下，默认配置就能正常播放，之前使用的是，集成版 docker 一键部署应该有点问题
