### ISSUE TITLE
mediaPathMapping添加分组支持

### ISSUE THREAD

**Issue by sjtuross** [chen3861229/embyExternalUrl#62]
你好chen，

能否类似routeRule, redirectStrmLastLinkRule, clientSelfAlistRule，给mediaPathMapping也添加分组支持？

比如某个分组中，搭配下面的规则，给不同的用户做不同的路径映射？

`["r.args.UserId", 0, "ac0d220d548f43bbb73cf9b44b2ddf0e"]`

**Comment by chen3861229** [comment]
可以添加，前段时间抽取了下通用的分组判断，改起来应该不难，不过可能需要过几天改，最近稍微有点儿忙

**Comment by chen3861229** [comment]
我这边只做了下简单的测试，r.args.UserId 这类会和路由缓存的默认规则有些关系，需要注意下

https://github.com/bpking1/embyExternalUrl/blob/main/emby2Alist/README.md#2024-08-04
