### ISSUE TITLE
软链接参数应该如何使用

### ISSUE THREAD

**Issue by Ailina0728** [chen3861229/embyExternalUrl#69]
经过一段时间折腾，数据倒腾到了Ubuntu下面，现在必要程序都是基于docker部署，没有了跨系统路径的问题。
测试过直连115文件可以重定向，**但是软链接这块还是没看懂**，希望提点一下，这个路径怎么对应的，如果symlink目录下有媒体分类的不同目录，比如 /华语电影，/新电影，/老电影...等等的该怎么办？
因为刮削工具刮削下来都是单独创建一个文件夹并且重命名，比如/home/linux/symlink/电影/外语电影/666（2024）/666.mkv这种。看faq说是要保持目录层级，指的是什么目录层级？把差集/home/linux先剔除掉了，意思是不是软链接参数要填“/symlink/电影/外语电影”，然后有多少分类就另起一行参数填分类目录，实在搞不懂了，大佬教教咋弄的，提供一份搭建的思路，还有个测试的日志截图
![issuse](https://github.com/user-attachments/assets/e9c692cd-f3c2-4215-8cd3-e936a158722b)
![日志](https://github.com/user-attachments/assets/5caa05e7-6588-4978-b495-e310011eb28e)

**Comment by chen3861229** [comment]
图例逻辑很清晰，多谢了

1.先说下简单的情况，假如图二中的媒体路径和文件名在 alist 中存在且相同，等同图一中的`软链接注意点`的 2 和 3 , 此时只需要将最后差一步的`/symlink/提着心吊着胆(2016)/提着心吊着胆(2016) - 2160p.mkv`映射为 alist 路径即可，以下规则将使用`/115/test/提着心吊着胆(2016)/提着心吊着胆(2016) - 2160p.mkv`去 alist 中查询获取并重定向，但是需要注意`/symlink/`和`/115/test/`看起来可能并不是逻辑上对应的，假如是符合通用情况的话可以不用管
```js
// 路径映射,会在 mediaMountPath 之后从上到下依次全部替换一遍,不要有重叠,注意 /mnt 会先被移除掉了
// 参数?.1: 生效规则三维数组,有时下列参数序号加一,优先级在参数2之后,需同时满足,多个组是或关系(任一匹配)
// 参数1: 0: 默认做字符串替换replace一次, 1: 前插, 2: 尾插, 3: replaceAll替换全部
// 参数2: 0: 默认只处理/开头的路径且不为 strm, 1: 只处理 strm 内部为/开头的相对路径, 2: 只处理 strm 内部为远程链接的
// 参数3: 来源, 参数4: 目标
const mediaPathMapping = [
  [0, 0, "/symlink", "/115/test"],
];
```

2.图一中强调的重点是经过了刮削的处理的软链接前后的文件名和路径层级已经完全不一致了，此时确实必须使用`symlinkRule`参数，但是这个只是用于判断指定路径开头的文件需要`进行软链接获取真实路径获取`处理规则，所以填`/home/linux/symlink/电影/外语电影` > `/home/linux/symlink/电影` > `/home/linux/symlink` 这三种是等价的，只是目录范围从小至大，此参数并不会对路径照成影响(不会进行字符串替换和映射)，当然看到了`Docker`环境，此时`/home/linux/symlink`必须和宿主机路径相同，图一中的挂载卷设置已经符合了这一点，以下为此过程涉及到的路径转换过程，
/home/linux/symlink/电影/外语电影/777.mkv
=> emby 入库的路径经过`symlinkRule`命中后会通过 nginx 查询文件系统中的路径信息拿到
/home/linux/115/test/666.mkv
=> 再经过`mediaPathMapping`路径映射参数处理，内含了`mediaMountPath=/home/linux`的处理
/115/test/666.mkv
=> 通过此路径查询 alist `/api/fs/get` 获取到`rawurl`直链后重定向响应给客户端访问

```js
// 指定需要获取符号链接真实路径的规则,优先级在 mediaMountPath 和 routeRule 之间
// 注意前提条件是此程序或容器必须挂载或具有对应目录的读取权限,否则将跳过处理,回源中转
// 此参数仅在软链接后的文件名和原始文件名不一致或路径差异较大时使用,其余情况建议用 mediaPathMapping
// 参数1: 0: startsWith(str), 1: endsWith(str), 2: includes(str), 3: match(/ain/g)
// 参数2: 匹配目标,对象为媒体服务入库的文件路径(Item.Path)
const symlinkRule = [
  [0, "/home/linux/symlink"],
];
```

**Comment by Ailina0728** [comment]
按照提示，默认`mediaMountPath=/home/linux`，然后将`symlinkRule=/home/linux/symlink`终于看到了命中软链接规则的日志，但是出现无访问权限的错误，导致跳过了软链接规则。日志如下
![权限](https://github.com/user-attachments/assets/5382242e-312a-41da-8afe-acc7748f3085)
猜测几种可能，映射给 nginx-emby（包括medialinker）容器的软链接路径错误，容器读不到；或者本地路径没有权限；nginx容器运行本身没有权限。
然后我逐个测试，保持`/home/linux:/home/linux`映射关系不变，将/symlink目录赋予了777权限，重新运行容器得出上方日志
再尝试给启动参数添加UID/GID为用户ID变量，没有效果。
本地上/home/linux的权限也属于linux组，也就是当前用户。在medialinker镜像的那边没看到有关于用户权限的变量需要设置，也无需高权限，我看别人也没有提出我这个事，就是这里也没搞定，大佬还得帮帮忙

**Comment by chen3861229** [comment]
权限相关问题的话可能有这几种可能

1.`Docker`容器没有指定权限相关`环境变量`的话，容器内部的`root`和宿主机的`root`虽然看起来名称一样，但是 id 不同，属于两个不同的用户，容器可能需要设置下，`PUID=0``PGID=0``UMASK=022`，以使用宿主机的`root`账户权限，这个是所有容器通用的一个做法，虽然 nginx:latest 的 docker hub 描述页中没看到，不过应该可行

2.假如只设置 1 无效，再可尝试下给容器特权执行模式，`--privileged=true`

3.假如 1 和 2 都无效，进一步可排查 nginx 的 conf 文件，`emby2Alist/nginx/nginx.conf`中的`user  nginx;`，可尝试改为`user root;`

补充: 以上排查方式默认都是用`root`账户，假如排查通过后觉得权限过高，可结合宿主机中软链接目录的真实用户、用户组权限精确设置非`root`以更合理的方式工作

**Comment by arthurxj** [comment]
我也觉得路径映射这部分搞得很头疼，这不换了个主机之后这个工具一直还没有布置上，用那个集成版的也没成功，日志里面也看不懂，不像之前的日志大约猜得到一点/(ㄒoㄒ)/~~

**Comment by arthurxj** [comment]
![image](https://github.com/user-attachments/assets/af3eeab0-a325-444c-b81d-8506899a1f6d)

**Comment by arthurxj** [comment]
![image](https://github.com/user-attachments/assets/2a0ce307-1032-4847-96be-d94ca23296ec)

**Comment by chen3861229** [comment]
通过截图中的情况一提到的之前工作正常，可能可以推测出 plex 入库文件的路径是`/data`开头的，可能做了卷映射等于`/vol02`的宿主机目录，由此可得情况二中，正确应该填写`const mediaMountPath = ["/data/1000-1-localhost/视频文件"];`，预期工作的路径转换是：

/data/1000-1-localhost/视频文件/a.电视剧更新/1.mkv
=> 将上述媒体服务中入库文件路径通过`路径映射/媒体挂载路径`参数替换后到 alist 中进行查询
/a.电视剧更新/1.mkv
=> 路径映射替换后的路径必须在 alist 的中存在相同层级结构的文件
=> 115 比较特殊，假如`clientSelfAlistRule`参数使用默认带有一条规则，目的是解决少数客户端的进度条拖动 bug (具体在注释中)，将响应 alist 的 /d 地址给客户端重定向，所以此时`alistPublicAddr`必须使用公网域名地址，
http(s)://youralist.com:5244/d/a.电视剧更新/1.mkv(?sign=XXX)

```js
// alist 公网地址,用于需要 alist server 代理流量的情况,按需填写
const alistPublicAddr = "http://youralist.com:5244";

// 指定客户端自己请求并获取 alist 直链的规则,代码优先级在 redirectStrmLastLinkRule 之后
// 特殊情况使用,则此处必须使用域名且公网畅通,用不着请保持默认
// 参数1: 分组名,组内为与关系(全部匹配),多个组和没有分组的规则是或关系(任一匹配),然后下面参数序号-1
// 参数2: 匹配类型或来源(字符串参数类型),优先级高"filePath": 文件路径(Item.Path),默认为"alistRes": alist 返回的链接 raw_url
// ,有分组时不可省略填写,可为表达式
// 参数3: 0: startsWith(str), 1: endsWith(str), 2: includes(str), 3: match(/ain/g)
// 参数4: 匹配目标,为数组的多个参数时,数组内为或关系(任一匹配)
// 参数5: 指定转发给客户端的 alist 的 host 前缀,兼容 sign 参数
const clientSelfAlistRule = [
  // "Emby for iOS"和"Infuse"对于 115 的进度条拖动依赖于此
  // 如果 nginx 为 https,则此 alist 也必须 https,浏览器行为客户端会阻止非 https 请求
  [2, strHead["115"], alistPublicAddr],
  // [2, strHead.ali, alistPublicAddr],
  // 优先使用 filePath,可省去一次查询 alist,如驱动为 alias,则应使用 alistRes
  // ["115-local", "filePath", 0, "/mnt/115", alistPublicAddr],
  // ["115-local", "r.args.X-Emby-Client", 0, strHead.xEmbyClients.seekBug], // 链接入参,客户端类型
  // ["115-alist", "alistRes", 2, strHead["115"], alistPublicAddr],
  // ["115-alist", "r.args.X-Emby-Client", 0, strHead.xEmbyClients.seekBug],
];
```
假设不涉及`"Emby for iOS"和"Infuse"对于 115 的进度条拖动 bug`，可以注释`clientSelfAlistRule`中的`[2, strHead["115"], alistPublicAddr],`，此时就需要 alist 的公网域名了`alistPublicAddr`，将响应网盘商公网直链给客户端重定向访问
https://xxx.115.com/xxxx

**Comment by Ailina0728** [comment]
这个medialinker也能像官方镜像一样映射配置文件的吗，还真不知道，回头再试下。非常感谢，耽误你好久都有点不好意思了

**Comment by Ailina0728** [comment]
还有个小事，medialinker镜像使用的是alpine镜像，默认Etc/UTC时区且不能通过TZ=Asia/Shanghai变量或者映射/etc/localtime来同步宿主机时区，dockerfile中添加
```
RUN apk add tzdata && cp /usr/share/zoneinfo/Asia/Shanghai /etc/localtime \
    && echo "Asia/Shanghai" > /etc/timezone \
    && apk del tzdata
```
构建才能实现日志时间同步，不影响啥，就是给有强迫症的提个醒，免得折腾

**Comment by thsrite** [comment]
感谢提醒，新版镜像已修复，另外最后不能删除tzdata，不然也不生效
---- 回复的原邮件 ----
***@***.***>发送日期2024年9月12日 ***@***.***>***@***.***>,
***@***.***>主题Re: [chen3861229/embyExternalUrl] 软链接参数应该如何使用 (Issue #69)
还有个小事，medialinker镜像使用的是alpine镜像，默认Etc/UTC时区且不能通过TZ=Asia/Shanghai变量或者映射/etc/localtime来同步宿主机时区，dockerfile中添加
RUN apk add tzdata && cp /usr/share/zoneinfo/Asia/Shanghai /etc/localtime \ && echo "Asia/Shanghai" > /etc/timezone \ && apk del tzdata 
构建才能实现日志时间同步，不影响啥，就是给有强迫症的提个醒，免得折腾
