### ISSUE TITLE
大佬，关于使用直连后听歌和听电子书报错的问题

### ISSUE THREAD

**Issue by yy306525121** [chen3861229/embyExternalUrl#70]
现在发现使用直连后通过plexamp听歌没问题，第三方听歌报500，电子书也是500（只测试了prologue，不知道还有没有其他客户端），由于能力有限，只是修改了plex.js文件中的redirect2Pan方法中的如下代码，不知道大佬有没有更好的处理方法。
![image](https://github.com/user-attachments/assets/05ebae98-68a8-41f7-93a3-be2c3c9a5979)

**Comment by chen3861229** [comment]
没有啥太好的办法，plex 的 api 比较封闭，盲猜第三方客户端报错对比 plex 官方没问题的话应该是脚本中 PartInfo 那块的文件路径缓存没有触发，第三方客户端可能也是缺少 api 文档导致没有模拟 plex 官方端进行一些额外接口的调用，图中的代码是之前没有做失败回退修改之前的，修复方式是没太大问题的，因为目前也是这样修复的
https://github.com/chen3861229/embyExternalUrl/blob/48802dd8fd5479111c3a7adbb728a8e7d4d9429a/plex2Alist/nginx/conf.d/plex.js#L70

**Comment by yy306525121** [comment]
> 没有啥太好的办法，plex 的 api 比较封闭，盲猜第三方客户端报错对比 plex 官方没问题的话应该是脚本中 PartInfo 那块的文件路径缓存没有触发，第三方客户端可能也是缺少 api 文档导致没有模拟 plex 官方端进行一些额外接口的调用，图中的代码是之前没有做失败回退修改之前的，修复方式是没太大问题的，因为目前也是这样修复的
> 
> https://github.com/chen3861229/embyExternalUrl/blob/48802dd8fd5479111c3a7adbb728a8e7d4d9429a/plex2Alist/nginx/conf.d/plex.js#L72

好嘞， 那就先这样用着
