### ISSUE TITLE
emby2alist配合docker版本的nginx proxy manager使用方法

### ISSUE THREAD

**Issue by LGuangming** [chen3861229/embyExternalUrl#73]
想问一下，我目前VPS上已经部署了docker版本的nginx proxy manager，并且有一些自己的反代配置，不是特别想部署新的nginx。现在想使用emby2alist这个项目，怎么可以直接搭配使用呢。

**Comment by chen3861229** [comment]
1.看了下，这个 WebUI 有些配置无法通过图形化界面添加，还是需要命令编辑一些配置文件，且最好按它的规范目录放置，这样的话其实有些偏离 WebUI 简便的用途了，假如只是需要使用它的证书续签，可以将它申请下的证书 docker 映射/物理机软链接文件到 emby2alist 指定目录下就行了

2.nginx 的空载内存占用大约只有 15 MB 左右，加上 njs 脚本，日常占用大约在 30 MB 左右，njs 的这 15 MB 无法省略，假如实在不想多部署一个 nginx 多占用 15 MB 内存，可以按照以下核查一下

2.1 通用查看 nginx 携带的默认已编译模块，
以下是 nginx proxy manager 带的
```
[root@docker-2dc5487eea5f:/usr/lib/nginx/modules]# ls
ngx_http_geoip2_module.so
ngx_stream_geoip2_module.so
```
以下是官方编译版本带的
```
root@nginx-emby2alist:/usr/lib/nginx/modules# ls                                
ngx_http_geoip_module-debug.so         ngx_http_xslt_filter_module-debug.so     
ngx_http_geoip_module.so               ngx_http_xslt_filter_module.so           
ngx_http_image_filter_module-debug.so  ngx_stream_geoip_module-debug.so         
ngx_http_image_filter_module.so        ngx_stream_geoip_module.so               
ngx_http_js_module-debug.so            ngx_stream_js_module-debug.so            
ngx_http_js_module.so                  ngx_stream_js_module.so 
```
**缺少了**，`ngx_http_js_module.so`，需要按运行机器的 CPU 架构去官方 nginx docker 中提取一个或自行编译一个，放置在`/usr/lib/nginx/modules`下

3.按照 nginx proxy manager 的目录规范填写加载`NJS`模块

以下是 nginx proxy manager 容器下，/etc/nginx/nginx.conf 内容
```
# run nginx in foreground
daemon off;
pid /run/nginx/nginx.pid;
user npm;

# Set number of worker processes automatically based on number of CPU cores.
worker_processes auto;

# Enables the use of JIT for regular expressions to speed-up their processing.
pcre_jit on;

error_log /data/logs/fallback_error.log warn;

# Includes files with directives to load dynamic modules.
include /etc/nginx/modules/*.conf;

# Custom
include /data/nginx/custom/root_top[.]conf;

events {
    include /data/nginx/custom/events[.]conf;
}

http {
    include                       /etc/nginx/mime.types;
    default_type                  application/octet-stream;
    sendfile                      on;
    server_tokens                 off;
    tcp_nopush                    on;
    tcp_nodelay                   on;
    client_body_temp_path         /tmp/nginx/body 1 2;
    keepalive_timeout             90s;
    proxy_connect_timeout         90s;
    proxy_send_timeout            90s;
    proxy_read_timeout            90s;
    ssl_prefer_server_ciphers     on;
    gzip                          on;
    proxy_ignore_client_abort     off;
    client_max_body_size          2000m;
    server_names_hash_bucket_size 1024;
    proxy_http_version            1.1;
    proxy_set_header              X-Forwarded-Scheme $scheme;
    proxy_set_header              X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header              Accept-Encoding "";
    proxy_cache                   off;
    proxy_cache_path              /var/lib/nginx/cache/public  levels=1:2 keys_zone=public-cache:30m max_size=192m;
    proxy_cache_path              /var/lib/nginx/cache/private levels=1:2 keys_zone=private-cache:5m max_size=1024m;

    # Log format and fallback log file
    include /etc/nginx/conf.d/include/log.conf;

    # Dynamically generated resolvers file
    include /etc/nginx/conf.d/include/resolvers.conf;

    # Default upstream scheme
    map $host $forward_scheme {
        default http;
    }

    # Real IP Determination

    # Local subnets:
    set_real_ip_from 10.0.0.0/8;
    set_real_ip_from 172.16.0.0/12; # Includes Docker subnet
    set_real_ip_from 192.168.0.0/16;
    # NPM generated CDN ip ranges:
    include conf.d/include/ip_ranges.conf;
    # always put the following 2 lines after ip subnets:
    real_ip_header X-Real-IP;
    real_ip_recursive on;

    # Custom
    include /data/nginx/custom/http_top[.]conf;

    # Files generated by NPM
    include /etc/nginx/conf.d/*.conf;
    include /data/nginx/default_host/*.conf;
    include /data/nginx/proxy_host/*.conf;
    include /data/nginx/redirection_host/*.conf;
    include /data/nginx/dead_host/*.conf;
    include /data/nginx/temp/*.conf;

    # Custom
    include /data/nginx/custom/http[.]conf;
}

stream {
    # Files generated by NPM
    include /data/nginx/stream/*.conf;

    # Custom
    include /data/nginx/custom/stream[.]conf;
}

# Custom
include /data/nginx/custom/root[.]conf;
```

3.1 由(# Custom)`include /data/nginx/custom/root_top[.]conf;`可知，需要在`/data/nginx/custom`下新建`root_top.conf`文件以客制化填写 nginx 根层级配置项，非 http 块下，**此文件对应 emby2alist 的 emby2Alist/nginx/nginx.conf **, 填写内容
```
load_module modules/ngx_http_js_module.so;
#load_module modules/ngx_stream_js_module.so; # don't need this
```
不要重新引入`include /etc/nginx/conf.d/*.conf;`，上面的 Nginx Proxy Manager 默认已经引入了`include /data/nginx/proxy_host/*.conf;`

4.在  Nginx Proxy Manager WebUI 处随意创建一个`Proxy Hosts`，`Status`为绿色` Online`此文件会生成在对应的`/data/nginx/proxy_host`目录下，**此文件对应 emby2alist 的 emby2Alist/nginx/conf.d/emby.conf **

5.以下为默认的`Proxy Hosts`默认生成的配置文件 1.conf
```
# ------------------------------------------------------------
# xxx
# ------------------------------------------------------------

map $scheme $hsts_header {
    https   "max-age=63072000; preload";
}

server {
  set $forward_scheme http;
  set $server         "192.168.31.200";
  set $port           8098;

  listen 80;
  listen [::]:80;

  server_name xxx;

  access_log /data/logs/proxy-host-1_access.log proxy;
  error_log /data/logs/proxy-host-1_error.log warn;

  location / {
    
    proxy_set_header Host $host;
    proxy_set_header X-Forwarded-Scheme $scheme;
    proxy_set_header X-Forwarded-Proto  $scheme;
    proxy_set_header X-Forwarded-For    $remote_addr;
    proxy_set_header X-Real-IP      $remote_addr;

    set $proxy_forward_scheme http;
    set $proxy_server         "192.168.31.200";
    set $proxy_port           8098;

    proxy_pass       $proxy_forward_scheme://$proxy_server:$proxy_port;
  }

  # Custom
  include /data/nginx/custom/server_proxy[.]conf;
}
```

5.1 假如需要手动图形化配置，Edit Proxy Host =>  Custom locations 填写较为繁琐，参照`emby2Alist/nginx/conf.d/emby.conf`中的一个个添加，并且摸索`emby.conf`中非`locations`层级的其余配置该如何在 Nginx Proxy Manager WebUI 中填写，WebUI 用得不多，我这边也不熟

5.2 将`emby2Alist/nginx/conf.d`下的所有文件复制到`/data/nginx/proxy_host`下，再结合`/data/nginx/proxy_host/1.conf`已有文件，再参照修改`emby2Alist/nginx/conf.d/emby.conf`文件以符合`Nginx Proxy Manager`的规范日志存储位置和一些其他配置项，
然后改好`emby2Alist/nginx/conf.d/emby.conf`记得删除`/data/nginx/proxy_host/1.conf`文件(删除前改名备份`1.conf.bak`)，再重载 nginx 配置文件应该能生效了，终端`nginx -s reload`或重启`Nginx Proxy Manager`，这种方式应该是不兼容`Nginx Proxy Manager`图形化编辑的方式了，后续图形化编辑`proxy_host`需要注意下它改了哪段的配置内容

https://github.com/bpking1/embyExternalUrl/issues/404

**Comment by LGuangming** [comment]
> 1.看了下，这个 WebUI 有些配置无法通过图形化界面添加，还是需要命令编辑一些配置文件，且最好按它的规范目录放置，这样的话其实有些偏离 WebUI 简便的用途了，假如只是需要使用它的证书续签，可以将它申请下的证书 docker 映射/物理机软链接文件到 emby2alist 指定目录下就行了
> 
> 2.nginx 的空载内存占用大约只有 15 MB 左右，加上 njs 脚本，日常占用大约在 30 MB 左右，njs 的这 15 MB 无法省略，假如实在不想多部署一个 nginx 多占用 15 MB 内存，可以按照以下核查一下
> 
> 2.1 通用查看 nginx 携带的默认已编译模块， 以下是 nginx proxy manager 带的
> 
> ```
> [root@docker-2dc5487eea5f:/usr/lib/nginx/modules]# ls
> ngx_http_geoip2_module.so
> ngx_stream_geoip2_module.so
> ```
> 
> 以下是官方编译版本带的
> 
> ```
> root@nginx-emby2alist:/usr/lib/nginx/modules# ls                                
> ngx_http_geoip_module-debug.so         ngx_http_xslt_filter_module-debug.so     
> ngx_http_geoip_module.so               ngx_http_xslt_filter_module.so           
> ngx_http_image_filter_module-debug.so  ngx_stream_geoip_module-debug.so         
> ngx_http_image_filter_module.so        ngx_stream_geoip_module.so               
> ngx_http_js_module-debug.so            ngx_stream_js_module-debug.so            
> ngx_http_js_module.so                  ngx_stream_js_module.so 
> ```
> 
> **缺少了**，`ngx_http_js_module.so`，需要按运行机器的 CPU 架构去官方 nginx docker 中提取一个或自行编译一个，放置在`/usr/lib/nginx/modules`下
> 
> 3.按照 nginx proxy manager 的目录规范填写加载`NJS`模块
> 
> 以下是 nginx proxy manager 容器下，/etc/nginx/nginx.conf 内容
> 
> ```
> # run nginx in foreground
> daemon off;
> pid /run/nginx/nginx.pid;
> user npm;
> 
> # Set number of worker processes automatically based on number of CPU cores.
> worker_processes auto;
> 
> # Enables the use of JIT for regular expressions to speed-up their processing.
> pcre_jit on;
> 
> error_log /data/logs/fallback_error.log warn;
> 
> # Includes files with directives to load dynamic modules.
> include /etc/nginx/modules/*.conf;
> 
> # Custom
> include /data/nginx/custom/root_top[.]conf;
> 
> events {
>     include /data/nginx/custom/events[.]conf;
> }
> 
> http {
>     include                       /etc/nginx/mime.types;
>     default_type                  application/octet-stream;
>     sendfile                      on;
>     server_tokens                 off;
>     tcp_nopush                    on;
>     tcp_nodelay                   on;
>     client_body_temp_path         /tmp/nginx/body 1 2;
>     keepalive_timeout             90s;
>     proxy_connect_timeout         90s;
>     proxy_send_timeout            90s;
>     proxy_read_timeout            90s;
>     ssl_prefer_server_ciphers     on;
>     gzip                          on;
>     proxy_ignore_client_abort     off;
>     client_max_body_size          2000m;
>     server_names_hash_bucket_size 1024;
>     proxy_http_version            1.1;
>     proxy_set_header              X-Forwarded-Scheme $scheme;
>     proxy_set_header              X-Forwarded-For $proxy_add_x_forwarded_for;
>     proxy_set_header              Accept-Encoding "";
>     proxy_cache                   off;
>     proxy_cache_path              /var/lib/nginx/cache/public  levels=1:2 keys_zone=public-cache:30m max_size=192m;
>     proxy_cache_path              /var/lib/nginx/cache/private levels=1:2 keys_zone=private-cache:5m max_size=1024m;
> 
>     # Log format and fallback log file
>     include /etc/nginx/conf.d/include/log.conf;
> 
>     # Dynamically generated resolvers file
>     include /etc/nginx/conf.d/include/resolvers.conf;
> 
>     # Default upstream scheme
>     map $host $forward_scheme {
>         default http;
>     }
> 
>     # Real IP Determination
> 
>     # Local subnets:
>     set_real_ip_from 10.0.0.0/8;
>     set_real_ip_from 172.16.0.0/12; # Includes Docker subnet
>     set_real_ip_from 192.168.0.0/16;
>     # NPM generated CDN ip ranges:
>     include conf.d/include/ip_ranges.conf;
>     # always put the following 2 lines after ip subnets:
>     real_ip_header X-Real-IP;
>     real_ip_recursive on;
> 
>     # Custom
>     include /data/nginx/custom/http_top[.]conf;
> 
>     # Files generated by NPM
>     include /etc/nginx/conf.d/*.conf;
>     include /data/nginx/default_host/*.conf;
>     include /data/nginx/proxy_host/*.conf;
>     include /data/nginx/redirection_host/*.conf;
>     include /data/nginx/dead_host/*.conf;
>     include /data/nginx/temp/*.conf;
> 
>     # Custom
>     include /data/nginx/custom/http[.]conf;
> }
> 
> stream {
>     # Files generated by NPM
>     include /data/nginx/stream/*.conf;
> 
>     # Custom
>     include /data/nginx/custom/stream[.]conf;
> }
> 
> # Custom
> include /data/nginx/custom/root[.]conf;
> ```
> 
> 3.1 由(# Custom)`include /data/nginx/custom/root_top[.]conf;`可知，需要在`/data/nginx/custom`下新建`root_top.conf`文件以客制化填写 nginx 根层级配置项，非 http 块下，**此文件对应 emby2alist 的 emby2Alist/nginx/nginx.conf **, 填写内容
> 
> ```
> load_module modules/ngx_http_js_module.so;
> #load_module modules/ngx_stream_js_module.so; # don't need this
> ```
> 
> 不要重新引入`include /etc/nginx/conf.d/*.conf;`，上面的 Nginx Proxy Manager 默认已经引入了`include /data/nginx/proxy_host/*.conf;`
> 
> 4.在 Nginx Proxy Manager WebUI 处随意创建一个`Proxy Hosts`，`Status`为绿色` Online`此文件会生成在对应的`/data/nginx/proxy_host`目录下，**此文件对应 emby2alist 的 emby2Alist/nginx/conf.d/emby.conf **
> 
> 5.以下为默认的`Proxy Hosts`默认生成的配置文件 1.conf
> 
> ```
> # ------------------------------------------------------------
> # xxx
> # ------------------------------------------------------------
> 
> map $scheme $hsts_header {
>     https   "max-age=63072000; preload";
> }
> 
> server {
>   set $forward_scheme http;
>   set $server         "192.168.31.200";
>   set $port           8098;
> 
>   listen 80;
>   listen [::]:80;
> 
>   server_name xxx;
> 
>   access_log /data/logs/proxy-host-1_access.log proxy;
>   error_log /data/logs/proxy-host-1_error.log warn;
> 
>   location / {
>     
>     proxy_set_header Host $host;
>     proxy_set_header X-Forwarded-Scheme $scheme;
>     proxy_set_header X-Forwarded-Proto  $scheme;
>     proxy_set_header X-Forwarded-For    $remote_addr;
>     proxy_set_header X-Real-IP      $remote_addr;
> 
>     set $proxy_forward_scheme http;
>     set $proxy_server         "192.168.31.200";
>     set $proxy_port           8098;
> 
>     proxy_pass       $proxy_forward_scheme://$proxy_server:$proxy_port;
>   }
> 
>   # Custom
>   include /data/nginx/custom/server_proxy[.]conf;
> }
> ```
> 
> 5.1 假如需要手动图形化配置，Edit Proxy Host => Custom locations 填写较为繁琐，参照`emby2Alist/nginx/conf.d/emby.conf`中的一个个添加，并且摸索`emby.conf`中非`locations`层级的其余配置该如何在 Nginx Proxy Manager WebUI 中填写，WebUI 用得不多，我这边也不熟
> 
> 5.2 将`emby2Alist/nginx/conf.d`下的所有文件复制到`/data/nginx/proxy_host`下，再结合`/data/nginx/proxy_host/1.conf`已有文件，再参照修改`emby2Alist/nginx/conf.d/emby.conf`文件以符合`Nginx Proxy Manager`的规范日志存储位置和一些其他配置项， 然后改好`emby2Alist/nginx/conf.d/emby.conf`记得删除`/data/nginx/proxy_host/1.conf`文件(删除前改名备份`1.conf.bak`)，再重载 nginx 配置文件应该能生效了，终端`nginx -s reload`或重启`Nginx Proxy Manager`，这种方式应该是不兼容`Nginx Proxy Manager`图形化编辑的方式了，后续图形化编辑`proxy_host`需要注意下它改了哪段的配置内容
> 
> [bpking1#404](https://github.com/bpking1/embyExternalUrl/issues/404)

您这真是手把手教啊，非常感谢！我会去试试的，实在不行就放弃NPM的UI了，谢谢！

**Comment by PanJX02** [comment]
我的vps已经装了宝塔的nginx，再装这个会不会影响原来的？

**Comment by MetaSquared** [comment]
> 1.看了下，这个 WebUI 有些配置无法通过图形化界面添加，还是需要命令编辑一些配置文件，且最好按它的规范目录放置，这样的话其实有些偏离 WebUI 简便的用途了，假如只是需要使用它的证书续签，可以将它申请下的证书 docker 映射/物理机软链接文件到 emby2alist 指定目录下就行了
> 
> 2.nginx 的空载内存占用大约只有 15 MB 左右，加上 njs 脚本，日常占用大约在 30 MB 左右，njs 的这 15 MB 无法省略，假如实在不想多部署一个 nginx 多占用 15 MB 内存，可以按照以下核查一下
> 
> 2.1 通用查看 nginx 携带的默认已编译模块， 以下是 nginx proxy manager 带的
> 
> ```
> [root@docker-2dc5487eea5f:/usr/lib/nginx/modules]# ls
> ngx_http_geoip2_module.so
> ngx_stream_geoip2_module.so
> ```
> 
> 以下是官方编译版本带的
> 
> ```
> root@nginx-emby2alist:/usr/lib/nginx/modules# ls                                
> ngx_http_geoip_module-debug.so         ngx_http_xslt_filter_module-debug.so     
> ngx_http_geoip_module.so               ngx_http_xslt_filter_module.so           
> ngx_http_image_filter_module-debug.so  ngx_stream_geoip_module-debug.so         
> ngx_http_image_filter_module.so        ngx_stream_geoip_module.so               
> ngx_http_js_module-debug.so            ngx_stream_js_module-debug.so            
> ngx_http_js_module.so                  ngx_stream_js_module.so 
> ```
> 
> **缺少了**，`ngx_http_js_module.so`，需要按运行机器的 CPU 架构去官方 nginx docker 中提取一个或自行编译一个，放置在`/usr/lib/nginx/modules`下
> 
> 3.按照 nginx proxy manager 的目录规范填写加载`NJS`模块
> 
> 以下是 nginx proxy manager 容器下，/etc/nginx/nginx.conf 内容
> 
> ```
> # run nginx in foreground
> daemon off;
> pid /run/nginx/nginx.pid;
> user npm;
> 
> # Set number of worker processes automatically based on number of CPU cores.
> worker_processes auto;
> 
> # Enables the use of JIT for regular expressions to speed-up their processing.
> pcre_jit on;
> 
> error_log /data/logs/fallback_error.log warn;
> 
> # Includes files with directives to load dynamic modules.
> include /etc/nginx/modules/*.conf;
> 
> # Custom
> include /data/nginx/custom/root_top[.]conf;
> 
> events {
>     include /data/nginx/custom/events[.]conf;
> }
> 
> http {
>     include                       /etc/nginx/mime.types;
>     default_type                  application/octet-stream;
>     sendfile                      on;
>     server_tokens                 off;
>     tcp_nopush                    on;
>     tcp_nodelay                   on;
>     client_body_temp_path         /tmp/nginx/body 1 2;
>     keepalive_timeout             90s;
>     proxy_connect_timeout         90s;
>     proxy_send_timeout            90s;
>     proxy_read_timeout            90s;
>     ssl_prefer_server_ciphers     on;
>     gzip                          on;
>     proxy_ignore_client_abort     off;
>     client_max_body_size          2000m;
>     server_names_hash_bucket_size 1024;
>     proxy_http_version            1.1;
>     proxy_set_header              X-Forwarded-Scheme $scheme;
>     proxy_set_header              X-Forwarded-For $proxy_add_x_forwarded_for;
>     proxy_set_header              Accept-Encoding "";
>     proxy_cache                   off;
>     proxy_cache_path              /var/lib/nginx/cache/public  levels=1:2 keys_zone=public-cache:30m max_size=192m;
>     proxy_cache_path              /var/lib/nginx/cache/private levels=1:2 keys_zone=private-cache:5m max_size=1024m;
> 
>     # Log format and fallback log file
>     include /etc/nginx/conf.d/include/log.conf;
> 
>     # Dynamically generated resolvers file
>     include /etc/nginx/conf.d/include/resolvers.conf;
> 
>     # Default upstream scheme
>     map $host $forward_scheme {
>         default http;
>     }
> 
>     # Real IP Determination
> 
>     # Local subnets:
>     set_real_ip_from 10.0.0.0/8;
>     set_real_ip_from 172.16.0.0/12; # Includes Docker subnet
>     set_real_ip_from 192.168.0.0/16;
>     # NPM generated CDN ip ranges:
>     include conf.d/include/ip_ranges.conf;
>     # always put the following 2 lines after ip subnets:
>     real_ip_header X-Real-IP;
>     real_ip_recursive on;
> 
>     # Custom
>     include /data/nginx/custom/http_top[.]conf;
> 
>     # Files generated by NPM
>     include /etc/nginx/conf.d/*.conf;
>     include /data/nginx/default_host/*.conf;
>     include /data/nginx/proxy_host/*.conf;
>     include /data/nginx/redirection_host/*.conf;
>     include /data/nginx/dead_host/*.conf;
>     include /data/nginx/temp/*.conf;
> 
>     # Custom
>     include /data/nginx/custom/http[.]conf;
> }
> 
> stream {
>     # Files generated by NPM
>     include /data/nginx/stream/*.conf;
> 
>     # Custom
>     include /data/nginx/custom/stream[.]conf;
> }
> 
> # Custom
> include /data/nginx/custom/root[.]conf;
> ```
> 
> 3.1 由(# Custom)`include /data/nginx/custom/root_top[.]conf;`可知，需要在`/data/nginx/custom`下新建`root_top.conf`文件以客制化填写 nginx 根层级配置项，非 http 块下，**此文件对应 emby2alist 的 emby2Alist/nginx/nginx.conf **, 填写内容
> 
> ```
> load_module modules/ngx_http_js_module.so;
> #load_module modules/ngx_stream_js_module.so; # don't need this
> ```
> 
> 不要重新引入`include /etc/nginx/conf.d/*.conf;`，上面的 Nginx Proxy Manager 默认已经引入了`include /data/nginx/proxy_host/*.conf;`
> 
> 4.在 Nginx Proxy Manager WebUI 处随意创建一个`Proxy Hosts`，`Status`为绿色` Online`此文件会生成在对应的`/data/nginx/proxy_host`目录下，**此文件对应 emby2alist 的 emby2Alist/nginx/conf.d/emby.conf **
> 
> 5.以下为默认的`Proxy Hosts`默认生成的配置文件 1.conf
> 
> ```
> # ------------------------------------------------------------
> # xxx
> # ------------------------------------------------------------
> 
> map $scheme $hsts_header {
>     https   "max-age=63072000; preload";
> }
> 
> server {
>   set $forward_scheme http;
>   set $server         "192.168.31.200";
>   set $port           8098;
> 
>   listen 80;
>   listen [::]:80;
> 
>   server_name xxx;
> 
>   access_log /data/logs/proxy-host-1_access.log proxy;
>   error_log /data/logs/proxy-host-1_error.log warn;
> 
>   location / {
>     
>     proxy_set_header Host $host;
>     proxy_set_header X-Forwarded-Scheme $scheme;
>     proxy_set_header X-Forwarded-Proto  $scheme;
>     proxy_set_header X-Forwarded-For    $remote_addr;
>     proxy_set_header X-Real-IP      $remote_addr;
> 
>     set $proxy_forward_scheme http;
>     set $proxy_server         "192.168.31.200";
>     set $proxy_port           8098;
> 
>     proxy_pass       $proxy_forward_scheme://$proxy_server:$proxy_port;
>   }
> 
>   # Custom
>   include /data/nginx/custom/server_proxy[.]conf;
> }
> ```
> 
> 5.1 假如需要手动图形化配置，Edit Proxy Host => Custom locations 填写较为繁琐，参照`emby2Alist/nginx/conf.d/emby.conf`中的一个个添加，并且摸索`emby.conf`中非`locations`层级的其余配置该如何在 Nginx Proxy Manager WebUI 中填写，WebUI 用得不多，我这边也不熟
> 
> 5.2 将`emby2Alist/nginx/conf.d`下的所有文件复制到`/data/nginx/proxy_host`下，再结合`/data/nginx/proxy_host/1.conf`已有文件，再参照修改`emby2Alist/nginx/conf.d/emby.conf`文件以符合`Nginx Proxy Manager`的规范日志存储位置和一些其他配置项， 然后改好`emby2Alist/nginx/conf.d/emby.conf`记得删除`/data/nginx/proxy_host/1.conf`文件(删除前改名备份`1.conf.bak`)，再重载 nginx 配置文件应该能生效了，终端`nginx -s reload`或重启`Nginx Proxy Manager`，这种方式应该是不兼容`Nginx Proxy Manager`图形化编辑的方式了，后续图形化编辑`proxy_host`需要注意下它改了哪段的配置内容
> 
> [bpking1#404](https://github.com/bpking1/embyExternalUrl/issues/404)

大佬，请问能不能完全脱离nginx proxy manager这个应用的组织架构，直接在本地nginx上部署njs + emby2alist呢？

**Comment by chen3861229** [comment]
理解错了哦，原本正常就是【本地nginx上部署njs + emby2alist】的，运用【nginx proxy manager】只是可选的复用已有组件

**Comment by MetaSquared** [comment]
> 理解错了哦，原本正常就是【本地nginx上部署njs + emby2alist】的，运用【nginx proxy manager】只是可选的复用已有组件

谢谢大佬热心解答！
