### ISSUE TITLE
docker-compose启动报警告

### ISSUE THREAD

**Issue by anyingxiuluo** [chen3861229/embyExternalUrl#75]
emby2alist用docker-compose启动报警告WARNING: Some services (service.nginx-emby) use the 'deploy' key, which will be ignored. Compose does not support 'deploy' configuration - use `docker stack deploy` to deploy to a swarm.

**Comment by chen3861229** [comment]
好的，多谢提醒，确实依赖 Docker Swarm 模式，稍微有些局限，稍后将注释这段为可选配置

**Comment by anyingxiuluo** [comment]
大佬,最近经常卡在这一步导致播放失败是什么原因,网盘是115,播放软件是fileball
![微信截图_20241117095624](https://github.com/user-attachments/assets/2df264b2-1693-4c8c-b2e5-717210753eda)

**Comment by anyingxiuluo** [comment]
播放是用国内公网访问的,emby和emby2alist是在新加坡甲骨文,是要给emby套https证书吗

**Comment by chen3861229** [comment]
是的，虽然网络细节有点不太一样，不过可以尝试一下，目的是连接到 emby 套证书，实际配置是端口入口处套证书，可以在 nginx 上配或给 nginx 套其他的图形化反代上配置证书也行，以下是 nginx 上配置证书的简单方法

1.将申请的证书和密钥文件放置在`emby2Alist\nginx\conf.d\cert`下
2.更改`emby2Alist\nginx\conf.d\emby.conf`中的第 44 行左右
```js
## Include the http and https configs, better don't use same port
# include /etc/nginx/conf.d/includes/http.conf;
include /etc/nginx/conf.d/includes/https.conf;
```
3.确保`emby2Alist\nginx\conf.d\includes\https.conf`中`ssl_certificate`和`ssl_certificate_key`路径正确
4. 重启 nginx 或终端运行，`nginx -s reload`即可
