### ISSUE TITLE
代理后没有播放记录的问题

### ISSUE THREAD

**Issue by tianshan2024** [chen3861229/embyExternalUrl#76]
你好，使用strm然后在emby直接播放，emby上能有播放记录（就是这个电视剧播放到哪一集几分钟）
如果使用代理直连后emby网页无法播放，在infuse可以直连播放，但是没有播放记录

麻烦大佬给指导一下哪里有问题？谢谢！

**Comment by tianshan2024** [comment]
配置文件只做了这些修改
// 这里默认 emby/jellyfin 的地址是宿主机,要注意 iptables 给容器放行端口
const embyHost = "http://192.168.110.65:8096";

// 挂载工具 rclone/CD2 多出来的挂载目录, 例如将 od,gd 挂载到 /mnt 目录下: /mnt/onedrive /mnt/gd ,那么这里就填写 /mnt
// 通常配置一个远程挂载根路径就够了,默认非此路径开头文件将转给原始 emby 处理,不用重复填写至 disableRedirectRule
// 如果没有挂载,全部使用 strm 文件,此项填[""],必须要是数组
const mediaMountPath = ["/media"];

// emby/jellyfin api key, 在 emby/jellyfin 后台设置
const embyApiKey = "720f6ea3ad8945db888888888*****";

// 访问宿主机上 5244 端口的 alist 地址, 要注意 iptables 给容器放行端口
const alistAddr = "http://192.168.110.65:5244";

// alist token, 在 alist 后台查看
const alistToken = "alist-66952dcf-9e23-47ad-9208-0e*********";

// alist 是否启用了 sign
const alistSignEnable = false;

// alist 中设置的直链过期时间,以小时为单位
const alistSignExpireTime = 12;

**Comment by tianshan2024** [comment]
http://192.168.110.65:5244/d/115/%E7%94%B5%E8%A7%86%E5%89%A7/%E5%8C%BB%E9%A6%86%E7%AC%91%E4%BC%A0%20%E7%AC%AC%E4%BA%8C%E5%AD%A3/%E5%8C%BB%E9%A6%86%E7%AC%91%E4%BC%A0S02E01.mp4?sign=uctHM9CtZWIY8zE6f6zr08GR_U5LiUMToYsqjKPsZQc=:0

strm文件是这样的，strm文件所在的目录挂载到了/media

**Comment by tianshan2024** [comment]
好像解决了，alist关闭全局sign可以了

**Comment by chen3861229** [comment]
假如在意 alist 安全的话，最好的是配置下，`emby2Alist\nginx\conf.d\config\constant-mount.js`中的
```js
// alist 是否启用了 sign
const alistSignEnable = true;

// alist 中设置的直链过期时间,以小时为单位
const alistSignExpireTime = 0; // 这个整数具体查看 alist 设置 => 全局 => 直链有效期
```
这样会在响应的 alist 链接上动态加上`sign`签名参数

**Comment by tianshan2024** [comment]
大佬，开启sign之后，现在8096页面可以播放，也有播放记录
但是8091页面直接打不开，使用infuse链接8091可以播放，但是没有播放记录，请大佬指导一下，哪里的问题
![8091](https://github.com/user-attachments/assets/8973c3ac-4417-4295-9e2c-8f4bcaf5d0f8)

**Comment by tianshan2024** [comment]
// 这个总配置单体文件只是备份,生效需要放置在 conf.d 下,且重命名为 constant.js
// 如果使用这个全量总配置文件,忽略 config 下的所有文件,以这个文件为准

// 全量配置,媒体库混合,本地文件 + rclone/CD2 挂载的 alist 文件 + strm文件 + 软链接(路径和文件名不一致)
// export constant allocation

// 必填项,根据实际情况修改下面的设置

// 这里默认 emby/jellyfin 的地址是宿主机,要注意 iptables 给容器放行端口
const embyHost = "http://192.168.110.65:8096";

// 挂载工具 rclone/CD2 多出来的挂载目录, 例如将 od,gd 挂载到 /mnt 目录下: /mnt/onedrive /mnt/gd ,那么这里就填写 /mnt
// 通常配置一个远程挂载根路径就够了,默认非此路径开头文件将转给原始 emby 处理,不用重复填写至 disableRedirectRule
// 如果没有挂载,全部使用 strm 文件,此项填[""],必须要是数组
const mediaMountPath = ["/media"];

// emby/jellyfin api key, 在 emby/jellyfin 后台设置
const embyApiKey = "496e4bdc15af44a4a28f5463339f****";

// 访问宿主机上 5244 端口的 alist 地址, 要注意 iptables 给容器放行端口
const alistAddr = "http://192.168.110.65:5244";

// alist token, 在 alist 后台查看
const alistToken = "alist-66952dcf-9e23-47ad-9208-0e94dbd8095fJloIREF8yDaW2yW17Q59Otgrq0PRxHEvvzGEhvRTphfL2eZegH6gdbLf6jHJ***";

// alist 是否启用了 sign
const alistSignEnable = true;

// alist 中设置的直链过期时间,以小时为单位
const alistSignExpireTime = 12;

**Comment by chen3861229** [comment]
不好意思，才看到链接中的`sign=uctHM9CtZWIY8zE6f6zr08GR_U5LiUMToYsqjKPsZQc=:0`，这个应该是生成 strm 的时候已经写死在 strm 内部了，暂时还是只能关闭 alist 的 sign 用了

**Comment by tianshan2024** [comment]
现在关闭了，也还是没有播放记录，都怀疑是emby的问题了，但是在8096直接访问的时候还有播放记录，真的是奇怪

**Comment by chen3861229** [comment]
1.虽然修复了下`strm`内部链接假如有过期`sign`参数的重新计算和覆盖，但依旧是解决不了描述的问题现象，https://github.com/chen3861229/embyExternalUrl/commit/d5a4884cf1780468c3cbde1615da854996297b96

2.没有播放记录的情况，历史 issus 中很多，根本原因了 emby 入库媒体时，没有/无法访问/被强制取消了媒体分析，导致的 emby 媒体详细信息中没有`可播放时长/runtimeTicks`，结合你的实际情况，是`strm`中已存在的`sign`过期了，导致 emby 服务端分析媒体时访问不了，解决方案，还是只能关闭 alist 的 sign 参数，因为此脚本动态重新计算`sign`参数只作用于客户端的播放成功，而`emby 服务端自身`假如`sign`失效，是等同于链接不通，然后需要依赖**官方 emby 客户端**首次播放会补充回传 strm 缺失的媒体信息这点，才能正常记录播放记录，对于这点，另外一个可选方案为，假如需要事先在服务端批量补充`strm`入库时缺失的媒体编码信息，可以使用 https://github.com/sjtuross/StrmAssistant
