### ISSUE TITLE
jellyfin+MediaLinker（docker）+alist（阿里云盘仅三方权益无svip）+rclone

### ISSUE THREAD

**Issue by XCJYO** [chen3861229/embyExternalUrl#77]
配置为阿里云2H2G服务器带宽3M CentOS 7.9 64位
 

alist宿主机安装，挂载了阿里云盘，有三方权益包，无svip，关闭了签名
rclone挂载alist到linux本地/mnt文件夹下
jellyfin宿主机安装， **没有**采用strm文件的方式
采用[集成版 docker 一键部署方式](https://github.com/thsrite/MediaLinker?tab=readme-ov-file)部署了MediaLinker

```
docker run -d \
    --name MediaLinker \
    -p 8091:8091 \
    -v /home/MediaLinker/:/opt/ \
    thsrite/medialinker:latest
 ```

 /home/MediaLinker/constant.js文件修改了6处
 
```
// 这里默认 emby/jellyfin 的地址是宿主机,要注意 iptables 给容器放行端口
const embyHost = "http://139.196.*****:8096";
const embyApiKey = "a39b5e6ae*****";
const mediaMountPath = ["/mnt"];
const alistAddr = "http://139.196.*****:5244";


另外我按照说明改为了小写
  // 注意 jellyfin 是小写开头 mediaSourceId
  keyExpression: "r.uri:r.args.mediaSourceId", // "r.uri:r.args.MediaSourceId:r.args.X-Emby-Device-Id"

206行
const clientSelfAlistRule = [
  [2, strHead.ali, alistPublicAddr],

```

配置后很好用，infuse/kodi添加jellyfin都成功转发到了alist的阿里云直链进行播放

但是jellyfin的网页端和客户端无法播放视频，这是正常现象吗？还是constant.js文件没改好吗
由于阿里云服务器上还需要配置魔力 emby才能正常刮削就用了jellyfin，jellyfin可以直接豆瓣刮削
有大佬了解吗😄

**Comment by chen3861229** [comment]
1.配置没太大问题，不过这个`[2, strHead.ali, alistPublicAddr]`建议注释掉，因为阿里没有限制 UA，注释掉直链缓存命中率更高，默认放在这儿可能造成了误解，只是上一行的`[2, strHead["115"], alistPublicAddr],`默认`115`的处理在某些情况下必须的

2.对比`nfuse/kodi`直链成功了，而`jellyfin的网页端和客户端无法播放视频`，怀疑是播放媒体的编码格式支持问题，建议找个最普通的`mp4 h264 aac`的视频对比一下，假如可以正常直链播放，那就是`jellyfin的网页端和客户端`支持播放的媒体编码太少了，已知的话，`emby/jellyfin的网页端`支持的格式最少，`HEVC`编码只在谷歌内核浏览器可以播放成功，音频方面也是少得可怜，`DTS`等都是不支持的

3.假如实在需要`jellyfin的网页端和客户端`支持播放，解决方案是开启允许转码参数，原理上和直链播放是互斥的，走了服务端转码，流量是服务器中转的，客户端播放速度受限于服务器机器的上行带宽，
只用改`emby2Alist\nginx\conf.d\config\constant-transcode.js`的`transcodeConfig.enable = true`
```js
// 转码配置,默认 false,将按之前逻辑禁止转码处理并移除转码选项参数,与服务端允许转码配置有相关性
const transcodeConfig = {
  enable: true, // 此大多数情况下为允许转码的总开关
}
```

**Comment by XCJYO** [comment]
测试了mp4  aac也是失败，jellyfin 网页端也不重要
我还以为是我没配置好导致的，现在明白配置没问题就OK了，感谢大佬🙏♥️♥️♥️
