### ISSUE TITLE
plex使用vidhub/infuse播放无法加载外挂字幕

### ISSUE THREAD

**Issue by zfhxi** [chen3861229/embyExternalUrl#78]
如题，不知道是不是plex官方修改了什么东西，之前用plex2alist就可以加载外挂字幕播放的，现在不行了，将plex media server降级似乎也不行。

下图是使用vidhub添加plex播放（通过plex2alist的端口连接）时，选字幕的截图：

<img width="1659" alt="plex2alist-play" src="https://github.com/user-attachments/assets/e1d14b17-ee38-436a-9f00-e8941fde9563">

下图是使用vidhub添加emby播放（通过emby2alist的端口连接）时，选字幕的截图：

<img width="1771" alt="emby2alist_play" src="https://github.com/user-attachments/assets/ad2da162-c80d-4128-a25c-978be32dede1">

可以看到，emby2alist是能加载外挂字幕的。我不清楚问题出现在哪一层，也不知道是不是我个体的原因。

视频文件的组织结构：

<img width="1244" alt="16_22_33-1732638152877" src="https://github.com/user-attachments/assets/6c749a90-1cc4-4982-bde4-c0c17ebcee99">

大家能否帮着测试下，你们带有外挂字幕的视频，是否能通过plex2alist来正常加载。

**Comment by chen3861229** [comment]
经过测试，这是`Vidhub`播放器自身的 bug，`/library/metadata`接口中的数据都是一样的，我这边只是测试出来修补`Part(Array).Stream(Array)`的外挂字幕缺失的`index`属性，vidhub 的详情页下边就会出现外挂字幕信息，但是播放器界面依旧没有选择外挂字幕的选项，正当修补同样缺失的`title`属性时，达到收费限制了(免费只允许播放5次)，无法继续测试了，综合结论，最好向播放器官方反馈 bug

![image](https://github.com/user-attachments/assets/1dcfc293-79b8-4937-952d-8dd8f8727e4e)

```js
if (r.uri.includes("/library/metadata")) {
      r.warn(`part.Stream: ${JSON.stringify(part.Stream)}`);
      part.Stream.map((stream, i) => {
        if (!stream.index) {
          stream.index = i;
        }
        if (!stream.title) {
          stream.title = stream.displayTitle;
        }
      });
    }
```
