### ISSUE TITLE
一鍵docker部署后ui不显示

### ISSUE THREAD

**Issue by 434387713** [chen3861229/embyExternalUrl#79]
使用集成docker安裝完是不是必須安裝下面的脚本才能正常使用
![image](https://github.com/user-attachments/assets/5cb2d21a-8fd9-44db-8f9b-e0d97eb7f966)

**Comment by chen3861229** [comment]
1.请问是哪一个？
emby2Alist	emby/jellyfin 重定向到 alist 直链 
embyAddExternalUrl	emby/jellyfin 全客户端(除TV端)添加调用外部播放器按钮 
embyWebAddExternalUrl	emby/jellyfin/alistWeb 调用外部播放器用户脚本,只支持网页 
plex2Alist	plex 重定向到 alist 直链

2.通过`ui不显示`判断，应该指的是`embyWebAddExternalUrl`或`embyAddExternalUrl`，这两个涉及到 UI 上的外部播放器按钮功能了，文档上稍微写得有些混淆(之后将改进)，这两个需要按照对应 md文档下的集成方式手动改一下，docker 集成中的没有这两个
