### ISSUE TITLE
关于web端播放的问题

### ISSUE THREAD

**Issue by free-150** [chen3861229/embyExternalUrl#80]
我在这个[链接](https://github.com/bpking1/embyExternalUrl/blob/main/FAQ.md#6115-%E5%86%85%E5%AE%B9%E6%97%A0%E6%B3%95-web-%E7%AB%AF%E6%92%AD%E6%94%BEhtmlvideoplayer-%E8%B7%A8%E5%9F%9F)看到现在不需要装插件就可以直接在网页版 emby 上302，我试了一下，有的片可以302，有的片却提示没有兼容的流是什么原因？还是说对视频有什么要求

**Comment by chen3861229** [comment]
是的，应为 302 播放的都是原始视频格式，`有的片却提示没有兼容的流是什么原因`这个是 web 浏览器自身对于高级的视频/音频编码格式不支持，有两种选择

1.保持直链，使用对应平台的客户端播放，大部分客户端支持的媒体格式比浏览器广很多

2.脚本中开启允许转码，与直链是互斥行为，这样和源服务是一样的，web 浏览器播放不兼容的媒体格式，会走源服务转码播放,
配置位于`emby2Alist\nginx\conf.d\config\constant-transcode.js`中
```js
// 转码配置,默认 false,将按之前逻辑禁止转码处理并移除转码选项参数,与服务端允许转码配置有相关性
const transcodeConfig = {
  enable: true, // 此大多数情况下为允许转码的总开关
  enableStrmTranscode: false, // 默认禁用 strm 的转码,体验很差,仅供调试使用
  ...
};
```

**Comment by free-150** [comment]
好的，谢谢
