### ISSUE TITLE
alistSignEnable=true时获取的alist链接签名丢失

### ISSUE THREAD

**Issue by zfhxi** [chen3861229/embyExternalUrl#82]
我在alist webui设置-》全局页面中开启了`签名所有`，并且`直链有效期`设为12。

`constant-mount.js`中设置了：
```js
// alist 是否启用了 sign
const alistSignEnable = true;

// alist 中设置的直链过期时间,以小时为单位,严格对照 alist 设置 => 全局 => 直链有效期
const alistSignExpireTime = 12
```
并且`clientSelfAlistRule`保持默认值：
```js
const clientSelfAlistRule = [
  [2, strHead["115"], alistPublicAddr],
]
```

然而，当我将源码更新到commit为[b1baa55](https://github.com/chen3861229/embyExternalUrl/commit/b1baa5549224175417a5adbcf4b7979a68ac3a21)时，
nginx error.log中转换后的alist链接为`http://alist.example.com/xxxx.mkv`，无法播放，似乎丢掉了签名。

当将`clientSelfAlistRule`改为空数组时：
```js
const clientSelfAlistRule = [
  // [2, strHead["115"], alistPublicAddr],
]
```
后台日志中可以发现处理后的url为`https://cdnfhnfile.115.com/xxx……`，是可以播放的，

在使用[08e54df](https://github.com/chen3861229/embyExternalUrl/commit/08e54df25c04be72c2d0a35dda9ca01d14474fd6)commit（以及之前的commit）时，是会附带sign信息的，如`http://alist.example.com/xxxx.mkv?sign=xxxx`

因此，初步猜测`b1baa55`及之后commit版本的源码，当开启`alistSignEnable`时，似乎最终得到的alist链接中会丢掉alist的签名。

**Comment by chen3861229** [comment]
多谢提供详细的信息，节省了不少时间，排查得是没错的
